//! # `tabula-assets` — versioned, hashed asset packs
//!
//! > ## PHASE 3
//!
//! The planned product ships **per-game packs delivered from a CDN and cached
//! locally**, not bundled into app releases (ADR-017). This crate owns validated
//! manifests, identities, explicit resources, pack/game binding, structural
//! pixel regions, pure deterministic resolution, and the platform-neutral port
//! for obtaining physical asset bytes. It does not implement filesystem,
//! network, or browser I/O.
//!
//! ## Current manifest (doc 04 §12.3)
//!
//! This is the exact pure manifest shape accepted today. Parsing and validation
//! operate on metadata only: they do not read asset files or create backend
//! handles.
//!
//! ```toml
//! # generated by `cargo xtask pack-assets`; served as `pack.json` by delivery infrastructure
//! pack    = "sample"
//! version = "1.0.0"
//! game    = "com.example.sample"
//!
//! [[files]]
//! name     = "pieces@2x.atlas"
//! path     = "sample/1.0.0/pieces@2x.png"
//! hash     = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
//! bytes    = 412_003
//! priority = "critical"      # critical | high | low
//! density  = 2
//!
//! [[resources]]
//! id = "pieces/white-knight"
//!
//! [[resources.variants]]
//! file = "pieces@2x.atlas"
//! region = { x = 0, y = 0, width = 128, height = 128 }
//! ```
//!
//! ## Planned rules for trustworthy asset delivery
//!
//! 1. **Content-hashed paths.** A given URL's bytes never change, so the cache is
//!    immutable and `Cache-Control: immutable` is honest.
//! 2. **Integrity check on load.** A cached file whose blake3 does not match the
//!    manifest is discarded, not used. Silent corruption is worse than a re-fetch.
//! 3. **Priority-driven loading.** `critical` blocks the branded loader; `high`
//!    loads during the first turn; `low` loads lazily. A player should be looking
//!    at a board, not a spinner.
//! 4. **Density variants** are picked from `FrameCtx.dpi`, so a phone does not
//!    download a desktop atlas.
//!
//! Implemented now:
//! - manifest TOML parsing with unknown-field rejection;
//! - validated pack, file-name, path, size, density, priority, and hash metadata;
//! - duplicate file-name/path detection;
//! - explicit [`AssetResource`] declarations from [`tabula_game_api::AssetRef`]
//!   values to physical file variants;
//! - typed pack binding through [`BoundAssetPack`];
//! - deterministic, pure density selection returning [`ResolvedAsset`] metadata;
//! - structurally valid source-pixel regions, without decoded-image bounds checks;
//! - pure byte-level integrity verification against manifest-declared size and
//!   BLAKE3 digest ([`AssetFile::verify_bytes`] returning a [`VerifiedAssetBytes`] witness);
//! - the [`AssetSource`] port, explicit [`UnverifiedAssetBytes`] state, and
//!   deterministic [`MemoryAssetSource`] reference adapter;
//! - the thin [`load_verified`] orchestration boundary returning owned
//!   [`OwnedVerifiedAssetBytes`] values.
//!
//! Not implemented yet:
//! - filesystem, HTTP, or browser asset-source implementations;
//! - cache management or CDN URL/signature generation;
//! - decoding or renderer handles.

#![forbid(unsafe_code)]

mod integrity;
mod loader;
mod manifest;
mod source;

pub use integrity::{AssetIntegrityError, OwnedVerifiedAssetBytes, VerifiedAssetBytes};
pub use loader::{load_verified, AssetLoadError};
pub use manifest::{
    AssetByteSize, AssetByteSizeError, AssetContentHash, AssetContentHashError, AssetDensity,
    AssetDensityError, AssetFile, AssetFileName, AssetFileNameError, AssetPackId, AssetPackIdError,
    AssetPackManifest, AssetPackRef, AssetPackRefError, AssetPackVersion, AssetPath,
    AssetPathError, AssetPixelRegion, AssetPixelRegionError, AssetPriority, AssetResolveError,
    AssetResource, AssetResourceVariant, BoundAssetPack, ManifestBindingError, ManifestError,
    ResolvedAsset,
};
pub use source::{AssetSource, MemoryAssetSource, MemoryAssetSourceError, UnverifiedAssetBytes};
