//! Literal rulebook/counter arithmetic fixtures, not match simulation.
//!
//! The contact tables are authored from the one-stage armor-only algebra in
//! MATH.md. Catalog HP/damage/armor are shared trusted inputs; literal expected
//! contact counts are read from that reviewed document, never generated by the
//! multi-stage implementation under test. Skills/movement/economy are excluded.

use tabula_game_age_war::catalog::UNITS;
use tabula_game_age_war::math::{ceil_div, damage_after_modifiers, HitInput};
use tabula_game_age_war::schema::{Age, DamageKind, UnitRole, UnitSpec};

const RULEBOOK: &str = include_str!("../../../docs/games/age-war/MATH.md");
const AGES: [(Age, &str); 6] = [
    (Age::Primitive, "Primitive"),
    (Age::Ancient, "Ancient"),
    (Age::Feudal, "Feudal"),
    (Age::Arcane, "Arcane"),
    (Age::Industrial, "Industrial"),
    (Age::Future, "Future"),
];

fn unit(age: Age, role: UnitRole) -> &'static UnitSpec {
    UNITS
        .iter()
        .find(|unit| unit.age == age && unit.role == role)
        .expect("catalog has exactly one unit for every age/role")
}

fn expected_rows(attacker: &str, defender: &str) -> Vec<[u64; 6]> {
    let heading = format!("### {attacker} → {defender}");
    let section = RULEBOOK
        .split(&heading)
        .nth(1)
        .expect("literal matrix exists");
    let rows: Vec<_> = section
        .lines()
        .skip(1)
        .take_while(|line| !line.starts_with('#'))
        .filter(|line| {
            ["| F |", "| R |", "| T |", "| K |", "| H |", "| S |"]
                .iter()
                .any(|prefix| line.starts_with(prefix))
        })
        .map(|line| {
            let values: Vec<u64> = line
                .split('|')
                .skip(2)
                .take(6)
                .map(|value| value.trim().parse().expect("literal positive integer cell"))
                .collect();
            values.try_into().expect("six literal defender columns")
        })
        .collect();
    assert_eq!(rows.len(), 6, "six literal attacker rows");
    rows
}

#[test]
fn all_576_within_and_adjacent_age_contact_oracles_match() {
    let mut tables = 0;
    let mut cells = 0;
    for (from_index, (from_age, from_name)) in AGES.iter().enumerate() {
        for (to_index, (to_age, to_name)) in AGES.iter().enumerate() {
            if from_index.abs_diff(to_index) > 1 {
                continue;
            }
            let expected = expected_rows(from_name, to_name);
            for (row, from_role) in UnitRole::ALL.iter().enumerate() {
                let source = unit(*from_age, *from_role);
                for (column, to_role) in UnitRole::ALL.iter().enumerate() {
                    let target = unit(*to_age, *to_role);
                    let channel = match source.attack.kind {
                        DamageKind::Physical => 0,
                        DamageKind::Arcane => 1,
                        DamageKind::Siege => 2,
                    };
                    let damage = damage_after_modifiers(HitInput {
                        base_damage: u32::from(source.attack.damage),
                        attack_bonus_bp: 0,
                        action_multiplier_bp: 10_000,
                        armor_bp: target.armor_bp[channel].get(),
                        defense_bonus_bp: 0,
                        shred_bp: 0,
                        pierce_bp: 0,
                        guard_bp: 0,
                    })
                    .expect("valid catalog armor-only packet");
                    let actual = ceil_div(u64::from(target.hp), u64::from(damage))
                        .expect("nonzero catalog packet");
                    assert_eq!(
                        actual,
                        expected[row][column],
                        "{} → {}",
                        source.id.as_str(),
                        target.id.as_str()
                    );
                    cells += 1;
                }
            }
            tables += 1;
        }
    }
    assert_eq!(tables, 16);
    assert_eq!(cells, 576);
}
