//! Bounded original Werewolf portraits. (doc 04 §12, ADR-017)
//!
//! Role assets are ordinary public artwork. Their availability never encodes a
//! match assignment; the presenter chooses a front only from an authorized View.
//! No all-role source atlas, seed or action history enters runtime resources.

use tabula_game_api::AssetRef;
use tabula_presentation::AssetPackRef;

use crate::Role;

/// Exact version-pinned pack metadata generated by `cargo xtask pack-assets werewolf`.
pub const MANIFEST: &str = include_str!("../../assets/fixture.pack.toml");

/// Native fixtures embed only bounded independent images, never the source atlas.
#[cfg(not(target_arch = "wasm32"))]
pub const ALL_IMAGES: &[(&str, &[u8])] = &[
    (
        "villager@1x.image",
        include_bytes!("../../assets/villager@1x.png"),
    ),
    (
        "villager@2x.image",
        include_bytes!("../../assets/villager@2x.png"),
    ),
    (
        "werewolf@1x.image",
        include_bytes!("../../assets/werewolf@1x.png"),
    ),
    (
        "werewolf@2x.image",
        include_bytes!("../../assets/werewolf@2x.png"),
    ),
    ("seer@1x.image", include_bytes!("../../assets/seer@1x.png")),
    ("seer@2x.image", include_bytes!("../../assets/seer@2x.png")),
    (
        "doctor@1x.image",
        include_bytes!("../../assets/doctor@1x.png"),
    ),
    (
        "doctor@2x.image",
        include_bytes!("../../assets/doctor@2x.png"),
    ),
    (
        "hunter@1x.image",
        include_bytes!("../../assets/hunter@1x.png"),
    ),
    (
        "hunter@2x.image",
        include_bytes!("../../assets/hunter@2x.png"),
    ),
    (
        "witch@1x.image",
        include_bytes!("../../assets/witch@1x.png"),
    ),
    (
        "witch@2x.image",
        include_bytes!("../../assets/witch@2x.png"),
    ),
    ("back@1x.image", include_bytes!("../../assets/back@1x.png")),
    ("back@2x.image", include_bytes!("../../assets/back@2x.png")),
    (
        "village-night@1x.image",
        include_bytes!("../../assets/village-night@1x.png"),
    ),
    (
        "village-night@2x.image",
        include_bytes!("../../assets/village-night@2x.png"),
    ),
    (
        "village-dawn@1x.image",
        include_bytes!("../../assets/village-dawn@1x.png"),
    ),
    (
        "village-dawn@2x.image",
        include_bytes!("../../assets/village-dawn@2x.png"),
    ),
];

/// Logical images needed by this local simulator, all independent of assignments.
#[must_use]
pub fn gameplay_resources() -> Vec<AssetRef> {
    Role::ALL
        .into_iter()
        .map(role_asset)
        .chain([back_asset(), scene_asset(true), scene_asset(false)])
        .collect()
}

/// Exact artwork identity, independent of physical density resolution.
#[must_use]
pub fn asset_pack() -> AssetPackRef {
    AssetPackRef::from_static("werewolf", "0.2.0")
}

/// One portrait identity, chosen only after an authorized own-role reveal.
#[must_use]
pub fn role_asset(role: Role) -> AssetRef {
    let name = match role {
        Role::Villager => "villager",
        Role::Werewolf => "werewolf",
        Role::Seer => "seer",
        Role::Doctor => "doctor",
        Role::Hunter => "hunter",
        Role::Witch => "witch",
    };
    AssetRef::new(format!("cards/{name}")).expect("closed role vocabulary is canonical")
}

/// One common opaque back for every concealed role and outside perspective.
#[must_use]
pub fn back_asset() -> AssetRef {
    AssetRef::new("cards/back").expect("literal resource is canonical")
}

/// Original village artwork; its lighting depends only on the public phase.
pub fn scene_asset(night: bool) -> AssetRef {
    AssetRef::new(if night {
        "scenes/village-night"
    } else {
        "scenes/village-dawn"
    })
    .expect("closed scene vocabulary")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tabula_assets::{AssetDensity, AssetPackManifest};
    use tabula_core::GameId;

    #[test]
    #[cfg(not(target_arch = "wasm32"))]
    fn bounded_independent_images_match_pinned_metadata() {
        let manifest = AssetPackManifest::from_toml(MANIFEST).unwrap();
        assert_eq!(manifest.files().len(), 18);
        assert_eq!(ALL_IMAGES.len(), 18);
        let mut encoded = 0;
        for file in manifest.files() {
            let bytes = ALL_IMAGES
                .iter()
                .find(|(name, _)| *name == file.name().as_str())
                .unwrap()
                .1;
            file.verify_bytes(bytes).unwrap();
            assert_eq!(&bytes[..8], b"\x89PNG\r\n\x1a\n");
            let width = u32::from_be_bytes(bytes[16..20].try_into().unwrap());
            let height = u32::from_be_bytes(bytes[20..24].try_into().unwrap());
            assert!(width <= 1280 && height <= 720);
            assert!(u64::from(width) * u64::from(height) * 4 <= 4 * 1024 * 1024);
            encoded += bytes.len();
        }
        assert!(encoded <= 4 * 1024 * 1024);
    }

    #[test]
    fn all_roles_and_back_resolve_at_both_densities_without_atlas_regions() {
        let manifest = AssetPackManifest::from_toml(MANIFEST).unwrap();
        let game = GameId::new("com.tabula.werewolf").unwrap();
        let pack = asset_pack();
        let bound = manifest.validate_binding(&pack, &game).unwrap();
        assert_eq!(manifest.resources().len(), 9);
        for asset in gameplay_resources() {
            for d in [1, 2] {
                let density = AssetDensity::new(d).unwrap();
                let image = bound.resolve(&asset, density).unwrap();
                assert_eq!(image.file().density(), Some(density));
                assert!(image.region().is_none());
            }
        }
    }
}
