//! # `tabula-web` — the Leptos application shell
//!
//! > ## PHASE 5
//! >
//! > Gate: chess and cards are playable between two devices over the internet
//! > (Phase 4 exit). The shell is built on a working protocol, not the reverse.
//!
//! Phase 5's goal in one sentence: **a stranger can sign up, browse, create or
//! join a room, get matched, play, and see their results.**
//!
//! ## Routes (doc 04 §2.1)
//!
//! ```text
//! /                     home · continue playing · featured games
//! /login  /register     auth
//! /games                catalog (filter by category, players, duration, complexity)
//! /games/:id            game detail · rules · config presets · play buttons
//! /rooms                room browser
//! /rooms/:id            room detail: seats, ready, invite, room chat, settings
//! /queue                matchmaking status
//! /play/:match_id       → HANDS OFF to the game runtime (a separate document)
//! /matches/:id          post-match summary · replay viewer · rematch
//! /u/:handle            profile · stats · history
//! /friends              social
//! /settings             account · appearance · motion · accessibility · audio · privacy
//! /shop                 cosmetics (later)
//! /admin/*              operator tooling — role-gated, SEPARATE BUNDLE
//! ```
//!
//! `/play/:match_id` is **not a Leptos route into a canvas**. It is a real
//! navigation to a minimal HTML page that boots `game.wasm` (ADR-011).
//!
//! ## State (doc 04 §2.2)
//!
//! ```rust,ignore
//! #[derive(Clone)]
//! pub struct AppState {
//!     pub session:  RwSignal<Option<SessionInfo>>,
//!     pub catalog:  Resource<(), Vec<GameSummary>>,   // cached, ETag-revalidated
//!     pub presence: RwSignal<PresenceMap>,
//!     pub room:     RwSignal<Option<RoomView>>,
//!     pub queue:    RwSignal<QueueState>,
//!     pub prefs:    RwSignal<Preferences>,            // persisted via KvStore
//!     pub net:      StoredValue<LobbyClient>,         // LOBBY TOPICS ONLY
//! }
//! ```
//!
//! Three rules that keep this simple:
//!
//! 1. **The shell holds one WebSocket, for lobby and social topics only.** It
//!    does *not* hold the match socket — that belongs to the game runtime.
//! 2. **All server data is typed via `tabula-protocol`.** No hand-written JSON;
//!    sharing Rust types with the server is most of the reason the shell is
//!    Leptos rather than TypeScript.
//! 3. `RwSignal` for live state, `Resource` for server-cached collections,
//!    `StoredValue` for the non-reactive client handle. No Redux-alike.
//!
//! ## Styling
//!
//! Class-based components (`btn btn--filled`) with a `data-state` attribute
//! driving state layers. Component CSS consumes **only** the CSS variables in
//! the generated `style/tokens.css`.
//!
//! **No hex literals anywhere in this crate** — `xtask check-no-raw-colors`
//! greps for them.
//!
//! ## Exit criteria (doc 07 Phase 5)
//!
//! ```text
//! [ ] the stranger demo passes
//! [ ] Lighthouse performance >= 85, accessibility >= 95
//! [ ] keyboard-only play for all three games
//! [ ] the queue matches within 30 s at test population
//! [ ] an admin can disable a game WITHOUT A DEPLOY
//! ```
//!
//! ## Module layout when this becomes real
//!
//! ```text
//! src/main.rs       mount, router, context provision
//! src/state.rs      AppState                                (doc 04 §2.2)
//! src/api.rs        typed HTTP client over tabula-protocol
//! src/routes/       one module per route above
//! src/components/   the shared component inventory (doc 04 §14.1)
//! style/tokens.css  GENERATED by `xtask gen-tokens` — do not edit
//! style/            hand-written component CSS, vars only
//! index.html        trunk entry point
//! ```

fn main() {
    eprintln!(
        "tabula-web is a Phase 5 deliverable (docs/architecture/07-phases-and-implementation-roadmap.md).\n\
         Gate: chess and cards playable between two devices over the internet (Phase 4 exit)."
    );
    std::process::exit(1);
}
