//! # `tabula-web` — the Leptos application shell
//!
//! > ## PHASE 5 — the discovery routes are implemented ahead of the gate
//! >
//! > Gate: chess and Caro are playable between two devices over the internet
//! > (Phase 4 exit). The shell is built on a working protocol, not the reverse.
//! >
//! > `/`, `/games` and `/games/:id` (with its `?setup=1` substate) are
//! > implemented anyway, as a recorded decision: see
//! > `docs/adr/0028-discovery-shell-ahead-of-phase-gate.md`. Every other route
//! > remains gated except the isolated account-state routes under ADR-0036
//! > and configured Kanidm continuation under ADR-0038. ADR-0043 adds bounded
//! > verified enrollment, self-profile editing, permitted other profiles and
//! > social snapshots when the isolated authority advertises those capabilities.
//! > Default and production compositions remain closed.
//! > The optional `/play/local/` handoff opens
//! > the existing standalone hot-seat runtime as a separate document
//! > (ADR-0030, retaining ADR-011). The shell creates no match and provides no
//! > network authority.
//!
//! Phase 5's goal in one sentence: **a stranger can sign up, browse, create or
//! join a room, get matched, play, and see their results.**
//!
//! ## Routes (doc 04 §2.1)
//!
//! ```text
//! /                     home · continue playing · featured games
//! /account  /me         isolated account state · self-only profile and editing
//! /login                configured Kanidm continuation
//! /register             verified enrollment · explicit sign-in after acceptance
//! /games                catalog (filter by category, players, duration, complexity)
//! /games/:id            game detail · rules · config presets · play buttons
//! /rooms                room browser
//! /rooms/:id            room detail: seats, ready, invite, room chat, settings
//! /queue                matchmaking status
//! /play/:match_id       → HANDS OFF to the game runtime (a separate document)
//! /matches/:id          post-match summary · replay viewer · rematch
//! /u/:handle            authority-permitted other-profile projection
//! /friends              permitted search · request decisions · scoped presence
//! /settings             account · appearance · motion · accessibility · audio · privacy
//! /shop                 cosmetics (later)
//! /admin/*              operator tooling — role-gated, SEPARATE BUNDLE
//! ```
//!
//! `/play/:match_id` is **not a Leptos route into a canvas**. It is a real
//! navigation to a minimal HTML page that boots `game.wasm` (ADR-011).
//!
//! ## State (doc 04 §2.2)
//!
//! ```rust,ignore
//! #[derive(Clone)]
//! pub struct AppState {
//!     pub session:  RwSignal<Option<SessionInfo>>,
//!     pub catalog:  Resource<(), Vec<GameSummary>>,   // cached, ETag-revalidated
//!     pub presence: RwSignal<PresenceMap>,
//!     pub room:     RwSignal<Option<RoomView>>,
//!     pub queue:    RwSignal<QueueState>,
//!     pub prefs:    RwSignal<Preferences>,            // persisted via KvStore
//!     pub net:      StoredValue<LobbyClient>,         // LOBBY TOPICS ONLY
//! }
//! ```
//!
//! Three rules that keep this simple:
//!
//! 1. **The shell holds one WebSocket, for lobby and social topics only.** It
//!    does *not* hold the match socket — that belongs to the game runtime.
//! 2. **All server data is typed via `tabula-protocol`.** No hand-written JSON;
//!    sharing Rust types with the server is most of the reason the shell is
//!    Leptos rather than TypeScript.
//! 3. `RwSignal` for live state, `Resource` for server-cached collections,
//!    `StoredValue` for the non-reactive client handle. No Redux-alike.
//!
//! ## Styling
//!
//! Class-based components (`btn btn--filled`) with a `data-state` attribute
//! driving state layers. Component CSS consumes **only** the CSS variables in
//! the generated `style/tokens.css`.
//!
//! **No hex literals anywhere in this crate** — `xtask check-no-raw-colors`
//! greps for them.
//!
//! ## Exit criteria (doc 07 Phase 5)
//!
//! ```text
//! [ ] the stranger demo passes
//! [ ] Lighthouse performance >= 85, accessibility >= 95
//! [ ] keyboard-only play for all three games
//! [ ] the queue matches within 30 s at test population
//! [ ] an admin can disable a game WITHOUT A DEPLOY
//! ```
//!
//! ## Module layout
//!
//! ```text
//! src/main.rs       mount
//! src/views/        one module per implemented route, plus shared chrome
//! src/account.rs    isolated account lifecycle + same-origin Fetch adapter
//! src/i18n.rs       shell copy merged with the catalog's own tables
//! src/query.rs      Library constraints <-> the address bar
//! src/setup.rs      the setup draft and its state machine
//! style/tokens.css  GENERATED by `xtask gen-tokens` — do not edit
//! style/app.scss    hand-written component CSS, vars only
//! index.html        trunk entry point
//! ```
//!
//! Still to come with the gate: `src/state.rs` (`AppState`, doc 04 §2.2) and
//! `src/api.rs` (a typed client over `tabula-protocol`). Neither exists yet
//! for the future lobby/networked shell. The bounded `src/account.rs` adapter
//! consumes `tabula-session-http` DTOs only; it is not that broad AppState/API.
//!
//! ## What this crate must never know
//!
//! A game. Not its id, not its config fields, not its message keys. The whole
//! catalog arrives through `tabula-registry`'s erased interfaces, and the game
//! copy arrives as data from `Catalog::messages` (I-9, enforced by
//! `xtask check-no-game-ids`, which treats this crate as restricted).

mod account;
#[cfg(feature = "account-social")]
mod accounts_full;
mod i18n;
#[cfg(any(feature = "online", feature = "account-social", test))]
mod json;
#[cfg(feature = "online")]
mod online;
mod query;
mod setup;
#[cfg(feature = "account-social")]
mod social_full;
mod views;

fn main() {
    leptos::mount::mount_to_body(views::App);
}
