package com.loveoverflow.tabula.mobile.localization

/** Account task vocabulary shared with the web where capabilities are equivalent (ADR-0046). */
enum class AccountCopy {
    Intro, Status, Checking, Loading, SigningOut, SignedOut, SignedOutBody, SignedIn, SignedInBody,
    Expired, ExpiredBody, Unavailable, NativeUnavailableBody, ProviderUnavailableBody, BackendUnavailableBody, StorageUnavailableBody,
    Error, ErrorBody, SignOutUnconfirmedBody, CheckSession, Refresh, RetrySignOut, Cancel, StopWaiting,
    Login, LoginIntro, LoginUnavailable, LoginUnavailableBody, AlreadySignedIn, ProviderBoundary,
    Register, RegisterIntro, RegisterUnavailable, RegisterUnavailableBody, RegistrationDisposition,
    Profile, ProfileIntro, ReadOnly, AccountId, DisplayName, Handle, Visibility,
    VisibilityPublic, VisibilityFriends, VisibilityPrivate, ProfileMissing, ProfileMissingBody,
    OtherProfilesUnavailable, Friends, FriendsIntro, FriendsUnavailable, FriendsUnavailableBody,
    ProfileAction, ProfileActionBody, FriendsActionBody, SignOut, ConfirmSignOut, ConfirmSignOutBody,
    ConfirmSignOutAction, KeepSignedIn, LocalTitle, LocalBody, Library, Preferences,
    Avatar, NeutralAvatar, AuthAvailableLater,
}

/** Exhaustive vi/en copy. No capability or current account is inferred from the locale. */
fun ShellStrings.account(copy: AccountCopy): String = if (vietnamese) vietnameseAccount(copy) else englishAccount(copy)

private fun englishAccount(copy: AccountCopy): String = when (copy) {
    AccountCopy.Intro -> "Your account on this device."
    AccountCopy.Status -> "Account status"
    AccountCopy.Checking -> "Account status not checked"
    AccountCopy.Loading -> "Checking the current session…"
    AccountCopy.SigningOut -> "Signing out…"
    AccountCopy.SignedOut -> "Signed out"
    AccountCopy.SignedOutBody -> "There is no confirmed account session on this device."
    AccountCopy.SignedIn -> "Signed in"
    AccountCopy.SignedInBody -> "Identity is shown only from the current account session."
    AccountCopy.Expired -> "Session expired"
    AccountCopy.ExpiredBody -> "Your previous identity is no longer shown. Check your session or return to the library."
    AccountCopy.Unavailable -> "Account services unavailable"
    AccountCopy.NativeUnavailableBody -> "Account services are not connected in this mobile build."
    AccountCopy.ProviderUnavailableBody -> "The sign-in provider is unavailable. No account identity is shown."
    AccountCopy.BackendUnavailableBody -> "The account service is unavailable. Check again when the service is reachable."
    AccountCopy.StorageUnavailableBody -> "Secure account storage is unavailable on this device. Account access stays unavailable without a safe credential store."
    AccountCopy.Error -> "Could not confirm account status"
    AccountCopy.ErrorBody -> "Your identity is hidden until the current session can be confirmed. Try again when you’re ready."
    AccountCopy.SignOutUnconfirmedBody -> "Sign-out has not been confirmed. Your identity stays hidden until sign-out can be confirmed. Try sign-out again when you’re ready."
    AccountCopy.CheckSession -> "Check session"
    AccountCopy.Refresh -> "Refresh account"
    AccountCopy.RetrySignOut -> "Try sign-out again"
    AccountCopy.Cancel -> "Cancel check"
    AccountCopy.StopWaiting -> "Stop waiting"
    AccountCopy.Login -> "Sign in"
    AccountCopy.LoginIntro -> "Use your identity provider to access your Tabula account."
    AccountCopy.LoginUnavailable -> "Mobile sign-in unavailable"
    AccountCopy.LoginUnavailableBody -> "This mobile build is not connected to the provider sign-in flow. No password or sign-in code is collected here."
    AccountCopy.AlreadySignedIn -> "You already have a confirmed session. You can view your profile."
    AccountCopy.ProviderBoundary -> "When native sign-in is connected, your provider’s page will open in the system browser."
    AccountCopy.Register -> "Create account"
    AccountCopy.RegisterIntro -> "A Tabula account starts with a verified provider identity."
    AccountCopy.RegisterUnavailable -> "Mobile registration unavailable"
    AccountCopy.RegisterUnavailableBody -> "This mobile build is not connected to verified account enrollment. It cannot create an account."
    AccountCopy.RegistrationDisposition -> "On supported web builds, enrollment creates a Tabula profile after provider verification. You then choose Sign in; registration does not sign you in automatically."
    AccountCopy.Profile -> "Your profile"
    AccountCopy.ProfileIntro -> "Read the identity details provided by your current account session."
    AccountCopy.ReadOnly -> "Read-only identity"
    AccountCopy.AccountId -> "Account ID"
    AccountCopy.DisplayName -> "Display name"
    AccountCopy.Handle -> "Handle"
    AccountCopy.Visibility -> "Profile visibility"
    AccountCopy.VisibilityPublic -> "Public · visible to signed-in accounts"
    AccountCopy.VisibilityFriends -> "Friends · visible to accepted friends"
    AccountCopy.VisibilityPrivate -> "Private · visible only to you"
    AccountCopy.ProfileMissing -> "Profile details unavailable"
    AccountCopy.ProfileMissingBody -> "This session provides only your immutable account ID. No display name, handle or visibility was returned."
    AccountCopy.OtherProfilesUnavailable -> "Other profiles and profile editing are not connected in this mobile build."
    AccountCopy.Friends -> "Friends"
    AccountCopy.FriendsIntro -> "Your connections, with account-scoped privacy."
    AccountCopy.FriendsUnavailable -> "Mobile friends unavailable"
    AccountCopy.FriendsUnavailableBody -> "Friends, requests and live presence are not connected in this mobile build. No friend list or online status is inferred from your session."
    AccountCopy.ProfileAction -> "View your profile"
    AccountCopy.ProfileActionBody -> "Read only the identity details your session provides."
    AccountCopy.FriendsActionBody -> "See which social features are available in this build."
    AccountCopy.SignOut -> "Sign out"
    AccountCopy.ConfirmSignOut -> "Sign out on this device?"
    AccountCopy.ConfirmSignOutBody -> "The app will request sign-out. Your identity is hidden while the result is checked."
    AccountCopy.ConfirmSignOutAction -> "Confirm sign-out"
    AccountCopy.KeepSignedIn -> "Keep signed in"
    AccountCopy.LocalTitle -> "Explore without an account"
    AccountCopy.LocalBody -> "The library is always available. Local play needs no account when a native game is available in your build."
    AccountCopy.Library -> "Browse games"
    AccountCopy.Preferences -> "Appearance and language follow your device. Account preferences are not connected in this build."
    AccountCopy.Avatar -> "Profile image"
    AccountCopy.NeutralAvatar -> "Neutral profile image"
    AccountCopy.AuthAvailableLater -> "No local account is created by browsing or playing."
}

private fun vietnameseAccount(copy: AccountCopy): String = when (copy) {
    AccountCopy.Intro -> "Tài khoản của bạn trên thiết bị này."
    AccountCopy.Status -> "Trạng thái tài khoản"
    AccountCopy.Checking -> "Chưa kiểm tra trạng thái tài khoản"
    AccountCopy.Loading -> "Đang kiểm tra phiên hiện tại…"
    AccountCopy.SigningOut -> "Đang đăng xuất…"
    AccountCopy.SignedOut -> "Chưa đăng nhập"
    AccountCopy.SignedOutBody -> "Chưa có phiên tài khoản được xác nhận trên thiết bị này."
    AccountCopy.SignedIn -> "Đã đăng nhập"
    AccountCopy.SignedInBody -> "Danh tính chỉ được hiển thị từ phiên tài khoản hiện tại."
    AccountCopy.Expired -> "Phiên đã hết hạn"
    AccountCopy.ExpiredBody -> "Danh tính trước đó không còn được hiển thị. Kiểm tra phiên hoặc quay lại thư viện."
    AccountCopy.Unavailable -> "Dịch vụ tài khoản chưa khả dụng"
    AccountCopy.NativeUnavailableBody -> "Dịch vụ tài khoản chưa được kết nối trong bản dựng di động này."
    AccountCopy.ProviderUnavailableBody -> "Nhà cung cấp đăng nhập chưa khả dụng. Không có danh tính tài khoản nào được hiển thị."
    AccountCopy.BackendUnavailableBody -> "Dịch vụ tài khoản chưa khả dụng. Kiểm tra lại khi có thể kết nối dịch vụ."
    AccountCopy.StorageUnavailableBody -> "Bộ lưu trữ tài khoản an toàn chưa khả dụng trên thiết bị này. Chưa thể truy cập tài khoản nếu không có nơi lưu thông tin xác thực an toàn."
    AccountCopy.Error -> "Chưa thể xác nhận trạng thái tài khoản"
    AccountCopy.ErrorBody -> "Danh tính được ẩn cho đến khi phiên hiện tại được xác nhận. Bạn có thể thử lại khi sẵn sàng."
    AccountCopy.SignOutUnconfirmedBody -> "Chưa thể xác nhận đăng xuất. Danh tính vẫn được ẩn cho đến khi đăng xuất được xác nhận. Bạn có thể thử đăng xuất lại khi sẵn sàng."
    AccountCopy.CheckSession -> "Kiểm tra phiên"
    AccountCopy.Refresh -> "Làm mới tài khoản"
    AccountCopy.RetrySignOut -> "Thử đăng xuất lại"
    AccountCopy.Cancel -> "Hủy kiểm tra"
    AccountCopy.StopWaiting -> "Dừng chờ"
    AccountCopy.Login -> "Đăng nhập"
    AccountCopy.LoginIntro -> "Dùng nhà cung cấp danh tính để truy cập tài khoản Tabula."
    AccountCopy.LoginUnavailable -> "Đăng nhập mobile chưa khả dụng"
    AccountCopy.LoginUnavailableBody -> "Bản dựng di động này chưa kết nối luồng đăng nhập của nhà cung cấp. Không thu thập mật khẩu hay mã đăng nhập tại đây."
    AccountCopy.AlreadySignedIn -> "Bạn đã có phiên được xác nhận. Bạn có thể xem hồ sơ của mình."
    AccountCopy.ProviderBoundary -> "Khi đăng nhập native được kết nối, trang của nhà cung cấp sẽ mở trong trình duyệt hệ thống."
    AccountCopy.Register -> "Tạo tài khoản"
    AccountCopy.RegisterIntro -> "Tài khoản Tabula bắt đầu từ danh tính đã được nhà cung cấp xác minh."
    AccountCopy.RegisterUnavailable -> "Đăng ký mobile chưa khả dụng"
    AccountCopy.RegisterUnavailableBody -> "Bản dựng di động này chưa kết nối luồng đăng ký đã xác minh. Ứng dụng chưa thể tạo tài khoản."
    AccountCopy.RegistrationDisposition -> "Trong bản web có hỗ trợ, việc đăng ký tạo hồ sơ Tabula sau khi xác minh qua nhà cung cấp. Sau đó bạn chọn Đăng nhập; đăng ký không tự động đăng nhập."
    AccountCopy.Profile -> "Hồ sơ của bạn"
    AccountCopy.ProfileIntro -> "Xem thông tin danh tính được phiên tài khoản hiện tại cung cấp."
    AccountCopy.ReadOnly -> "Danh tính chỉ đọc"
    AccountCopy.AccountId -> "ID tài khoản"
    AccountCopy.DisplayName -> "Tên hiển thị"
    AccountCopy.Handle -> "Tên định danh"
    AccountCopy.Visibility -> "Phạm vi hiển thị hồ sơ"
    AccountCopy.VisibilityPublic -> "Công khai · tài khoản đã đăng nhập có thể xem"
    AccountCopy.VisibilityFriends -> "Bạn bè · bạn bè đã chấp nhận có thể xem"
    AccountCopy.VisibilityPrivate -> "Riêng tư · chỉ bạn có thể xem"
    AccountCopy.ProfileMissing -> "Chưa có thông tin hồ sơ"
    AccountCopy.ProfileMissingBody -> "Phiên này chỉ cung cấp ID tài khoản không thay đổi. Chưa có tên hiển thị, tên định danh hay phạm vi hiển thị được trả về."
    AccountCopy.OtherProfilesUnavailable -> "Hồ sơ của người khác và chỉnh sửa hồ sơ chưa được kết nối trong bản dựng di động này."
    AccountCopy.Friends -> "Bạn bè"
    AccountCopy.FriendsIntro -> "Các kết nối của bạn, với quyền riêng tư theo tài khoản."
    AccountCopy.FriendsUnavailable -> "Bạn bè mobile chưa khả dụng"
    AccountCopy.FriendsUnavailableBody -> "Bạn bè, lời mời và trạng thái trực tuyến chưa được kết nối trong bản dựng di động này. Không suy đoán danh sách bạn bè hay trạng thái online từ phiên tài khoản."
    AccountCopy.ProfileAction -> "Xem hồ sơ của bạn"
    AccountCopy.ProfileActionBody -> "Chỉ đọc thông tin danh tính được phiên cung cấp."
    AccountCopy.FriendsActionBody -> "Xem tính năng kết nối nào khả dụng trong bản dựng này."
    AccountCopy.SignOut -> "Đăng xuất"
    AccountCopy.ConfirmSignOut -> "Đăng xuất trên thiết bị này?"
    AccountCopy.ConfirmSignOutBody -> "Ứng dụng sẽ yêu cầu đăng xuất. Danh tính được ẩn trong lúc kiểm tra kết quả."
    AccountCopy.ConfirmSignOutAction -> "Xác nhận đăng xuất"
    AccountCopy.KeepSignedIn -> "Giữ đăng nhập"
    AccountCopy.LocalTitle -> "Khám phá không cần tài khoản"
    AccountCopy.LocalBody -> "Bạn luôn có thể xem thư viện. Chơi local không cần tài khoản khi bản dựng có trò chơi native khả dụng."
    AccountCopy.Library -> "Xem thư viện trò chơi"
    AccountCopy.Preferences -> "Giao diện và ngôn ngữ theo thiết bị. Tùy chọn tài khoản chưa được kết nối trong bản dựng này."
    AccountCopy.Avatar -> "Ảnh hồ sơ"
    AccountCopy.NeutralAvatar -> "Ảnh hồ sơ trung tính"
    AccountCopy.AuthAvailableLater -> "Khám phá hay chơi không tạo tài khoản local."
}
