-- Readiness parses all required columns while returning no authority data.
SELECT
 a.user_id,a.authorization_epoch,a.enabled,a.last_observed_at_ms,
 a.publication_lease_started_at_ms,a.publication_lease_until_ms,
 i.issuer,i.subject,i.user_id,
 s.id,s.user_id,s.authorization_epoch,s.channel,s.credential_generation,
 s.credential_digest,s.context_id,s.created_at_ms,s.last_activity_at_ms,
 s.last_observed_at_ms,s.idle_deadline_ms,s.absolute_deadline_ms,
 s.revoked_at_ms,s.expired_at_ms,
 ep.singleton,ep.enabled,ep.policy_epoch,ep.last_observed_at_ms,
 p.user_id,p.handle,p.display_name,p.visibility,p.revision,
 g.digest,g.operation_id,g.issuer,g.subject,g.policy_epoch,g.expected_account_epoch,
 g.created_at_ms,g.expires_at_ms,g.disposition,g.requested_handle,g.requested_display_name,
 pr.user_id,pr.operation_id,pr.expected_revision,pr.display_name,pr.visibility,pr.resulting_revision,
 f.request_id,f.sender_id,f.recipient_id,f.pair_low,f.pair_high,f.status,f.revision,
 f.created_at_ms,f.expires_at_ms,f.updated_at_ms,
 so.actor_id,so.operation_id,so.fingerprint,so.request_id,ls.user_id,ls.last_seen_ms,
 h.match_id,h.fence,h.format,h.version,h.input_index,h.observed_ms,h.record_count,
 h.record_bytes,h.creation,h.creation_hash,h.ledger,h.ledger_hash,h.latest_hash,
 jr.match_id,jr.input_index,jr.state_version,jr.logical_ms,jr.state_hash,jr.payload,
 jr.payload_bytes,jr.payload_hash,jp.match_id,jp.fence,jp.started_at_ms,jp.until_ms,
 r.match_id,r.creator_user_id,r.code_digest,r.game_id,r.game_version,r.config,
 r.seats,r.created_at_ms,r.code_deadline_ms,r.started,r.completed,
 m.match_id,m.user_id,m.seat,m.generation,
 ad.match_id,ad.session_id,ad.user_id,ad.authorization_epoch,ad.seat,ad.generation,
 ja.session_id,ja.window_started_at_ms,ja.attempts,
 sg.session_id,sg.transaction_id,sg.user_id,sg.authorization_epoch,
 sg.credential_digest,sg.channel,sg.context_id,sg.deadline_ms,
 mg.match_id,mg.transaction_id,mg.session_id,mg.user_id,mg.authorization_epoch,mg.seat,mg.generation
FROM session_accounts a,session_provider_identities i,session_auth_sessions s,
 account_enrollment_policy ep,account_profiles p,account_enrollment_grants g,
 account_profile_receipts pr,tabula_friend_requests f,tabula_social_operations so,
 tabula_social_last_seen ls,match_journal_heads h,match_journal_records jr,
 match_journal_publications jp,online_match_rooms r,online_match_memberships m,
 online_match_admissions ad,online_match_join_attempts ja,
 online_session_commit_guards sg,online_match_commit_guards mg
WHERE FALSE
