//! Published perft positions: the independent move-generation oracle.

use tabula_game_chess::{perft, State};

fn assert_perft(fen: &str, depth: u8, expected: u64) {
    let position = State::from_fen(fen).expect("published FEN must parse");
    assert_eq!(
        perft(&position, depth),
        expected,
        "FEN {fen}, depth {depth}"
    );
}

#[test]
fn published_positions_match_through_practical_depths() {
    // https://www.chessprogramming.org/Perft_Results — values are independent
    // fixtures, not generated by this implementation.
    assert_perft(
        "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        4,
        197_281,
    );
    // Kiwipete: castling, pins, discovered checks, and tactical captures.
    assert_perft(
        "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1",
        3,
        97_862,
    );
    // En-passant checks and constrained king movement.
    assert_perft("8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1", 4, 43_238);
    // Promotions and both castling rights under attack.
    assert_perft(
        "r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq - 0 1",
        3,
        9_467,
    );
}

#[test]
#[ignore = "deep verification: run cargo test -p tabula-game-chess --test perft -- --ignored"]
fn initial_position_depth_five_matches_published_oracle() {
    assert_perft(
        "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        5,
        4_865_609,
    );
}
