#!/usr/bin/env python3
"""Bounded PNG exports of the supplied canonical Chess artwork (doc 04 §12).

Requires Inkscape and Pillow only while regenerating; the Rust runtime decodes
PNG and has no new SVG, image-authoring or Python dependency. Original sources
remain unchanged under source/. The original cover is never embedded in Rust.
"""
from argparse import ArgumentParser
from io import BytesIO
from pathlib import Path
import subprocess
import tempfile

from PIL import Image

ROOT = Path(__file__).resolve().parent
CELL, PAD, REGION, COLUMNS = 72, 4, 64, 6
PIECES = [
    (side + key, f"pieces/{color}-{kind}")
    for side, color in [("w", "white"), ("b", "black")]
    for key, kind in [("K", "king"), ("Q", "queen"), ("B", "bishop"),
                      ("N", "knight"), ("R", "rook"), ("P", "pawn")]
]


def png_bytes(image):
    output = BytesIO()
    image.save(output, "PNG", compress_level=9)
    return output.getvalue()


def piece_atlas(density):
    atlas = Image.new("RGBA", (CELL * COLUMNS * density, CELL * 2 * density))
    with tempfile.TemporaryDirectory(prefix="tabula-chess-") as directory:
        for index, (key, _) in enumerate(PIECES):
            output = Path(directory) / f"{key}.png"
            subprocess.run([
                "inkscape", str(ROOT / "source" / "pieces" / f"{key}.svg"),
                "--export-type=png", f"--export-filename={output}",
                f"--export-width={REGION * density}",
                f"--export-height={REGION * density}", "--export-background-opacity=0",
            ], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            with Image.open(output) as exported:
                image = exported.convert("RGBA")
                if image.size != (REGION * density, REGION * density):
                    raise ValueError(f"unexpected export size for {key}: {image.size}")
                # Paste straight-alpha RGBA, without another alpha mask. A mask
                # here would apply edge coverage twice and thin the contours.
                atlas.paste(image, ((index % COLUMNS * CELL + PAD) * density,
                                    (index // COLUMNS * CELL + PAD) * density))
    return png_bytes(atlas)


def cover(density):
    with Image.open(ROOT / "source" / "chess-atmosphere.png") as original:
        image = original.convert("RGB").resize((240 * density, 160 * density),
                                                Image.Resampling.LANCZOS)
        return png_bytes(image)


def manifest_source():
    lines = ["# Generated by generate.py from retained canonical source artwork."]
    for name, prefix, priority in [("pieces", "pieces", "critical"),
                                    ("cover", "cover", "high")]:
        for density in [1, 2]:
            lines += ["", "[[files]]", f'name = "{name}@{density}x.atlas"',
                      f'source = "{prefix}@{density}x.png"',
                      f'priority = "{priority}"', f'density = {density}']
    for index, (_, resource) in enumerate(PIECES):
        lines += ["", "[[resources]]", f'id = "{resource}"']
        for density in [1, 2]:
            x = (index % COLUMNS * CELL + PAD) * density
            y = (index // COLUMNS * CELL + PAD) * density
            lines += ["", "[[resources.variants]]", f'file = "pieces@{density}x.atlas"',
                      f'region = {{ x = {x}, y = {y}, width = {REGION * density}, height = {REGION * density} }}']
    lines += ["", "[[resources]]", 'id = "catalog/cover"']
    for density in [1, 2]:
        lines += ["", "[[resources.variants]]", f'file = "cover@{density}x.atlas"']
    return "\n".join(lines) + "\n"


def main():
    parser = ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify exports without writing")
    args = parser.parse_args()
    exports = {"pack.source.toml": manifest_source().encode()}
    for density in [1, 2]:
        exports[f"pieces@{density}x.png"] = piece_atlas(density)
        exports[f"cover@{density}x.png"] = cover(density)
    for name, data in exports.items():
        if args.check:
            if not (ROOT / name).is_file() or (ROOT / name).read_bytes() != data:
                raise SystemExit(f"stale Chess artwork: {name}")
        else:
            (ROOT / name).write_bytes(data)
    print(f"{'Verified' if args.check else 'Wrote'} canonical Chess 1x/2x PNG exports and source manifest")


if __name__ == "__main__":
    main()
