// @generated by `cargo xtask gen-tokens` from tokens.toml; do not edit.
package com.loveoverflow.tabula.mobile.design

import androidx.compose.ui.graphics.Color

/** The authored schemes of `tokens.toml`, in authored order. */
enum class TabulaScheme { Light, Dark, HcLight, HcDark }

/** Semantic colour roles of one scheme (`[schemes.*]`). */
class TabulaColors(
    val surface: Color,
    val container: Color,
    val containerHigh: Color,
    val onSurface: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val primary: Color,
    val onPrimary: Color,
    val success: Color,
    val onSuccess: Color,
    val danger: Color,
    val onDanger: Color,
    val turnActive: Color,
    val turnWaiting: Color,
    val legalTarget: Color,
    val illegalTarget: Color,
    val selected: Color,
    val lastAction: Color,
    val threat: Color,
    val hidden: Color,
    val shellCanvas: Color,
    val shellPaper: Color,
    val shellHero: Color,
    val shellOnHero: Color,
    val shellNote: Color,
    val shellCoverSage: Color,
    val shellCoverMint: Color,
    val shellArtFieldLight: Color,
    val shellArtFieldDark: Color,
    val shellArtLine: Color,
    val shellArtPieceLight: Color,
    val shellArtPieceDark: Color,
    val shellArtRoad: Color,
    val shellArtEarth: Color,
    val team: List<Color>,
    val seatMarker: List<Color>,
)

/** Resolved colours for every authored scheme. */
object TabulaSchemes {
    val light = TabulaColors(
        surface = Color(0xFFFFFBFF),
        container = Color(0xFFF4EDF7),
        containerHigh = Color(0xFFEAE3ED),
        onSurface = Color(0xFF1E1C21),
        onSurfaceVariant = Color(0xFF4B4650),
        outline = Color(0xFF79747E),
        primary = Color(0xFF5634BE),
        onPrimary = Color(0xFFFFFFFF),
        success = Color(0xFF106F3D),
        onSuccess = Color(0xFFFFFFFF),
        danger = Color(0xFFBA1A1A),
        onDanger = Color(0xFFFFFFFF),
        turnActive = Color(0xFF006341),
        turnWaiting = Color(0xFF5E5868),
        legalTarget = Color(0xFF007044),
        illegalTarget = Color(0xFFBA1A1A),
        selected = Color(0xFF5634BE),
        lastAction = Color(0xFFB07000),
        threat = Color(0xFFBA1A1A),
        hidden = Color(0xFF4C4E58),
        shellCanvas = Color(0xFFF9F7F4),
        shellPaper = Color(0xFFFFFFFF),
        shellHero = Color(0xFFE9E0F7),
        shellOnHero = Color(0xFF342C45),
        shellNote = Color(0xFFF1EEE8),
        shellCoverSage = Color(0xFFDFE7D9),
        shellCoverMint = Color(0xFFD9E8DC),
        shellArtFieldLight = Color(0xFFECEDDB),
        shellArtFieldDark = Color(0xFFAABB9C),
        shellArtLine = Color(0xFF7E9072),
        shellArtPieceLight = Color(0xFFFFFFF1),
        shellArtPieceDark = Color(0xFF30343D),
        shellArtRoad = Color(0xFFF8ECD1),
        shellArtEarth = Color(0xFFC79872),
        team = listOf(Color(0xFF005F73), Color(0xFFCA6702), Color(0xFF6D597A), Color(0xFF127D66), Color(0xFFB64664), Color(0xFF385F91), Color(0xFF79521E), Color(0xFF5E587E)),
        seatMarker = listOf(Color(0xFF005F73), Color(0xFFCA6702), Color(0xFF6D597A), Color(0xFF127D66), Color(0xFFB64664), Color(0xFF385F91), Color(0xFF79521E), Color(0xFF5E587E)),
    )
    val dark = TabulaColors(
        surface = Color(0xFF141217),
        container = Color(0xFF1E1C21),
        containerHigh = Color(0xFF2B282F),
        onSurface = Color(0xFFE7E1E5),
        onSurfaceVariant = Color(0xFFCAC3CE),
        outline = Color(0xFF938F99),
        primary = Color(0xFFCFBCFF),
        onPrimary = Color(0xFF32007E),
        success = Color(0xFF74F8A6),
        onSuccess = Color(0xFF00391A),
        danger = Color(0xFFFFB4AB),
        onDanger = Color(0xFF690005),
        turnActive = Color(0xFF73E2A3),
        turnWaiting = Color(0xFFCAC3CE),
        legalTarget = Color(0xFF74F8A6),
        illegalTarget = Color(0xFFFFB4AB),
        selected = Color(0xFFCFBCFF),
        lastAction = Color(0xFFFFDDB1),
        threat = Color(0xFFFFB4AB),
        hidden = Color(0xFFC8C6D0),
        shellCanvas = Color(0xFF17161A),
        shellPaper = Color(0xFF222126),
        shellHero = Color(0xFF3B304A),
        shellOnHero = Color(0xFFEEE9F1),
        shellNote = Color(0xFF2D2B30),
        shellCoverSage = Color(0xFF344333),
        shellCoverMint = Color(0xFF2D443C),
        shellArtFieldLight = Color(0xFFECEDDB),
        shellArtFieldDark = Color(0xFFAABB9C),
        shellArtLine = Color(0xFF7E9072),
        shellArtPieceLight = Color(0xFFFFFFF1),
        shellArtPieceDark = Color(0xFF30343D),
        shellArtRoad = Color(0xFFF8ECD1),
        shellArtEarth = Color(0xFFC79872),
        team = listOf(Color(0xFF66D9EF), Color(0xFFFFB86C), Color(0xFFD6A5E8), Color(0xFF74F8A6), Color(0xFFFF9DB8), Color(0xFF8AB4F8), Color(0xFFE8C48A), Color(0xFFB8B0FF)),
        seatMarker = listOf(Color(0xFF66D9EF), Color(0xFFFFB86C), Color(0xFFD6A5E8), Color(0xFF74F8A6), Color(0xFFFF9DB8), Color(0xFF8AB4F8), Color(0xFFE8C48A), Color(0xFFB8B0FF)),
    )
    val hcLight = TabulaColors(
        surface = Color(0xFFFFFFFF),
        container = Color(0xFFFFFFFF),
        containerHigh = Color(0xFFF5F5F5),
        onSurface = Color(0xFF000000),
        onSurfaceVariant = Color(0xFF000000),
        outline = Color(0xFF000000),
        primary = Color(0xFF2C0078),
        onPrimary = Color(0xFFFFFFFF),
        success = Color(0xFF005A20),
        onSuccess = Color(0xFFFFFFFF),
        danger = Color(0xFF910000),
        onDanger = Color(0xFFFFFFFF),
        turnActive = Color(0xFF005A20),
        turnWaiting = Color(0xFF000000),
        legalTarget = Color(0xFF005A20),
        illegalTarget = Color(0xFF910000),
        selected = Color(0xFF2C0078),
        lastAction = Color(0xFF6B4700),
        threat = Color(0xFF910000),
        hidden = Color(0xFF333333),
        shellCanvas = Color(0xFFFFFFFF),
        shellPaper = Color(0xFFFFFFFF),
        shellHero = Color(0xFFFFFFFF),
        shellOnHero = Color(0xFF000000),
        shellNote = Color(0xFFF5F5F5),
        shellCoverSage = Color(0xFFFFFFFF),
        shellCoverMint = Color(0xFFFFFFFF),
        shellArtFieldLight = Color(0xFFFFFFFF),
        shellArtFieldDark = Color(0xFFCACACA),
        shellArtLine = Color(0xFF000000),
        shellArtPieceLight = Color(0xFFFFFFFF),
        shellArtPieceDark = Color(0xFF000000),
        shellArtRoad = Color(0xFFFFFFFF),
        shellArtEarth = Color(0xFF79747E),
        team = listOf(Color(0xFF004B5C), Color(0xFF984D00), Color(0xFF4B3158), Color(0xFF005A20), Color(0xFF8F153C), Color(0xFF003D7A), Color(0xFF5E3E00), Color(0xFF42306D)),
        seatMarker = listOf(Color(0xFF004B5C), Color(0xFF984D00), Color(0xFF4B3158), Color(0xFF005A20), Color(0xFF8F153C), Color(0xFF003D7A), Color(0xFF5E3E00), Color(0xFF42306D)),
    )
    val hcDark = TabulaColors(
        surface = Color(0xFF000000),
        container = Color(0xFF000000),
        containerHigh = Color(0xFF1C1C1C),
        onSurface = Color(0xFFFFFFFF),
        onSurfaceVariant = Color(0xFFFFFFFF),
        outline = Color(0xFFFFFFFF),
        primary = Color(0xFFE0D3FF),
        onPrimary = Color(0xFF190050),
        success = Color(0xFF86FFA9),
        onSuccess = Color(0xFF00391A),
        danger = Color(0xFFFFDAD6),
        onDanger = Color(0xFF690005),
        turnActive = Color(0xFF86FFA9),
        turnWaiting = Color(0xFFFFFFFF),
        legalTarget = Color(0xFF86FFA9),
        illegalTarget = Color(0xFFFFDAD6),
        selected = Color(0xFFE0D3FF),
        lastAction = Color(0xFFFFE0A6),
        threat = Color(0xFFFFDAD6),
        hidden = Color(0xFFD0CCD5),
        shellCanvas = Color(0xFF000000),
        shellPaper = Color(0xFF000000),
        shellHero = Color(0xFF1C1C1C),
        shellOnHero = Color(0xFFFFFFFF),
        shellNote = Color(0xFF1C1C1C),
        shellCoverSage = Color(0xFF1C1C1C),
        shellCoverMint = Color(0xFF1C1C1C),
        shellArtFieldLight = Color(0xFFFFFFFF),
        shellArtFieldDark = Color(0xFF79747E),
        shellArtLine = Color(0xFFFFFFFF),
        shellArtPieceLight = Color(0xFFFFFFFF),
        shellArtPieceDark = Color(0xFF000000),
        shellArtRoad = Color(0xFFFFFFFF),
        shellArtEarth = Color(0xFF79747E),
        team = listOf(Color(0xFF7DEBFF), Color(0xFFFFD39B), Color(0xFFEFC8FF), Color(0xFF86FFA9), Color(0xFFFFB0C7), Color(0xFFB4C5FF), Color(0xFFFFE0A6), Color(0xFFD7C8FF)),
        seatMarker = listOf(Color(0xFF7DEBFF), Color(0xFFFFD39B), Color(0xFFEFC8FF), Color(0xFF86FFA9), Color(0xFFFFB0C7), Color(0xFFB4C5FF), Color(0xFFFFE0A6), Color(0xFFD7C8FF)),
    )

    fun of(scheme: TabulaScheme): TabulaColors = when (scheme) {
        TabulaScheme.Light -> light
        TabulaScheme.Dark -> dark
        TabulaScheme.HcLight -> hcLight
        TabulaScheme.HcDark -> hcDark
    }
}

/** Spacing in dp (`[sys.space]`). */
object TabulaSpace {
    const val none: Float = 0f
    const val xxs: Float = 2f
    const val xs: Float = 4f
    const val sm: Float = 8f
    const val md: Float = 12f
    const val lg: Float = 16f
    const val xl: Float = 20f
    const val xxl: Float = 24f
    const val xxxl: Float = 32f
    const val xxxxl: Float = 40f
    const val xxxxxl: Float = 48f
    const val xxxxxxl: Float = 64f
}

/** Corner radii in dp (`[sys.shape]`); `full` is the capsule convention. */
object TabulaShape {
    const val none: Float = 0.0f
    const val xs: Float = 4.0f
    const val sm: Float = 8.0f
    const val md: Float = 12.0f
    const val lg: Float = 16.0f
    const val xl: Float = 24.0f
    const val full: Float = 9999.0f
    const val card: Float = 16.0f
    const val board: Float = 12.0f
    const val token: Float = 9999.0f
    const val sheet: Float = 24.0f
    const val button: Float = 14.0f
    const val chip: Float = 8.0f
}

/** Font-family role; the platform maps a role to a typeface (`[sys.type.family]`). */
enum class TabulaFontRole { Display, Text, Mono }

/** One text style in dp/sp-equivalent logical units (`[sys.type.*]`). */
class TabulaTextStyle(
    val role: TabulaFontRole,
    val size: Float,
    val lineHeight: Float,
    val weight: Int,
    val letterSpacing: Float,
)

object TabulaType {
    val displayLg = TabulaTextStyle(TabulaFontRole.Display, 57.0f, 64.0f, 700, -0.5f)
    val displayMd = TabulaTextStyle(TabulaFontRole.Display, 45.0f, 52.0f, 700, -0.25f)
    val displaySm = TabulaTextStyle(TabulaFontRole.Display, 36.0f, 44.0f, 700, 0.0f)
    val headlineLg = TabulaTextStyle(TabulaFontRole.Text, 32.0f, 40.0f, 700, 0.0f)
    val headlineMd = TabulaTextStyle(TabulaFontRole.Text, 28.0f, 36.0f, 700, 0.0f)
    val headlineSm = TabulaTextStyle(TabulaFontRole.Text, 24.0f, 32.0f, 700, 0.0f)
    val titleLg = TabulaTextStyle(TabulaFontRole.Text, 22.0f, 28.0f, 700, 0.0f)
    val titleMd = TabulaTextStyle(TabulaFontRole.Text, 16.0f, 24.0f, 700, 0.15f)
    val titleSm = TabulaTextStyle(TabulaFontRole.Text, 14.0f, 20.0f, 700, 0.1f)
    val bodyLg = TabulaTextStyle(TabulaFontRole.Text, 16.0f, 24.0f, 400, 0.5f)
    val bodyMd = TabulaTextStyle(TabulaFontRole.Text, 14.0f, 20.0f, 400, 0.25f)
    val bodySm = TabulaTextStyle(TabulaFontRole.Text, 12.0f, 16.0f, 400, 0.4f)
    val labelLg = TabulaTextStyle(TabulaFontRole.Text, 14.0f, 20.0f, 700, 0.5f)
    val labelMd = TabulaTextStyle(TabulaFontRole.Text, 12.0f, 16.0f, 700, 0.5f)
    val labelSm = TabulaTextStyle(TabulaFontRole.Text, 11.0f, 16.0f, 700, 0.5f)
    val monoMd = TabulaTextStyle(TabulaFontRole.Mono, 16.0f, 20.0f, 600, 0.0f)
    val monoSm = TabulaTextStyle(TabulaFontRole.Mono, 12.0f, 16.0f, 600, 0.0f)
}

/** State-layer opacities (`[sys.state]`). */
object TabulaState {
    const val hover: Float = 0.08f
    const val focus: Float = 0.12f
    const val press: Float = 0.12f
    const val drag: Float = 0.16f
    const val disabledContent: Float = 0.38f
    const val disabledContainer: Float = 0.12f
}

/** Density and focus (`[sys.density]`, `[sys.focus]`). */
object TabulaAccessibility {
    const val densityScale: Float = 1.0f
    const val minTarget: Float = 44.0f
    const val focusRingWidth: Float = 3.0f
    const val focusRingColorRole: String = "primary"
}
