pack = "chess"
version = "0.3.0"
game = "com.tabula.chess"

[[files]]
name = "cover@1x.atlas"
path = "chess/0.3.0/cover@1x.b3-8cc678cb546c246e3b64c1c280b654d5316b08e41454a52daecc4a477241a5fd.png"
hash = "8cc678cb546c246e3b64c1c280b654d5316b08e41454a52daecc4a477241a5fd"
bytes = 44320
priority = "high"
density = 1

[[files]]
name = "cover@2x.atlas"
path = "chess/0.3.0/cover@2x.b3-c6bb188094f6aa8364d5769833a7c60734063dc818eb136d07066efe0e1fff41.png"
hash = "c6bb188094f6aa8364d5769833a7c60734063dc818eb136d07066efe0e1fff41"
bytes = 168293
priority = "high"
density = 2

[[files]]
name = "pieces@1x.atlas"
path = "chess/0.3.0/pieces@1x.b3-4c278a7bea9e13d861e4e0a27785682e7caa56b7e564b23f9b09f94ab69918ec.png"
hash = "4c278a7bea9e13d861e4e0a27785682e7caa56b7e564b23f9b09f94ab69918ec"
bytes = 28782
priority = "critical"
density = 1

[[files]]
name = "pieces@2x.atlas"
path = "chess/0.3.0/pieces@2x.b3-e32515f16e64c9e892b95c95a624f9187e11a463c649673cce2af2680ba3c34d.png"
hash = "e32515f16e64c9e892b95c95a624f9187e11a463c649673cce2af2680ba3c34d"
bytes = 61913
priority = "critical"
density = 2

[[files]]
name = "COPYRIGHT.txt"
path = "chess/0.3.0/source/pieces/COPYRIGHT.b3-ef27da6c4cb8eec8b32cd6c12ee705673d75b1ab2ea85ebf43bea4aa02c5e59b.txt"
hash = "ef27da6c4cb8eec8b32cd6c12ee705673d75b1ab2ea85ebf43bea4aa02c5e59b"
bytes = 30
priority = "low"

[[files]]
name = "LICENSE-Apache-2.0.txt"
path = "chess/0.3.0/source/pieces/LICENSE-Apache-2.0.b3-83cb3a2fcf829b6138e095b083016c34ddcdfa07b68d38782722c14fcf85ace6.txt"
hash = "83cb3a2fcf829b6138e095b083016c34ddcdfa07b68d38782722c14fcf85ace6"
bytes = 11358
priority = "low"

[[files]]
name = "NOTICE.txt"
path = "chess/0.3.0/source/pieces/NOTICE.b3-a686c7949818fcd503bebd14f8887576e71e688b1360737fd1b55ce40c1b2257.txt"
hash = "a686c7949818fcd503bebd14f8887576e71e688b1360737fd1b55ce40c1b2257"
bytes = 483
priority = "low"

[[files]]
name = "PIECE-PROVENANCE.md"
path = "chess/0.3.0/source/pieces/PIECE-PROVENANCE.b3-01ec0cc6d351bc8e5707c726f737e390b0cf7fc293806b151b7fc03a3a48e1ab.md"
hash = "01ec0cc6d351bc8e5707c726f737e390b0cf7fc293806b151b7fc03a3a48e1ab"
bytes = 2222
priority = "low"

[[resources]]
id = "catalog/cover"

[[resources.variants]]
file = "cover@1x.atlas"

[[resources.variants]]
file = "cover@2x.atlas"

[[resources]]
id = "pieces/black-bishop"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 148
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 296
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/black-king"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 4
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 8
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/black-knight"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 220
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 440
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/black-pawn"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 364
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 728
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/black-queen"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 76
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 152
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/black-rook"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 292
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 584
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/white-bishop"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 148
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 296
y = 8
width = 128
height = 128

[[resources]]
id = "pieces/white-king"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 4
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 8
y = 8
width = 128
height = 128

[[resources]]
id = "pieces/white-knight"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 220
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 440
y = 8
width = 128
height = 128

[[resources]]
id = "pieces/white-pawn"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 364
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 728
y = 8
width = 128
height = 128

[[resources]]
id = "pieces/white-queen"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 76
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 152
y = 8
width = 128
height = 128

[[resources]]
id = "pieces/white-rook"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 292
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 584
y = 8
width = 128
height = 128
