pack = "chess"
version = "0.1.0"
game = "com.tabula.chess"

[[files]]
name = "cover@1x.atlas"
path = "chess/0.1.0/cover@1x.b3-8cc678cb546c246e3b64c1c280b654d5316b08e41454a52daecc4a477241a5fd.png"
hash = "8cc678cb546c246e3b64c1c280b654d5316b08e41454a52daecc4a477241a5fd"
bytes = 44320
priority = "high"
density = 1

[[files]]
name = "cover@2x.atlas"
path = "chess/0.1.0/cover@2x.b3-c6bb188094f6aa8364d5769833a7c60734063dc818eb136d07066efe0e1fff41.png"
hash = "c6bb188094f6aa8364d5769833a7c60734063dc818eb136d07066efe0e1fff41"
bytes = 168293
priority = "high"
density = 2

[[files]]
name = "pieces@1x.atlas"
path = "chess/0.1.0/pieces@1x.b3-143639222e2604f324068497ed1538f23528af661ce87404449f2078ef0eb3bb.png"
hash = "143639222e2604f324068497ed1538f23528af661ce87404449f2078ef0eb3bb"
bytes = 21488
priority = "critical"
density = 1

[[files]]
name = "pieces@2x.atlas"
path = "chess/0.1.0/pieces@2x.b3-3d0bfafcdb1c6a5b4a932e036b2d3f5827e201f7646550216dfabd5fe2df5ac1.png"
hash = "3d0bfafcdb1c6a5b4a932e036b2d3f5827e201f7646550216dfabd5fe2df5ac1"
bytes = 46139
priority = "critical"
density = 2

[[resources]]
id = "catalog/cover"

[[resources.variants]]
file = "cover@1x.atlas"

[[resources.variants]]
file = "cover@2x.atlas"

[[resources]]
id = "pieces/black-bishop"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 148
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 296
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/black-king"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 4
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 8
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/black-knight"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 220
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 440
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/black-pawn"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 364
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 728
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/black-queen"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 76
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 152
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/black-rook"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 292
y = 76
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 584
y = 152
width = 128
height = 128

[[resources]]
id = "pieces/white-bishop"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 148
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 296
y = 8
width = 128
height = 128

[[resources]]
id = "pieces/white-king"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 4
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 8
y = 8
width = 128
height = 128

[[resources]]
id = "pieces/white-knight"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 220
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 440
y = 8
width = 128
height = 128

[[resources]]
id = "pieces/white-pawn"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 364
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 728
y = 8
width = 128
height = 128

[[resources]]
id = "pieces/white-queen"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 76
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 152
y = 8
width = 128
height = 128

[[resources]]
id = "pieces/white-rook"

[[resources.variants]]
file = "pieces@1x.atlas"

[resources.variants.region]
x = 292
y = 4
width = 64
height = 64

[[resources.variants]]
file = "pieces@2x.atlas"

[resources.variants.region]
x = 584
y = 8
width = 128
height = 128
