#!/usr/bin/env python3
"""Reproduce bounded original portrait crops and one opaque, role-neutral back.

Requires Pillow for authoring only. The live Vietnamese labels and rules are
Rust RenderList text, never part of a role-front raster. No publisher art enters
this pack. Full source atlas stays outside runtime include_bytes paths.
"""
from argparse import ArgumentParser
from io import BytesIO
from pathlib import Path
import hashlib
import json
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent
DOCS = ROOT.parents[2] / 'docs/ui/werewolf-approved'
ROLES = ['villager', 'werewolf', 'seer', 'doctor', 'hunter', 'witch']
SOURCE_HASH = '83455e8181f4e211feb9d13772e841cce2d3e169c7a7ed763e9bbdd222fae757'


def png(image):
    out = BytesIO()
    image.save(out, 'PNG', compress_level=9)
    return out.getvalue()


def back(density):
    # Re-authored from the approved moon/diamond convention, without baked text.
    scale = density * 3
    im = Image.new('RGB', (192*scale, 288*scale), '#231f36')
    d = ImageDraw.Draw(im)
    gold = '#d8bc78'
    for inset in [8, 13]:
        d.rounded_rectangle([inset*scale, inset*scale, (192-inset)*scale, (288-inset)*scale], radius=9*scale, outline=gold, width=scale)
    for sx in [0, 10]:
        d.polygon([(96*scale,(56+sx)*scale),((151-sx)*scale,145*scale),(96*scale,(234-sx)*scale),((41+sx)*scale,145*scale)], outline=gold, width=scale)
    d.ellipse([61*scale,107*scale,131*scale,177*scale], fill=gold)
    d.ellipse([76*scale,101*scale,135*scale,165*scale], fill='#231f36')
    for y in [85,206]:
        d.polygon([(96*scale,(y-7)*scale),(99*scale,(y-2)*scale),(104*scale,y*scale),(99*scale,(y+2)*scale),(96*scale,(y+7)*scale),(93*scale,(y+2)*scale),(88*scale,y*scale),(93*scale,(y-2)*scale)], fill=gold)
    return im.resize((192*density,288*density), Image.Resampling.LANCZOS)


def exports():
    source = (ROOT/'source/role-art-atlas.webp').read_bytes()
    if hashlib.sha256(source).hexdigest() != SOURCE_HASH:
        raise ValueError('retained approved art differs from provenance hash')
    atlas = Image.open(BytesIO(source)).convert('RGB')
    if atlas.size != (1536,1024):
        raise ValueError('unexpected source atlas dimensions')
    result = {}
    lines = ['# Generated by generate.py; independent role files, no runtime all-role atlas.']
    for name in ROLES + ['back', 'village-night', 'village-dawn']:
        for density in [1,2]:
            if name.startswith('village-'):
                image = Image.open(ROOT/'source'/f'{name}.png').convert('RGB').resize((640*density,360*density),Image.Resampling.LANCZOS)
                image = image.quantize(colors=256,method=Image.Quantize.MEDIANCUT,dither=Image.Dither.FLOYDSTEINBERG)
            elif name == 'back':
                image = back(density)
            else:
                i = ROLES.index(name)
                image = atlas.crop(((i%3)*512,(i//3)*512,(i%3+1)*512,(i//3+1)*512))
                image = image.resize((256*density,256*density),Image.Resampling.LANCZOS)
                # Stable palette reduces downloads while retaining all source detail.
                image = image.quantize(colors=256, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.FLOYDSTEINBERG)
            result[f'{name}@{density}x.png'] = png(image)
            lines += ['', '[[files]]', f'name = "{name}@{density}x.image"', f'source = "{name}@{density}x.png"', 'priority = "critical"',f'density = {density}']
    for name in ROLES + ['back', 'village-night', 'village-dawn']:
        lines += ['', '[[resources]]', f'id = "{"scenes" if name.startswith("village-") else "cards"}/{name}"']
        for density in [1,2]:
            lines += ['', '[[resources.variants]]', f'file = "{name}@{density}x.image"']
    result['pack.source.toml'] = ('\n'.join(lines)+'\n').encode()
    stats = []
    for name,data in result.items():
        if name.endswith('.png'):
            image = Image.open(BytesIO(data))
            stats.append({'file':name,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest(),'width':image.width,'height':image.height,'decoded_rgba8_bytes':image.width*image.height*4})
    result['budgets.json'] = (json.dumps({'encoded_bytes':sum(s['bytes'] for s in stats),'all_variants_rgba8_bytes':sum(s['decoded_rgba8_bytes'] for s in stats),'assets':stats},indent=2)+'\n').encode()
    return result


def main():
    parser = ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args = parser.parse_args()
    for name,data in exports().items():
        destination = DOCS / name if name == 'budgets.json' else ROOT / name
        if args.check:
            if not destination.is_file() or destination.read_bytes()!=data:
                raise SystemExit(f'stale Werewolf artwork: {name}')
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(data)
    print(('Verified' if args.check else 'Wrote')+' reproducible Werewolf portraits/back, metadata and budgets')

if __name__ == '__main__':
    main()
