//! Original UNBALANCED D01 starting content. Not executable gameplay.
//! Authoritative numeric source for docs/games/age-war/CONTENT.md.
//! Every literal bypass is private to this crate and covered by catalog tests.

use crate::schema::{
    Activation, Age, AgeAdvanceSpec, AttackSpec, BasisPoints, Contact, CueKeys, DamageKind,
    DispelTag, DroneSpec, ExpiryPolicy, GuardPacketFilter, Id, Immunity, InterruptPolicy,
    Mitigation, PresentationHint, RefreshPolicy, SkillBinding, SkillCard, SkillCost, SkillEffect,
    SkillFamily, SpellSlot, SpellSpec, StackPolicy, TargetFilter, TargetPriority, TargetSide,
    TechKind, TechSpec, Ticks, Trigger, TurretBranch, TurretSpec, UnitRole, UnitSpec, Q,
};

const fn id(value: &'static str) -> Id<'static> {
    Id::catalog_literal(value)
}
const fn ticks(value: u16) -> Ticks {
    Ticks::catalog_literal(value)
}
const fn q(value: u32) -> Q {
    Q::catalog_literal(value)
}
const fn bp(value: u16) -> BasisPoints {
    BasisPoints::catalog_literal(value)
}
const fn armor(value: u16) -> Mitigation {
    Mitigation::catalog_literal(value)
}

/// D01 descriptor revision. This is not a gameplay/replay `RulesVersion`.
pub const DESIGN_VERSION: u16 = 1;
/// Explicitly unbalanced original starting content, not copied published stats.
pub const UNBALANCED: bool = true;
/// Maximum cumulative healing granted during one regular unit's lifetime.
pub const LIFETIME_HEAL_CAP_BP: BasisPoints = bp(3_500);
/// Maximum cumulative shielding granted during one regular unit's lifetime.
pub const LIFETIME_SHIELD_CAP_BP: BasisPoints = bp(5_000);
/// Bounded summon inventory per owner; pending and living drones count.
pub const DRONES_PER_OWNER_CAP: u8 = 4;
/// Bounded summon inventory across both owners.
pub const DRONES_PER_MATCH_CAP: u8 = 8;
/// Normal attacks and skill projectiles expire at this absolute flight age.
pub const PROJECTILE_LIFETIME_CAP: Ticks = ticks(120);
/// Every root/knockback contact grants this no-refresh immunity window.
pub const CONTROL_IMMUNITY: Ticks = ticks(40);
/// At most this many simultaneous status instances per entity.
pub const STATUSES_PER_ENTITY_CAP: u8 = 16;
/// At most this many live skill/attack projectiles per match (reject before commit).
pub const PROJECTILES_PER_MATCH_CAP: u16 = 128;

/// Two exact attack-only models referenced by summon cards, not normal recruits.
pub const DRONES: [DroneSpec; 2] = [
    DroneSpec {
        id: id("reed_drone"),
        design_version: 1,
        hp: 50,
        population: 1,
        armor_bp: [armor(0), armor(0), armor(0)],
        move_q_per_tick: q(130),
        half_width_q: q(160),
        attack: AttackSpec {
            damage: 10,
            kind: DamageKind::Physical,
            windup: ticks(6),
            recovery: ticks(24),
            reach_q: q(750),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
    },
    DroneSpec {
        id: id("relay_drone"),
        design_version: 1,
        hp: 60,
        population: 1,
        armor_bp: [armor(0), armor(0), armor(0)],
        move_q_per_tick: q(130),
        half_width_q: q(160),
        attack: AttackSpec {
            damage: 12,
            kind: DamageKind::Physical,
            windup: ticks(6),
            recovery: ticks(22),
            reach_q: q(750),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
    },
];

/// Sixteen exact reusable family cards; unit and turret bindings resolve here.
pub const SKILLS: [SkillCard; 16] = [
    SkillCard {
        id: id("guard"),
        design_version: 1,
        family: SkillFamily::Guard,
        activation: Activation::AutoCooldown,
        trigger: Trigger::Always,
        target_side: TargetSide::SelfOnly,
        target_filter: TargetFilter::SelfOnly,
        priority: TargetPriority::SelfOnly,
        cost: SkillCost::Free,
        range_q: q(0),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(2),
        contact: Contact::Instant,
        recovery: ticks(4),
        cooldown: ticks(120),
        duration: ticks(40),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ChargesSpentOrTimeout,
        dispel: DispelTag::Positive,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Guard { mitigation_bp: armor(1_500), outgoing_penalty_bp: bp(2_000), hit_charges: 2, packet_filter: GuardPacketFilter::DirectPhysicalAndArcane },
        cues: CueKeys { activate: id("age_war.guard.activate"), contact: id("age_war.guard.contact"), expire: id("age_war.guard.expire"), audio: id("age_war.guard.audio") },
        power_budget_points: 35,
        counterplay_vi: "Dùng DoT/Siege, tiêu hai charge bằng packet đủ lớn hoặc đợi hết40tick trước khi dồn damage.",
        oracle_vi: "Trong40tick, guard giảm15% cho hai packet direct physical/arcane lớn nhất mỗi tick; tiêu thụ một charge/packet. Action multiplier8000bp khi active; không guard DoT/Siege.",
    },
    SkillCard {
        id: id("pierce"),
        design_version: 1,
        family: SkillFamily::Pierce,
        activation: Activation::OnAttackContact,
        trigger: Trigger::AttackContact,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::UnitsAndStructures,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Free,
        range_q: q(24_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(0),
        contact: Contact::Instant,
        recovery: ticks(0),
        cooldown: ticks(0),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Pierce { damage: 0, pierce_bp: bp(1_800) },
        cues: CueKeys { activate: id("age_war.pierce.activate"), contact: id("age_war.pierce.contact"), expire: id("age_war.pierce.expire"), audio: id("age_war.pierce.audio") },
        power_budget_points: 30,
        counterplay_vi: "Đổi sang HP hoặc giáp arcane; nhiều quân rẻ khiến xuyên giáp mất lợi thế.",
        oracle_vi: "Mitigation1000bp còn820bp (=floor1000×0.82); damage=0 sửa hit cơ bản, không sinh hit thêm.",
    },
    SkillCard {
        id: id("shred"),
        design_version: 1,
        family: SkillFamily::Shred,
        activation: Activation::OnAttackContact,
        trigger: Trigger::AttackContact,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Free,
        range_q: q(24_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(0),
        contact: Contact::Instant,
        recovery: ticks(0),
        cooldown: ticks(0),
        duration: ticks(80),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::ExtendExpiry,
        expiry: ExpiryPolicy::Timeout,
        dispel: DispelTag::Negative,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Shred { mitigation_loss_bp: armor(750) },
        cues: CueKeys { activate: id("age_war.shred.activate"), contact: id("age_war.shred.contact"), expire: id("age_war.shred.expire"), audio: id("age_war.shred.audio") },
        power_budget_points: 35,
        counterplay_vi: "Cleanse debuff hoặc diệt nguồn; nhiều nguồn shred không cộng magnitude.",
        oracle_vi: "Bốn hit chỉ giữ strongest750bp; refresh lấy expiry muộn hơn, không cộng thành3000bp.",
    },
    SkillCard {
        id: id("charge"),
        design_version: 1,
        family: SkillFamily::Charge,
        activation: Activation::AutoCooldown,
        trigger: Trigger::UninterruptedRun,
        target_side: TargetSide::SelfOnly,
        target_filter: TargetFilter::SelfOnly,
        priority: TargetPriority::SelfOnly,
        cost: SkillCost::Free,
        range_q: q(0),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(0),
        contact: Contact::Instant,
        recovery: ticks(0),
        cooldown: ticks(160),
        duration: ticks(80),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::NextAttackOrTimeout,
        dispel: DispelTag::Positive,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Charge { bonus_damage: 45, required_run_q: q(2_000) },
        cues: CueKeys { activate: id("age_war.charge.activate"), contact: id("age_war.charge.contact"), expire: id("age_war.charge.expire"), audio: id("age_war.charge.audio") },
        power_budget_points: 40,
        counterplay_vi: "Root/knockback cắt quãng chạy; chặn bằng quân rẻ để hấp thụ hit tăng cường.",
        oracle_vi: "1.999 q chưa đủ, 2.000 q đủ; một hit kế tiếp nhận +45 và tiêu thụ buff; hết 80 tick không hit thì mất.",
    },
    SkillCard {
        id: id("volley"),
        design_version: 1,
        family: SkillFamily::Volley,
        activation: Activation::AutoCooldown,
        trigger: Trigger::Always,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Free,
        range_q: q(7_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(6),
        contact: Contact::Projectile { speed_q_per_tick: q(900), lifetime: ticks(12) },
        recovery: ticks(12),
        cooldown: ticks(140),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Volley { damage: 18, kind: DamageKind::Physical, shots: 3, spacing: ticks(4) },
        cues: CueKeys { activate: id("age_war.volley.activate"), contact: id("age_war.volley.contact"), expire: id("age_war.volley.expire"), audio: id("age_war.volley.audio") },
        power_budget_points: 45,
        counterplay_vi: "Tấn công lúc nguồn đang windup; giáp physical giảm từng viên, không chỉ tổng burst.",
        oracle_vi: "Contact ba viên cách nhau 4 tick; mục tiêu chết thì viên đã khóa mất, không retarget.",
    },
    SkillCard {
        id: id("dot"),
        design_version: 1,
        family: SkillFamily::Dot,
        activation: Activation::OnAttackContact,
        trigger: Trigger::AttackContact,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Free,
        range_q: q(24_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(0),
        contact: Contact::Instant,
        recovery: ticks(0),
        cooldown: ticks(0),
        duration: ticks(81),
        stacking: StackPolicy::PerSourceStrongest { source_cap: 3 },
        refresh: RefreshPolicy::ExtendExpiryKeepPulse,
        expiry: ExpiryPolicy::Timeout,
        dispel: DispelTag::Negative,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Dot { damage: 8, kind: DamageKind::Arcane, pulses: 4, interval: ticks(20) },
        cues: CueKeys { activate: id("age_war.dot.activate"), contact: id("age_war.dot.contact"), expire: id("age_war.dot.expire"), audio: id("age_war.dot.audio") },
        power_budget_points: 30,
        counterplay_vi: "Dispel trước pulse tiếp theo; heal có hạn nên không thể kéo dài vô tận.",
        oracle_vi: "Không tick ngay tại contact; bốn pulse tại +20/+40/+60/+80, expiry81tick nên pulse80 hợp lệ; apply lại giữ next pulse, không sinh hit ngay.",
    },
    SkillCard {
        id: id("slow"),
        design_version: 1,
        family: SkillFamily::Slow,
        activation: Activation::AutoCooldown,
        trigger: Trigger::Always,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Free,
        range_q: q(7_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(4),
        contact: Contact::Instant,
        recovery: ticks(8),
        cooldown: ticks(120),
        duration: ticks(80),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::ExtendExpiry,
        expiry: ExpiryPolicy::Timeout,
        dispel: DispelTag::Negative,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Slow { reduction_bp: bp(3_000) },
        cues: CueKeys { activate: id("age_war.slow.activate"), contact: id("age_war.slow.contact"), expire: id("age_war.slow.expire"), audio: id("age_war.slow.audio") },
        power_budget_points: 35,
        counterplay_vi: "Dispel; slow yếu hơn không cộng thêm và không refresh hiệu lực mạnh.",
        oracle_vi: "Move 100 q/tick thành 70; hai slow 30% và 40% chỉ dùng 40%, không thành 70%.",
    },
    SkillCard {
        id: id("root"),
        design_version: 1,
        family: SkillFamily::Root,
        activation: Activation::AutoCooldown,
        trigger: Trigger::Always,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Free,
        range_q: q(7_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(4),
        contact: Contact::Instant,
        recovery: ticks(8),
        cooldown: ticks(180),
        duration: ticks(12),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::Timeout,
        dispel: DispelTag::Negative,
        immunity: Immunity::Control { after_ticks: ticks(40) },
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Root,
        cues: CueKeys { activate: id("age_war.root.activate"), contact: id("age_war.root.contact"), expire: id("age_war.root.expire"), audio: id("age_war.root.audio") },
        power_budget_points: 45,
        counterplay_vi: "Dispel hoặc dùng quân làm mồi; cửa sổ miễn control ngăn khóa vĩnh viễn.",
        oracle_vi: "Root 12 tick khóa move, không khóa attack; sau ending/cleanse có40tick miễn root/knockback; khi còn controlled, lần tiếp theo không extend.",
    },
    SkillCard {
        id: id("knockback"),
        design_version: 1,
        family: SkillFamily::Knockback,
        activation: Activation::AutoCooldown,
        trigger: Trigger::Always,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Free,
        range_q: q(7_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(4),
        contact: Contact::Instant,
        recovery: ticks(8),
        cooldown: ticks(180),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::Control { after_ticks: ticks(40) },
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Knockback { distance_q: q(1_000) },
        cues: CueKeys { activate: id("age_war.knockback.activate"), contact: id("age_war.knockback.contact"), expire: id("age_war.knockback.expire"), audio: id("age_war.knockback.audio") },
        power_budget_points: 40,
        counterplay_vi: "Quân tank làm tuyến đệm; structures miễn đẩy; control immunity chặn chuỗi đẩy.",
        oracle_vi: "Đẩy1000q ra xa nguồn, dừng ởbiên/ally footprint; không xuyên quân/damage; khi kết thúc nhận40tick immunity.",
    },
    SkillCard {
        id: id("heal"),
        design_version: 1,
        family: SkillFamily::Heal,
        activation: Activation::AutoCooldown,
        trigger: Trigger::MissingHp,
        target_side: TargetSide::Ally,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::LowestHpRatioThenNearestThenId,
        cost: SkillCost::Free,
        range_q: q(4_500),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(4),
        contact: Contact::Instant,
        recovery: ticks(8),
        cooldown: ticks(160),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Heal { hp: 45 },
        cues: CueKeys { activate: id("age_war.heal.activate"), contact: id("age_war.heal.contact"), expire: id("age_war.heal.expire"), audio: id("age_war.heal.audio") },
        power_budget_points: 35,
        counterplay_vi: "Dồn burst hoặc áp sát support; lifetime heal cap ngăn stall.",
        oracle_vi: "Chỉ regular ally còn sống, thấp HP ratio nhất (tie entity id); overheal không tích trữ; lifetime tổng heal <=35% maxHP.",
    },
    SkillCard {
        id: id("shield"),
        design_version: 1,
        family: SkillFamily::Shield,
        activation: Activation::AutoCooldown,
        trigger: Trigger::Always,
        target_side: TargetSide::Ally,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::ThreatThenHpRatioThenNearestThenId,
        cost: SkillCost::Free,
        range_q: q(4_500),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(4),
        contact: Contact::Instant,
        recovery: ticks(8),
        cooldown: ticks(180),
        duration: ticks(100),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::Timeout,
        dispel: DispelTag::Positive,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Shield { hp: 70 },
        cues: CueKeys { activate: id("age_war.shield.activate"), contact: id("age_war.shield.contact"), expire: id("age_war.shield.expire"), audio: id("age_war.shield.audio") },
        power_budget_points: 40,
        counterplay_vi: "Dùng burst vượt shield pool25% maxHP hoặc đợi100tick; lifetime grant không tự nạp lại.",
        oracle_vi: "Pool shield tức thời<=25% spawnmaxHP; strongest grant, lifetime tổng grant<=50%; overheal không đếm; hết100tick mất.",
    },
    SkillCard {
        id: id("dispel"),
        design_version: 1,
        family: SkillFamily::Dispel,
        activation: Activation::AutoCooldown,
        trigger: Trigger::HasDispellableStatus,
        target_side: TargetSide::Ally,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::HostileControlThenOldestThenId,
        cost: SkillCost::Free,
        range_q: q(4_500),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(4),
        contact: Contact::Instant,
        recovery: ticks(8),
        cooldown: ticks(180),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Dispel { remove_up_to: 1 },
        cues: CueKeys { activate: id("age_war.dispel.activate"), contact: id("age_war.dispel.contact"), expire: id("age_war.dispel.expire"), audio: id("age_war.dispel.audio") },
        power_budget_points: 35,
        counterplay_vi: "Dùng nhiều debuff khác family hoặc ép support dùng cleanse trước.",
        oracle_vi: "Bỏ một negative status theo root→slow→DoT/shred, rồi oldest application→status id→source id; không trả HP đã mất.",
    },
    SkillCard {
        id: id("chain"),
        design_version: 1,
        family: SkillFamily::Chain,
        activation: Activation::AutoCooldown,
        trigger: Trigger::Always,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Free,
        range_q: q(7_000),
        aoe_radius_q: q(0),
        max_targets: 3,
        windup: ticks(4),
        contact: Contact::Instant,
        recovery: ticks(8),
        cooldown: ticks(160),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Chain { damage: 42, kind: DamageKind::Arcane, jumps: 3, jump_range_q: q(1_600), retention_bp: bp(8_000) },
        cues: CueKeys { activate: id("age_war.chain.activate"), contact: id("age_war.chain.contact"), expire: id("age_war.chain.expire"), audio: id("age_war.chain.audio") },
        power_budget_points: 55,
        counterplay_vi: "Giãn đội hình hơn 1.600 q; từng entity chỉ bị một lần mỗi cast.",
        oracle_vi: "Ba hit trước giáp là 42/33/26 (floor riêng mỗi jump); chọn nearest chưa-hit rồi entity id.",
    },
    SkillCard {
        id: id("bombard"),
        design_version: 1,
        family: SkillFamily::Bombard,
        activation: Activation::AutoCooldown,
        trigger: Trigger::Always,
        target_side: TargetSide::Ground,
        target_filter: TargetFilter::GroundPoint,
        priority: TargetPriority::GroundPoint,
        cost: SkillCost::Free,
        range_q: q(8_000),
        aoe_radius_q: q(1_800),
        max_targets: 4,
        windup: ticks(10),
        contact: Contact::DelayedArea { delay: ticks(20) },
        recovery: ticks(16),
        cooldown: ticks(180),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Bombard { damage: 70, kind: DamageKind::Siege },
        cues: CueKeys { activate: id("age_war.bombard.activate"), contact: id("age_war.bombard.contact"), expire: id("age_war.bombard.expire"), audio: id("age_war.bombard.audio") },
        power_budget_points: 65,
        counterplay_vi: "Di chuyển khỏi điểm khóa trong 20 tick; minimum range của siege mở cửa áp sát.",
        oracle_vi: "Khóa ground tại cast; contact sau 20 tick, bán kính 1.800 q, tối đa 4 entity nearest tâm rồi entity id.",
    },
    SkillCard {
        id: id("summon"),
        design_version: 1,
        family: SkillFamily::Summon,
        activation: Activation::AutoCooldown,
        trigger: Trigger::Always,
        target_side: TargetSide::SelfOnly,
        target_filter: TargetFilter::SelfOnly,
        priority: TargetPriority::SelfOnly,
        cost: SkillCost::Free,
        range_q: q(0),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(10),
        contact: Contact::Instant,
        recovery: ticks(12),
        cooldown: ticks(300),
        duration: ticks(240),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::Timeout,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Summon { count: 2, drone: DRONES[0], lifetime: ticks(240) },
        cues: CueKeys { activate: id("age_war.summon.activate"), contact: id("age_war.summon.contact"), expire: id("age_war.summon.expire"), audio: id("age_war.summon.audio") },
        power_budget_points: 65,
        counterplay_vi: "AOE diệt drone; drone không nhận heal/shield, không XP/bounty.",
        oracle_vi: "Sinh tối đa hai drone trong khoảng trống; cap 4/owner, 8/match; TTL 240; đầy cap reject trước commit.",
    },
    SkillCard {
        id: id("burst_heat"),
        design_version: 1,
        family: SkillFamily::BurstHeat,
        activation: Activation::AutoCooldown,
        trigger: Trigger::HeatBudget,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Free,
        range_q: q(7_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(5),
        contact: Contact::Projectile { speed_q_per_tick: q(1_200), lifetime: ticks(10) },
        recovery: ticks(14),
        cooldown: ticks(30),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::BurstHeat { damage: 22, kind: DamageKind::Physical, shots: 3, spacing: ticks(3), heat_per_shot: 25, heat_limit: 100, decay_per_tick: 1 },
        cues: CueKeys { activate: id("age_war.burst_heat.activate"), contact: id("age_war.burst_heat.contact"), expire: id("age_war.burst_heat.expire"), audio: id("age_war.burst_heat.audio") },
        power_budget_points: 55,
        counterplay_vi: "Ép burst vào tank rồi phản công trong lúc nguồn đang xả nhiệt.",
        oracle_vi: "Precheck cần heat+75<=100; ghi 25/viên khi phóng; decay1/tick; không đổi target trong burst.",
    },
];

/// Six ages × six tactical roles; every statistic is original and UNBALANCED.
pub const UNITS: [UnitSpec; 36] = [
    UnitSpec {
        id: id("stone_keeper"),
        design_version: 1,
        age: Age::Primitive,
        name_vi: "Người giữ đá",
        role: UnitRole::Frontline,
        presentation_hint: PresentationHint::MasculineHuman,
        cost_gold: 35,
        population: 1,
        train: ticks(36),
        hp: 150,
        armor_bp: [armor(1_000), armor(0), armor(500)],
        move_q_per_tick: q(90),
        half_width_q: q(260),
        attack: AttackSpec {
            damage: 24,
            kind: DamageKind::Physical,
            windup: ticks(8),
            recovery: ticks(18),
            reach_q: q(850),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[SkillBinding {
            id: id("guard"),
            design_version: 1,
        }],
        counterplay_vi: "Mở đường bằng pierce; guard có khoảng trống.",
    },
    UnitSpec {
        id: id("reed_hunter"),
        design_version: 1,
        age: Age::Primitive,
        name_vi: "Nữ săn lau",
        role: UnitRole::Ranged,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 45,
        population: 1,
        train: ticks(42),
        hp: 90,
        armor_bp: [armor(0), armor(500), armor(0)],
        move_q_per_tick: q(100),
        half_width_q: q(200),
        attack: AttackSpec {
            damage: 20,
            kind: DamageKind::Physical,
            windup: ticks(10),
            recovery: ticks(22),
            reach_q: q(5_800),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(800),
        },
        skills: &[SkillBinding {
            id: id("pierce"),
            design_version: 1,
        }],
        counterplay_vi: "Áp sát; HP thấp và không AOE.",
    },
    UnitSpec {
        id: id("root_shield"),
        design_version: 1,
        age: Age::Primitive,
        name_vi: "Khiên rễ",
        role: UnitRole::Tank,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 65,
        population: 2,
        train: ticks(56),
        hp: 280,
        armor_bp: [armor(2_000), armor(500), armor(1_000)],
        move_q_per_tick: q(55),
        half_width_q: q(420),
        attack: AttackSpec {
            damage: 22,
            kind: DamageKind::Physical,
            windup: ticks(12),
            recovery: ticks(28),
            reach_q: q(800),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("guard"),
                design_version: 1,
            },
            SkillBinding {
                id: id("knockback"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Arcane và shred; đi chậm dễ chịu chênh tầm.",
    },
    UnitSpec {
        id: id("quick_track"),
        design_version: 1,
        age: Age::Primitive,
        name_vi: "Dấu chân nhanh",
        role: UnitRole::Skirmisher,
        presentation_hint: PresentationHint::MasculineHuman,
        cost_gold: 50,
        population: 1,
        train: ticks(40),
        hp: 105,
        armor_bp: [armor(500), armor(0), armor(0)],
        move_q_per_tick: q(145),
        half_width_q: q(190),
        attack: AttackSpec {
            damage: 18,
            kind: DamageKind::Physical,
            windup: ticks(6),
            recovery: ticks(16),
            reach_q: q(750),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("charge"),
                design_version: 1,
            },
            SkillBinding {
                id: id("dot"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Root cắt charge; giáp physical chống hit thường.",
    },
    UnitSpec {
        id: id("leaf_mender"),
        design_version: 1,
        age: Age::Primitive,
        name_vi: "Người vá lá",
        role: UnitRole::Support,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 55,
        population: 1,
        train: ticks(48),
        hp: 100,
        armor_bp: [armor(0), armor(1_000), armor(0)],
        move_q_per_tick: q(80),
        half_width_q: q(210),
        attack: AttackSpec {
            damage: 12,
            kind: DamageKind::Arcane,
            windup: ticks(8),
            recovery: ticks(26),
            reach_q: q(3_500),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(600),
        },
        skills: &[
            SkillBinding {
                id: id("heal"),
                design_version: 1,
            },
            SkillBinding {
                id: id("dispel"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Diệt support trước; heal chỉ35% lifetime.",
    },
    UnitSpec {
        id: id("rolling_stone_rig"),
        design_version: 1,
        age: Age::Primitive,
        name_vi: "Giàn đá cuộn",
        role: UnitRole::Siege,
        presentation_hint: PresentationHint::Construct,
        cost_gold: 85,
        population: 3,
        train: ticks(70),
        hp: 160,
        armor_bp: [armor(500), armor(0), armor(1_500)],
        move_q_per_tick: q(45),
        half_width_q: q(480),
        attack: AttackSpec {
            damage: 55,
            kind: DamageKind::Siege,
            windup: ticks(18),
            recovery: ticks(38),
            reach_q: q(7_000),
            min_reach_q: q(2_000),
            projectile_speed_q_per_tick: q(550),
        },
        skills: &[SkillBinding {
            id: id("bombard"),
            design_version: 1,
        }],
        counterplay_vi: "Áp sát dưới2000q; tránh điểm AOE đã khóa.",
    },
    UnitSpec {
        id: id("salt_guard"),
        design_version: 1,
        age: Age::Ancient,
        name_vi: "Vệ binh muối",
        role: UnitRole::Frontline,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 50,
        population: 1,
        train: ticks(40),
        hp: 180,
        armor_bp: [armor(1_500), armor(500), armor(500)],
        move_q_per_tick: q(95),
        half_width_q: q(260),
        attack: AttackSpec {
            damage: 28,
            kind: DamageKind::Physical,
            windup: ticks(8),
            recovery: ticks(18),
            reach_q: q(900),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[SkillBinding {
            id: id("shred"),
            design_version: 1,
        }],
        counterplay_vi: "Dispel stack; không để bốn contact liên tiếp.",
    },
    UnitSpec {
        id: id("sun_axle_archer"),
        design_version: 1,
        age: Age::Ancient,
        name_vi: "Xạ thủ mặt trời",
        role: UnitRole::Ranged,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 65,
        population: 1,
        train: ticks(48),
        hp: 110,
        armor_bp: [armor(500), armor(500), armor(0)],
        move_q_per_tick: q(95),
        half_width_q: q(210),
        attack: AttackSpec {
            damage: 24,
            kind: DamageKind::Physical,
            windup: ticks(10),
            recovery: ticks(22),
            reach_q: q(6_500),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(900),
        },
        skills: &[SkillBinding {
            id: id("volley"),
            design_version: 1,
        }],
        counterplay_vi: "Giáp physical hấp thụ từng viên volley.",
    },
    UnitSpec {
        id: id("silent_bronze"),
        design_version: 1,
        age: Age::Ancient,
        name_vi: "Khiên đồng lặng",
        role: UnitRole::Tank,
        presentation_hint: PresentationHint::MasculineHuman,
        cost_gold: 90,
        population: 2,
        train: ticks(62),
        hp: 350,
        armor_bp: [armor(2_500), armor(1_000), armor(1_500)],
        move_q_per_tick: q(52),
        half_width_q: q(440),
        attack: AttackSpec {
            damage: 26,
            kind: DamageKind::Physical,
            windup: ticks(12),
            recovery: ticks(30),
            reach_q: q(850),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("guard"),
                design_version: 1,
            },
            SkillBinding {
                id: id("shield"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Shred rồi tập trung hỏa lực; chờ shield hết100tick.",
    },
    UnitSpec {
        id: id("sand_rider"),
        design_version: 1,
        age: Age::Ancient,
        name_vi: "Kỵ nữ cát",
        role: UnitRole::Skirmisher,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 75,
        population: 2,
        train: ticks(48),
        hp: 155,
        armor_bp: [armor(1_000), armor(0), armor(500)],
        move_q_per_tick: q(160),
        half_width_q: q(240),
        attack: AttackSpec {
            damage: 26,
            kind: DamageKind::Physical,
            windup: ticks(7),
            recovery: ticks(18),
            reach_q: q(1_000),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("charge"),
                design_version: 1,
            },
            SkillBinding {
                id: id("pierce"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Root ngăn đường chạy; chống bằng HP thay armor.",
    },
    UnitSpec {
        id: id("banner_weaver"),
        design_version: 1,
        age: Age::Ancient,
        name_vi: "Người dệt cờ",
        role: UnitRole::Support,
        presentation_hint: PresentationHint::MasculineHuman,
        cost_gold: 80,
        population: 1,
        train: ticks(52),
        hp: 130,
        armor_bp: [armor(500), armor(1_500), armor(500)],
        move_q_per_tick: q(82),
        half_width_q: q(220),
        attack: AttackSpec {
            damage: 14,
            kind: DamageKind::Arcane,
            windup: ticks(8),
            recovery: ticks(28),
            reach_q: q(4_000),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(700),
        },
        skills: &[
            SkillBinding {
                id: id("heal"),
                design_version: 1,
            },
            SkillBinding {
                id: id("shield"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Burn hai lifetime budget rồi dồn burst.",
    },
    UnitSpec {
        id: id("spiral_ballista"),
        design_version: 1,
        age: Age::Ancient,
        name_vi: "Nỏ trục xoắn",
        role: UnitRole::Siege,
        presentation_hint: PresentationHint::Construct,
        cost_gold: 115,
        population: 3,
        train: ticks(76),
        hp: 210,
        armor_bp: [armor(1_000), armor(500), armor(1_500)],
        move_q_per_tick: q(42),
        half_width_q: q(480),
        attack: AttackSpec {
            damage: 72,
            kind: DamageKind::Physical,
            windup: ticks(20),
            recovery: ticks(40),
            reach_q: q(8_000),
            min_reach_q: q(2_400),
            projectile_speed_q_per_tick: q(1_100),
        },
        skills: &[
            SkillBinding {
                id: id("pierce"),
                design_version: 1,
            },
            SkillBinding {
                id: id("knockback"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Tấn công trong dead zone; knockback cóimmunity.",
    },
    UnitSpec {
        id: id("briar_blade"),
        design_version: 1,
        age: Age::Feudal,
        name_vi: "Kiếm sĩ vườn gai",
        role: UnitRole::Frontline,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 70,
        population: 1,
        train: ticks(44),
        hp: 220,
        armor_bp: [armor(2_000), armor(1_000), armor(1_000)],
        move_q_per_tick: q(100),
        half_width_q: q(260),
        attack: AttackSpec {
            damage: 34,
            kind: DamageKind::Physical,
            windup: ticks(8),
            recovery: ticks(18),
            reach_q: q(950),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[SkillBinding {
            id: id("root"),
            design_version: 1,
        }],
        counterplay_vi: "Root không khóa attack; tank vẫn đánh trong12tick.",
    },
    UnitSpec {
        id: id("mist_bow"),
        design_version: 1,
        age: Age::Feudal,
        name_vi: "Cung thủ sương",
        role: UnitRole::Ranged,
        presentation_hint: PresentationHint::MasculineHuman,
        cost_gold: 85,
        population: 1,
        train: ticks(50),
        hp: 135,
        armor_bp: [armor(500), armor(1_500), armor(500)],
        move_q_per_tick: q(105),
        half_width_q: q(210),
        attack: AttackSpec {
            damage: 28,
            kind: DamageKind::Physical,
            windup: ticks(10),
            recovery: ticks(22),
            reach_q: q(7_000),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_000),
        },
        skills: &[SkillBinding {
            id: id("slow"),
            design_version: 1,
        }],
        counterplay_vi: "Dispel slow rồi áp sát; chậm yếu khôngcộng.",
    },
    UnitSpec {
        id: id("iron_lotus"),
        design_version: 1,
        age: Age::Feudal,
        name_vi: "Khiên sen sắt",
        role: UnitRole::Tank,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 120,
        population: 2,
        train: ticks(66),
        hp: 420,
        armor_bp: [armor(3_000), armor(1_500), armor(2_000)],
        move_q_per_tick: q(50),
        half_width_q: q(460),
        attack: AttackSpec {
            damage: 30,
            kind: DamageKind::Physical,
            windup: ticks(13),
            recovery: ticks(31),
            reach_q: q(900),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("guard"),
                design_version: 1,
            },
            SkillBinding {
                id: id("shred"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Arcane và chênh tầm; shred cần giữ contact lâu.",
    },
    UnitSpec {
        id: id("red_wayfarer"),
        design_version: 1,
        age: Age::Feudal,
        name_vi: "Nữ lữ hành đỏ",
        role: UnitRole::Skirmisher,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 100,
        population: 2,
        train: ticks(50),
        hp: 185,
        armor_bp: [armor(1_500), armor(500), armor(500)],
        move_q_per_tick: q(165),
        half_width_q: q(240),
        attack: AttackSpec {
            damage: 28,
            kind: DamageKind::Physical,
            windup: ticks(7),
            recovery: ticks(18),
            reach_q: q(1_100),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("charge"),
                design_version: 1,
            },
            SkillBinding {
                id: id("volley"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Chặn đường chạy; volley dừng chuyển động.",
    },
    UnitSpec {
        id: id("bell_physician"),
        design_version: 1,
        age: Age::Feudal,
        name_vi: "Y sư chuông",
        role: UnitRole::Support,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 105,
        population: 1,
        train: ticks(54),
        hp: 160,
        armor_bp: [armor(1_000), armor(2_000), armor(1_000)],
        move_q_per_tick: q(85),
        half_width_q: q(220),
        attack: AttackSpec {
            damage: 16,
            kind: DamageKind::Arcane,
            windup: ticks(8),
            recovery: ticks(28),
            reach_q: q(4_200),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(750),
        },
        skills: &[
            SkillBinding {
                id: id("heal"),
                design_version: 1,
            },
            SkillBinding {
                id: id("dispel"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Đẩy support ra khỏi4500q; cleanse cooldown180.",
    },
    UnitSpec {
        id: id("flower_crossbow_rig"),
        design_version: 1,
        age: Age::Feudal,
        name_vi: "Giàn nỏ hoa",
        role: UnitRole::Siege,
        presentation_hint: PresentationHint::Construct,
        cost_gold: 150,
        population: 3,
        train: ticks(80),
        hp: 260,
        armor_bp: [armor(1_500), armor(1_000), armor(2_000)],
        move_q_per_tick: q(40),
        half_width_q: q(500),
        attack: AttackSpec {
            damage: 90,
            kind: DamageKind::Siege,
            windup: ticks(22),
            recovery: ticks(42),
            reach_q: q(8_500),
            min_reach_q: q(2_600),
            projectile_speed_q_per_tick: q(1_200),
        },
        skills: &[SkillBinding {
            id: id("bombard"),
            design_version: 1,
        }],
        counterplay_vi: "Charge vào minrange trước windup22tick.",
    },
    UnitSpec {
        id: id("quartz_warden"),
        design_version: 1,
        age: Age::Arcane,
        name_vi: "Hộ vệ thạch anh",
        role: UnitRole::Frontline,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 90,
        population: 1,
        train: ticks(46),
        hp: 235,
        armor_bp: [armor(1_500), armor(2_500), armor(1_000)],
        move_q_per_tick: q(102),
        half_width_q: q(270),
        attack: AttackSpec {
            damage: 30,
            kind: DamageKind::Arcane,
            windup: ticks(8),
            recovery: ticks(19),
            reach_q: q(1_050),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("shield"),
                design_version: 1,
            },
            SkillBinding {
                id: id("shred"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Physical damage; shred chỉ giảm mitigation, shield pool có hạn.",
    },
    UnitSpec {
        id: id("lightning_guide"),
        design_version: 1,
        age: Age::Arcane,
        name_vi: "Người dẫn chớp",
        role: UnitRole::Ranged,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 110,
        population: 1,
        train: ticks(52),
        hp: 145,
        armor_bp: [armor(1_000), armor(2_500), armor(500)],
        move_q_per_tick: q(100),
        half_width_q: q(210),
        attack: AttackSpec {
            damage: 32,
            kind: DamageKind::Arcane,
            windup: ticks(10),
            recovery: ticks(23),
            reach_q: q(7_200),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_100),
        },
        skills: &[SkillBinding {
            id: id("chain"),
            design_version: 1,
        }],
        counterplay_vi: "Giãn đội hình1600q; armor arcane mỗi jump.",
    },
    UnitSpec {
        id: id("rune_knight"),
        design_version: 1,
        age: Age::Arcane,
        name_vi: "Kỵ sĩ ký tự",
        role: UnitRole::Tank,
        presentation_hint: PresentationHint::MasculineHuman,
        cost_gold: 145,
        population: 2,
        train: ticks(68),
        hp: 450,
        armor_bp: [armor(2_500), armor(3_500), armor(2_000)],
        move_q_per_tick: q(48),
        half_width_q: q(460),
        attack: AttackSpec {
            damage: 32,
            kind: DamageKind::Arcane,
            windup: ticks(14),
            recovery: ticks(32),
            reach_q: q(950),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("guard"),
                design_version: 1,
            },
            SkillBinding {
                id: id("root"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Pierce rồi burst; root không bẫy structures.",
    },
    UnitSpec {
        id: id("shadow_dancer"),
        design_version: 1,
        age: Age::Arcane,
        name_vi: "Vũ công bóng",
        role: UnitRole::Skirmisher,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 125,
        population: 2,
        train: ticks(52),
        hp: 190,
        armor_bp: [armor(1_000), armor(2_000), armor(500)],
        move_q_per_tick: q(170),
        half_width_q: q(230),
        attack: AttackSpec {
            damage: 32,
            kind: DamageKind::Physical,
            windup: ticks(6),
            recovery: ticks(18),
            reach_q: q(1_100),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("slow"),
                design_version: 1,
            },
            SkillBinding {
                id: id("pierce"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Dispel slow; arcane burst đánh HP thấp.",
    },
    UnitSpec {
        id: id("curse_unbinder"),
        design_version: 1,
        age: Age::Arcane,
        name_vi: "Người gỡ nguyền",
        role: UnitRole::Support,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 135,
        population: 1,
        train: ticks(56),
        hp: 180,
        armor_bp: [armor(1_000), armor(3_000), armor(1_000)],
        move_q_per_tick: q(88),
        half_width_q: q(220),
        attack: AttackSpec {
            damage: 20,
            kind: DamageKind::Arcane,
            windup: ticks(8),
            recovery: ticks(28),
            reach_q: q(4_500),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(800),
        },
        skills: &[
            SkillBinding {
                id: id("dispel"),
                design_version: 1,
            },
            SkillBinding {
                id: id("heal"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Rải hai negative family vượt remove1 mỗi180tick.",
    },
    UnitSpec {
        id: id("cracked_prism"),
        design_version: 1,
        age: Age::Arcane,
        name_vi: "Lăng kính rạn",
        role: UnitRole::Siege,
        presentation_hint: PresentationHint::Construct,
        cost_gold: 185,
        population: 3,
        train: ticks(84),
        hp: 285,
        armor_bp: [armor(1_000), armor(3_000), armor(1_500)],
        move_q_per_tick: q(38),
        half_width_q: q(500),
        attack: AttackSpec {
            damage: 96,
            kind: DamageKind::Arcane,
            windup: ticks(24),
            recovery: ticks(44),
            reach_q: q(8_800),
            min_reach_q: q(2_800),
            projectile_speed_q_per_tick: q(1_300),
        },
        skills: &[
            SkillBinding {
                id: id("chain"),
                design_version: 1,
            },
            SkillBinding {
                id: id("bombard"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Giãn quân; đánh trong dead zone2800q.",
    },
    UnitSpec {
        id: id("wire_bodyguard"),
        design_version: 1,
        age: Age::Industrial,
        name_vi: "Vệ sĩ dây thép",
        role: UnitRole::Frontline,
        presentation_hint: PresentationHint::MasculineHuman,
        cost_gold: 105,
        population: 1,
        train: ticks(48),
        hp: 265,
        armor_bp: [armor(2_500), armor(1_500), armor(1_500)],
        move_q_per_tick: q(105),
        half_width_q: q(280),
        attack: AttackSpec {
            damage: 36,
            kind: DamageKind::Physical,
            windup: ticks(8),
            recovery: ticks(20),
            reach_q: q(1_100),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[SkillBinding {
            id: id("burst_heat"),
            design_version: 1,
        }],
        counterplay_vi: "Dùng tank hấp thụ burst rồi phản công khi heat cao.",
    },
    UnitSpec {
        id: id("wind_axle_shooter"),
        design_version: 1,
        age: Age::Industrial,
        name_vi: "Xạ thủ trục gió",
        role: UnitRole::Ranged,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 130,
        population: 1,
        train: ticks(54),
        hp: 165,
        armor_bp: [armor(1_500), armor(1_000), armor(1_000)],
        move_q_per_tick: q(100),
        half_width_q: q(220),
        attack: AttackSpec {
            damage: 38,
            kind: DamageKind::Physical,
            windup: ticks(11),
            recovery: ticks(23),
            reach_q: q(7_800),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_400),
        },
        skills: &[
            SkillBinding {
                id: id("pierce"),
                design_version: 1,
            },
            SkillBinding {
                id: id("volley"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Nhiều quân rẻ chia target, áp sát lúc volley.",
    },
    UnitSpec {
        id: id("coal_barrier"),
        design_version: 1,
        age: Age::Industrial,
        name_vi: "Xe chắn than",
        role: UnitRole::Tank,
        presentation_hint: PresentationHint::Construct,
        cost_gold: 170,
        population: 3,
        train: ticks(72),
        hp: 530,
        armor_bp: [armor(3_500), armor(1_500), armor(3_000)],
        move_q_per_tick: q(45),
        half_width_q: q(520),
        attack: AttackSpec {
            damage: 36,
            kind: DamageKind::Physical,
            windup: ticks(14),
            recovery: ticks(34),
            reach_q: q(1_100),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("guard"),
                design_version: 1,
            },
            SkillBinding {
                id: id("knockback"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Arcane; knockback không reset40tick immunity.",
    },
    UnitSpec {
        id: id("steam_scout"),
        design_version: 1,
        age: Age::Industrial,
        name_vi: "Nữ trinh sát hơi",
        role: UnitRole::Skirmisher,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 145,
        population: 2,
        train: ticks(54),
        hp: 215,
        armor_bp: [armor(2_000), armor(1_000), armor(1_000)],
        move_q_per_tick: q(175),
        half_width_q: q(250),
        attack: AttackSpec {
            damage: 34,
            kind: DamageKind::Physical,
            windup: ticks(7),
            recovery: ticks(18),
            reach_q: q(1_200),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("shred"),
                design_version: 1,
            },
            SkillBinding {
                id: id("charge"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Root chặn charge; cleanse shred trước burst.",
    },
    UnitSpec {
        id: id("coolant_engineer"),
        design_version: 1,
        age: Age::Industrial,
        name_vi: "Kỹ sư băng",
        role: UnitRole::Support,
        presentation_hint: PresentationHint::MasculineHuman,
        cost_gold: 150,
        population: 1,
        train: ticks(58),
        hp: 200,
        armor_bp: [armor(1_500), armor(2_000), armor(1_500)],
        move_q_per_tick: q(90),
        half_width_q: q(230),
        attack: AttackSpec {
            damage: 22,
            kind: DamageKind::Arcane,
            windup: ticks(9),
            recovery: ticks(29),
            reach_q: q(4_500),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(900),
        },
        skills: &[
            SkillBinding {
                id: id("shield"),
                design_version: 1,
            },
            SkillBinding {
                id: id("dispel"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Dồn burst vượt shield25%; shield budget cạn không nạp lại.",
    },
    UnitSpec {
        id: id("steel_flower_cannon"),
        design_version: 1,
        age: Age::Industrial,
        name_vi: "Pháo hoa thép",
        role: UnitRole::Siege,
        presentation_hint: PresentationHint::Construct,
        cost_gold: 220,
        population: 3,
        train: ticks(88),
        hp: 320,
        armor_bp: [armor(2_000), armor(1_000), armor(3_000)],
        move_q_per_tick: q(35),
        half_width_q: q(520),
        attack: AttackSpec {
            damage: 112,
            kind: DamageKind::Siege,
            windup: ticks(26),
            recovery: ticks(46),
            reach_q: q(9_300),
            min_reach_q: q(3_000),
            projectile_speed_q_per_tick: q(1_400),
        },
        skills: &[
            SkillBinding {
                id: id("bombard"),
                design_version: 1,
            },
            SkillBinding {
                id: id("dot"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Charge dưới3000q; dispel DOT không hoànhit.",
    },
    UnitSpec {
        id: id("orbit_keeper"),
        design_version: 1,
        age: Age::Future,
        name_vi: "Người giữ quỹ đạo",
        role: UnitRole::Frontline,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 125,
        population: 1,
        train: ticks(50),
        hp: 295,
        armor_bp: [armor(2_500), armor(2_500), armor(2_000)],
        move_q_per_tick: q(110),
        half_width_q: q(280),
        attack: AttackSpec {
            damage: 40,
            kind: DamageKind::Arcane,
            windup: ticks(8),
            recovery: ticks(20),
            reach_q: q(1_200),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("shield"),
                design_version: 1,
            },
            SkillBinding {
                id: id("guard"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Tiêu pool shield rồi dùng DoT/Siege vượt guard.",
    },
    UnitSpec {
        id: id("light_cutter"),
        design_version: 1,
        age: Age::Future,
        name_vi: "Xạ thủ ánh cắt",
        role: UnitRole::Ranged,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 155,
        population: 1,
        train: ticks(56),
        hp: 185,
        armor_bp: [armor(2_000), armor(2_000), armor(1_500)],
        move_q_per_tick: q(105),
        half_width_q: q(220),
        attack: AttackSpec {
            damage: 42,
            kind: DamageKind::Physical,
            windup: ticks(11),
            recovery: ticks(23),
            reach_q: q(8_200),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_700),
        },
        skills: &[
            SkillBinding {
                id: id("pierce"),
                design_version: 1,
            },
            SkillBinding {
                id: id("burst_heat"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Ép burst vào quân rẻ rồi áp sát lúc nguội nhiệt.",
    },
    UnitSpec {
        id: id("star_anchor"),
        design_version: 1,
        age: Age::Future,
        name_vi: "Khung neo sao",
        role: UnitRole::Tank,
        presentation_hint: PresentationHint::Construct,
        cost_gold: 200,
        population: 3,
        train: ticks(76),
        hp: 580,
        armor_bp: [armor(4_000), armor(3_000), armor(3_500)],
        move_q_per_tick: q(42),
        half_width_q: q(540),
        attack: AttackSpec {
            damage: 40,
            kind: DamageKind::Arcane,
            windup: ticks(15),
            recovery: ticks(35),
            reach_q: q(1_200),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("root"),
                design_version: 1,
            },
            SkillBinding {
                id: id("knockback"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Cửa sổcontrolimmunity; siege từngoài reach.",
    },
    UnitSpec {
        id: id("channel_runner"),
        design_version: 1,
        age: Age::Future,
        name_vi: "Người băng kênh",
        role: UnitRole::Skirmisher,
        presentation_hint: PresentationHint::MasculineHuman,
        cost_gold: 170,
        population: 2,
        train: ticks(56),
        hp: 235,
        armor_bp: [armor(2_500), armor(1_500), armor(1_500)],
        move_q_per_tick: q(185),
        half_width_q: q(250),
        attack: AttackSpec {
            damage: 38,
            kind: DamageKind::Physical,
            windup: ticks(7),
            recovery: ticks(18),
            reach_q: q(1_300),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(0),
        },
        skills: &[
            SkillBinding {
                id: id("charge"),
                design_version: 1,
            },
            SkillBinding {
                id: id("slow"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Root/knockback ngắt quãng chạy; cleanse slow.",
    },
    UnitSpec {
        id: id("relay_keeper"),
        design_version: 1,
        age: Age::Future,
        name_vi: "Người điều hợp",
        role: UnitRole::Support,
        presentation_hint: PresentationHint::FeminineHuman,
        cost_gold: 180,
        population: 2,
        train: ticks(62),
        hp: 220,
        armor_bp: [armor(2_000), armor(3_000), armor(2_000)],
        move_q_per_tick: q(92),
        half_width_q: q(230),
        attack: AttackSpec {
            damage: 24,
            kind: DamageKind::Arcane,
            windup: ticks(9),
            recovery: ticks(29),
            reach_q: q(4_800),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_000),
        },
        skills: &[
            SkillBinding {
                id: id("summon"),
                design_version: 1,
            },
            SkillBinding {
                id: id("heal"),
                design_version: 1,
            },
        ],
        counterplay_vi: "AOE vào drone; heal không áp dụng drone.",
    },
    UnitSpec {
        id: id("prism_chorus"),
        design_version: 1,
        age: Age::Future,
        name_vi: "Đàn lăng kính",
        role: UnitRole::Siege,
        presentation_hint: PresentationHint::Construct,
        cost_gold: 255,
        population: 4,
        train: ticks(92),
        hp: 350,
        armor_bp: [armor(2_000), armor(2_500), armor(3_500)],
        move_q_per_tick: q(32),
        half_width_q: q(540),
        attack: AttackSpec {
            damage: 124,
            kind: DamageKind::Siege,
            windup: ticks(28),
            recovery: ticks(48),
            reach_q: q(9_800),
            min_reach_q: q(3_200),
            projectile_speed_q_per_tick: q(1_800),
        },
        skills: &[
            SkillBinding {
                id: id("chain"),
                design_version: 1,
            },
            SkillBinding {
                id: id("bombard"),
                design_version: 1,
            },
        ],
        counterplay_vi: "Giãn đội hình và áp sát dead zone3200q.",
    },
];

/// Two exact commander variants per age, reusing the same sixteen payload mechanisms.
pub const SPELLS: [SpellSpec; 12] = [
    SpellSpec { age: Age::Primitive, slot: SpellSlot::First, name_vi: "Mưa đá rễ", card: SkillCard {
        id: id("stonefall"),
        design_version: 1,
        family: SkillFamily::Bombard,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Ground,
        target_filter: TargetFilter::GroundPoint,
        priority: TargetPriority::GroundPoint,
        cost: SkillCost::Gold(60),
        range_q: q(100_000),
        aoe_radius_q: q(2_200),
        max_targets: 4,
        windup: ticks(8),
        contact: Contact::DelayedArea { delay: ticks(20) },
        recovery: ticks(10),
        cooldown: ticks(700),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Bombard { damage: 100, kind: DamageKind::Physical },
        cues: CueKeys { activate: id("age_war.stonefall.activate"), contact: id("age_war.stonefall.contact"), expire: id("age_war.stonefall.expire"), audio: id("age_war.stonefall.audio") },
        power_budget_points: 90,
        counterplay_vi: "Di chuyển khỏi điểm khóa trong 20 tick; minimum range của siege mở cửa áp sát.",
        oracle_vi: "Khóa ground tại commit; sau20tick hit100 physical, bán kính2200q, tối đa4 entity. Không retarget sau khi khóa.",
    } },
    SpellSpec { age: Age::Primitive, slot: SpellSlot::Second, name_vi: "Nhịp lá xanh", card: SkillCard {
        id: id("green_rest"),
        design_version: 1,
        family: SkillFamily::Heal,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Ally,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::LowestHpRatioThenNearestThenId,
        cost: SkillCost::Gold(50),
        range_q: q(100_000),
        aoe_radius_q: q(3_000),
        max_targets: 3,
        windup: ticks(8),
        contact: Contact::Instant,
        recovery: ticks(10),
        cooldown: ticks(600),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Heal { hp: 85 },
        cues: CueKeys { activate: id("age_war.green_rest.activate"), contact: id("age_war.green_rest.contact"), expire: id("age_war.green_rest.expire"), audio: id("age_war.green_rest.audio") },
        power_budget_points: 80,
        counterplay_vi: "Dồn burst hoặc áp sát support; lifetime heal cap ngăn stall.",
        oracle_vi: "Hồi85HP cho tối đa3 regular ally theo HP ratio/id; lifetime35% và overheal vẫn áp dụng, không heal structures/drone.",
    } },
    SpellSpec { age: Age::Ancient, slot: SpellSlot::First, name_vi: "Lao mặt trời", card: SkillCard {
        id: id("sun_javelin"),
        design_version: 1,
        family: SkillFamily::Pierce,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::UnitsAndStructures,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Gold(75),
        range_q: q(100_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(12),
        contact: Contact::Projectile { speed_q_per_tick: q(2_000), lifetime: ticks(60) },
        recovery: ticks(12),
        cooldown: ticks(760),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Pierce { damage: 160, pierce_bp: bp(3_000) },
        cues: CueKeys { activate: id("age_war.sun_javelin.activate"), contact: id("age_war.sun_javelin.contact"), expire: id("age_war.sun_javelin.expire"), audio: id("age_war.sun_javelin.audio") },
        power_budget_points: 105,
        counterplay_vi: "Đổi sang HP hoặc giáp arcane; nhiều quân rẻ khiến xuyên giáp mất lợi thế.",
        oracle_vi: "Một projectile hit160 physical, giảm30% mitigation, floor từng bước; TTL60tick, không retarget.",
    } },
    SpellSpec { age: Age::Ancient, slot: SpellSlot::Second, name_vi: "Hợp xướng đồng", card: SkillCard {
        id: id("iron_chorus"),
        design_version: 1,
        family: SkillFamily::Shield,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Ally,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::ThreatThenHpRatioThenNearestThenId,
        cost: SkillCost::Gold(80),
        range_q: q(100_000),
        aoe_radius_q: q(3_000),
        max_targets: 3,
        windup: ticks(8),
        contact: Contact::Instant,
        recovery: ticks(10),
        cooldown: ticks(700),
        duration: ticks(100),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::Timeout,
        dispel: DispelTag::Positive,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Shield { hp: 110 },
        cues: CueKeys { activate: id("age_war.iron_chorus.activate"), contact: id("age_war.iron_chorus.contact"), expire: id("age_war.iron_chorus.expire"), audio: id("age_war.iron_chorus.audio") },
        power_budget_points: 100,
        counterplay_vi: "Dùng burst vượt shield pool25% maxHP hoặc đợi100tick; lifetime grant không tự nạp lại.",
        oracle_vi: "Grant110 shield cho tối đa3 regular ally; duration100tick; tổng grant lifetime50% maxHP vẫn bị chặn.",
    } },
    SpellSpec { age: Age::Feudal, slot: SpellSlot::First, name_vi: "Lưới gai mềm", card: SkillCard {
        id: id("briar_net"),
        design_version: 1,
        family: SkillFamily::Root,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Gold(75),
        range_q: q(100_000),
        aoe_radius_q: q(1_800),
        max_targets: 2,
        windup: ticks(8),
        contact: Contact::Instant,
        recovery: ticks(10),
        cooldown: ticks(760),
        duration: ticks(12),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::Timeout,
        dispel: DispelTag::Negative,
        immunity: Immunity::Control { after_ticks: ticks(40) },
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Root,
        cues: CueKeys { activate: id("age_war.briar_net.activate"), contact: id("age_war.briar_net.contact"), expire: id("age_war.briar_net.expire"), audio: id("age_war.briar_net.audio") },
        power_budget_points: 100,
        counterplay_vi: "Dispel hoặc dùng quân làm mồi; cửa sổ miễn control ngăn khóa vĩnh viễn.",
        oracle_vi: "Tối đa2 regular enemy trong AOE1800q bị root12tick; không khóa attack; từng target nhận miễn control40tick sau root end/cleanse (root end12 thì ready52).",
    } },
    SpellSpec { age: Age::Feudal, slot: SpellSlot::Second, name_vi: "Trống bước dài", card: SkillCard {
        id: id("marching_drum"),
        design_version: 1,
        family: SkillFamily::Charge,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Ally,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Gold(80),
        range_q: q(100_000),
        aoe_radius_q: q(3_000),
        max_targets: 3,
        windup: ticks(8),
        contact: Contact::Instant,
        recovery: ticks(10),
        cooldown: ticks(800),
        duration: ticks(120),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::NextAttackOrTimeout,
        dispel: DispelTag::Positive,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Charge { bonus_damage: 100, required_run_q: q(0) },
        cues: CueKeys { activate: id("age_war.marching_drum.activate"), contact: id("age_war.marching_drum.contact"), expire: id("age_war.marching_drum.expire"), audio: id("age_war.marching_drum.audio") },
        power_budget_points: 110,
        counterplay_vi: "Dùng quân rẻ hấp thụ boosted hit hoặc kite đến120tick; buff không tăng move/armor và không hồi cooldown.",
        oracle_vi: "Tối đa3 regular ally nhận +100 ở hit kế tiếp, không cần run; tiêu thụ mỗi buff một lần hoặc hết120tick.",
    } },
    SpellSpec { age: Age::Arcane, slot: SpellSlot::First, name_vi: "Cung chớp pha lê", card: SkillCard {
        id: id("prism_arc"),
        design_version: 1,
        family: SkillFamily::Chain,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Gold(90),
        range_q: q(100_000),
        aoe_radius_q: q(0),
        max_targets: 4,
        windup: ticks(8),
        contact: Contact::Instant,
        recovery: ticks(10),
        cooldown: ticks(840),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Chain { damage: 90, kind: DamageKind::Arcane, jumps: 4, jump_range_q: q(1_400), retention_bp: bp(8_000) },
        cues: CueKeys { activate: id("age_war.prism_arc.activate"), contact: id("age_war.prism_arc.contact"), expire: id("age_war.prism_arc.expire"), audio: id("age_war.prism_arc.audio") },
        power_budget_points: 120,
        counterplay_vi: "Giãn đội hình hơn 1.600 q; từng entity chỉ bị một lần mỗi cast.",
        oracle_vi: "Bốn hit arcane trước giáp90/72/57/45; mỗi hop <=1400q; entity đã-hit không được chọn lại.",
    } },
    SpellSpec { age: Age::Arcane, slot: SpellSlot::Second, name_vi: "Trăng gỡ nút", card: SkillCard {
        id: id("clear_moon"),
        design_version: 1,
        family: SkillFamily::Dispel,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Ally,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::HostileControlThenOldestThenId,
        cost: SkillCost::Gold(65),
        range_q: q(100_000),
        aoe_radius_q: q(3_000),
        max_targets: 3,
        windup: ticks(8),
        contact: Contact::Instant,
        recovery: ticks(10),
        cooldown: ticks(640),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Dispel { remove_up_to: 2 },
        cues: CueKeys { activate: id("age_war.clear_moon.activate"), contact: id("age_war.clear_moon.contact"), expire: id("age_war.clear_moon.expire"), audio: id("age_war.clear_moon.audio") },
        power_budget_points: 90,
        counterplay_vi: "Dùng nhiều debuff khác family hoặc ép support dùng cleanse trước.",
        oracle_vi: "Tối đa3 regular ally, mỗi target bỏ tối đa2 negative status theo root→slow→DoT/shred, oldest application/status/source id; không trả HP đã mất.",
    } },
    SpellSpec { age: Age::Industrial, slot: SpellSlot::First, name_vi: "Mưa ngòi ngắn", card: SkillCard {
        id: id("fuse_rain"),
        design_version: 1,
        family: SkillFamily::Bombard,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Ground,
        target_filter: TargetFilter::GroundPoint,
        priority: TargetPriority::GroundPoint,
        cost: SkillCost::Gold(100),
        range_q: q(100_000),
        aoe_radius_q: q(2_400),
        max_targets: 5,
        windup: ticks(14),
        contact: Contact::DelayedArea { delay: ticks(30) },
        recovery: ticks(10),
        cooldown: ticks(920),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Bombard { damage: 170, kind: DamageKind::Siege },
        cues: CueKeys { activate: id("age_war.fuse_rain.activate"), contact: id("age_war.fuse_rain.contact"), expire: id("age_war.fuse_rain.expire"), audio: id("age_war.fuse_rain.audio") },
        power_budget_points: 140,
        counterplay_vi: "Di chuyển khỏi điểm khóa trong 20 tick; minimum range của siege mở cửa áp sát.",
        oracle_vi: "Khóa ground; delay30tick; siege170 trong2400q, tối đa5 entity; hit cuối trước expiry; không damage ngoài vùng.",
    } },
    SpellSpec { age: Age::Industrial, slot: SpellSlot::Second, name_vi: "Sương làm nguội", card: SkillCard {
        id: id("coolant_mist"),
        design_version: 1,
        family: SkillFamily::Slow,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Gold(80),
        range_q: q(100_000),
        aoe_radius_q: q(2_000),
        max_targets: 4,
        windup: ticks(8),
        contact: Contact::Instant,
        recovery: ticks(10),
        cooldown: ticks(760),
        duration: ticks(80),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::ExtendExpiry,
        expiry: ExpiryPolicy::Timeout,
        dispel: DispelTag::Negative,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Slow { reduction_bp: bp(4_000) },
        cues: CueKeys { activate: id("age_war.coolant_mist.activate"), contact: id("age_war.coolant_mist.contact"), expire: id("age_war.coolant_mist.expire"), audio: id("age_war.coolant_mist.audio") },
        power_budget_points: 105,
        counterplay_vi: "Dispel; slow yếu hơn không cộng thêm và không refresh hiệu lực mạnh.",
        oracle_vi: "Tối đa4 regular enemy trong2000q; move giảm40% trong80tick; slow không cộng và không kéo dài slow mạnh bằng slow yếu.",
    } },
    SpellSpec { age: Age::Future, slot: SpellSlot::First, name_vi: "Bầy trạm nhỏ", card: SkillCard {
        id: id("relay_swarm"),
        design_version: 1,
        family: SkillFamily::Summon,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Ground,
        target_filter: TargetFilter::GroundPoint,
        priority: TargetPriority::GroundPoint,
        cost: SkillCost::Gold(90),
        range_q: q(100_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(8),
        contact: Contact::Instant,
        recovery: ticks(10),
        cooldown: ticks(960),
        duration: ticks(240),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::Timeout,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::Summon { count: 2, drone: DRONES[1], lifetime: ticks(240) },
        cues: CueKeys { activate: id("age_war.relay_swarm.activate"), contact: id("age_war.relay_swarm.contact"), expire: id("age_war.relay_swarm.expire"), audio: id("age_war.relay_swarm.audio") },
        power_budget_points: 125,
        counterplay_vi: "AOE diệt drone; drone không nhận heal/shield, không XP/bounty.",
        oracle_vi: "GroundPoint khóa tại accept; hai drone HP60/damage12/period28/TTL240 phải vừa owned-side interval, không qua blocker; thiếu space/pop2/cap4owner8match reject trước gold/cooldown; source chết không despawn.",
    } },
    SpellSpec { age: Age::Future, slot: SpellSlot::Second, name_vi: "Vệt xung sáng", card: SkillCard {
        id: id("pulse_wake"),
        design_version: 1,
        family: SkillFamily::BurstHeat,
        activation: Activation::CommanderCast,
        trigger: Trigger::Always,
        target_side: TargetSide::Enemy,
        target_filter: TargetFilter::NormalUnits,
        priority: TargetPriority::NearestThenId,
        cost: SkillCost::Gold(110),
        range_q: q(100_000),
        aoe_radius_q: q(0),
        max_targets: 1,
        windup: ticks(8),
        contact: Contact::Projectile { speed_q_per_tick: q(2_400), lifetime: ticks(48) },
        recovery: ticks(10),
        cooldown: ticks(960),
        duration: ticks(0),
        stacking: StackPolicy::UniqueStrongest,
        refresh: RefreshPolicy::KeepExpiry,
        expiry: ExpiryPolicy::ContactOnly,
        dispel: DispelTag::None,
        immunity: Immunity::None,
        interrupt: InterruptPolicy::WindupOnHardControl,
        effect: SkillEffect::BurstHeat { damage: 95, kind: DamageKind::Arcane, shots: 3, spacing: ticks(4), heat_per_shot: 30, heat_limit: 100, decay_per_tick: 1 },
        cues: CueKeys { activate: id("age_war.pulse_wake.activate"), contact: id("age_war.pulse_wake.contact"), expire: id("age_war.pulse_wake.expire"), audio: id("age_war.pulse_wake.audio") },
        power_budget_points: 145,
        counterplay_vi: "Ép burst vào tank rồi phản công trong lúc nguồn đang xả nhiệt.",
        oracle_vi: "Ba projectile95 arcane cách4tick, heat30/shot; cần heat+90<=100 trước commit; decay1/tick và TTL48tick; khóa target.",
    } },
];

/// Two mutually exclusive branches per age; there remain only two physical slots per owner.
pub const TURRETS: [TurretSpec; 12] = [
    TurretSpec {
        id: id("reed_slinger"),
        design_version: 1,
        age: Age::Primitive,
        branch: TurretBranch::Direct,
        name_vi: "Cột lau ném",
        cost_gold: 100,
        build: ticks(80),
        hp: 350,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 24,
            kind: DamageKind::Physical,
            windup: ticks(10),
            recovery: ticks(30),
            reach_q: q(6_500),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(850),
        },
        skills: &[SkillBinding {
            id: id("pierce"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("spore_post"),
        design_version: 1,
        age: Age::Primitive,
        branch: TurretBranch::Control,
        name_vi: "Cột bào tử",
        cost_gold: 110,
        build: ticks(80),
        hp: 320,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 14,
            kind: DamageKind::Arcane,
            windup: ticks(10),
            recovery: ticks(34),
            reach_q: q(6_200),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(750),
        },
        skills: &[SkillBinding {
            id: id("dot"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("bronze_spiral"),
        design_version: 1,
        age: Age::Ancient,
        branch: TurretBranch::Direct,
        name_vi: "Trục đồng xoắn",
        cost_gold: 140,
        build: ticks(80),
        hp: 410,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 34,
            kind: DamageKind::Physical,
            windup: ticks(12),
            recovery: ticks(32),
            reach_q: q(7_000),
            min_reach_q: q(1_000),
            projectile_speed_q_per_tick: q(1_000),
        },
        skills: &[SkillBinding {
            id: id("pierce"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("sand_net_post"),
        design_version: 1,
        age: Age::Ancient,
        branch: TurretBranch::Control,
        name_vi: "Cột lưới cát",
        cost_gold: 150,
        build: ticks(80),
        hp: 370,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 18,
            kind: DamageKind::Physical,
            windup: ticks(12),
            recovery: ticks(36),
            reach_q: q(6_500),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(900),
        },
        skills: &[SkillBinding {
            id: id("root"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("mist_crossbow"),
        design_version: 1,
        age: Age::Feudal,
        branch: TurretBranch::Direct,
        name_vi: "Nỏ sương",
        cost_gold: 180,
        build: ticks(80),
        hp: 470,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 36,
            kind: DamageKind::Physical,
            windup: ticks(12),
            recovery: ticks(30),
            reach_q: q(7_400),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_200),
        },
        skills: &[SkillBinding {
            id: id("volley"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("lotus_ram_post"),
        design_version: 1,
        age: Age::Feudal,
        branch: TurretBranch::Control,
        name_vi: "Cột chày sen",
        cost_gold: 190,
        build: ticks(80),
        hp: 430,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 24,
            kind: DamageKind::Physical,
            windup: ticks(14),
            recovery: ticks(36),
            reach_q: q(6_500),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_000),
        },
        skills: &[SkillBinding {
            id: id("knockback"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("split_prism_post"),
        design_version: 1,
        age: Age::Arcane,
        branch: TurretBranch::Direct,
        name_vi: "Cột lăng kính tách",
        cost_gold: 220,
        build: ticks(80),
        hp: 500,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 40,
            kind: DamageKind::Arcane,
            windup: ticks(14),
            recovery: ticks(32),
            reach_q: q(7_800),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_300),
        },
        skills: &[SkillBinding {
            id: id("chain"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("rune_frost_post"),
        design_version: 1,
        age: Age::Arcane,
        branch: TurretBranch::Control,
        name_vi: "Cột sương ký tự",
        cost_gold: 230,
        build: ticks(80),
        hp: 460,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 22,
            kind: DamageKind::Arcane,
            windup: ticks(12),
            recovery: ticks(34),
            reach_q: q(7_100),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_200),
        },
        skills: &[SkillBinding {
            id: id("slow"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("fuse_cannon_post"),
        design_version: 1,
        age: Age::Industrial,
        branch: TurretBranch::Direct,
        name_vi: "Cột pháo ngòi",
        cost_gold: 260,
        build: ticks(80),
        hp: 570,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 60,
            kind: DamageKind::Siege,
            windup: ticks(20),
            recovery: ticks(42),
            reach_q: q(8_200),
            min_reach_q: q(2_200),
            projectile_speed_q_per_tick: q(1_500),
        },
        skills: &[SkillBinding {
            id: id("bombard"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("cooling_scatter_post"),
        design_version: 1,
        age: Age::Industrial,
        branch: TurretBranch::Control,
        name_vi: "Cột tán nguội",
        cost_gold: 270,
        build: ticks(80),
        hp: 520,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 28,
            kind: DamageKind::Physical,
            windup: ticks(12),
            recovery: ticks(32),
            reach_q: q(7_600),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_600),
        },
        skills: &[SkillBinding {
            id: id("burst_heat"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("orbit_cutter_post"),
        design_version: 1,
        age: Age::Future,
        branch: TurretBranch::Direct,
        name_vi: "Cột cắt quỹ đạo",
        cost_gold: 300,
        build: ticks(80),
        hp: 640,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 52,
            kind: DamageKind::Physical,
            windup: ticks(14),
            recovery: ticks(32),
            reach_q: q(8_800),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_900),
        },
        skills: &[SkillBinding {
            id: id("pierce"),
            design_version: 1,
        }],
    },
    TurretSpec {
        id: id("gravity_anchor_post"),
        design_version: 1,
        age: Age::Future,
        branch: TurretBranch::Control,
        name_vi: "Cột neo trọng lực",
        cost_gold: 310,
        build: ticks(80),
        hp: 580,
        armor_bp: [armor(2_000), armor(1_500), armor(1_000)],
        attack: AttackSpec {
            damage: 28,
            kind: DamageKind::Arcane,
            windup: ticks(14),
            recovery: ticks(36),
            reach_q: q(8_000),
            min_reach_q: q(0),
            projectile_speed_q_per_tick: q(1_800),
        },
        skills: &[SkillBinding {
            id: id("knockback"),
            design_version: 1,
        }],
    },
];

/// Twelve nonstackable technology identities; global totals are capped separately.
pub const TECHS: [TechSpec; 12] = [
    TechSpec {
        id: id("primitive_attack"),
        design_version: 1,
        age: Age::Primitive,
        kind: TechKind::Attack,
        cost_gold: 120,
        research: ticks(60),
        bonus_bp: bp(1_000),
    },
    TechSpec {
        id: id("primitive_armor"),
        design_version: 1,
        age: Age::Primitive,
        kind: TechKind::Armor,
        cost_gold: 140,
        research: ticks(60),
        bonus_bp: bp(250),
    },
    TechSpec {
        id: id("ancient_attack"),
        design_version: 1,
        age: Age::Ancient,
        kind: TechKind::Attack,
        cost_gold: 160,
        research: ticks(60),
        bonus_bp: bp(1_000),
    },
    TechSpec {
        id: id("ancient_armor"),
        design_version: 1,
        age: Age::Ancient,
        kind: TechKind::Armor,
        cost_gold: 180,
        research: ticks(60),
        bonus_bp: bp(250),
    },
    TechSpec {
        id: id("feudal_attack"),
        design_version: 1,
        age: Age::Feudal,
        kind: TechKind::Attack,
        cost_gold: 200,
        research: ticks(60),
        bonus_bp: bp(1_000),
    },
    TechSpec {
        id: id("feudal_armor"),
        design_version: 1,
        age: Age::Feudal,
        kind: TechKind::Armor,
        cost_gold: 220,
        research: ticks(60),
        bonus_bp: bp(250),
    },
    TechSpec {
        id: id("arcane_attack"),
        design_version: 1,
        age: Age::Arcane,
        kind: TechKind::Attack,
        cost_gold: 240,
        research: ticks(60),
        bonus_bp: bp(1_000),
    },
    TechSpec {
        id: id("arcane_armor"),
        design_version: 1,
        age: Age::Arcane,
        kind: TechKind::Armor,
        cost_gold: 260,
        research: ticks(60),
        bonus_bp: bp(250),
    },
    TechSpec {
        id: id("industrial_attack"),
        design_version: 1,
        age: Age::Industrial,
        kind: TechKind::Attack,
        cost_gold: 280,
        research: ticks(60),
        bonus_bp: bp(1_000),
    },
    TechSpec {
        id: id("industrial_armor"),
        design_version: 1,
        age: Age::Industrial,
        kind: TechKind::Armor,
        cost_gold: 300,
        research: ticks(60),
        bonus_bp: bp(250),
    },
    TechSpec {
        id: id("future_attack"),
        design_version: 1,
        age: Age::Future,
        kind: TechKind::Attack,
        cost_gold: 320,
        research: ticks(60),
        bonus_bp: bp(1_000),
    },
    TechSpec {
        id: id("future_armor"),
        design_version: 1,
        age: Age::Future,
        kind: TechKind::Armor,
        cost_gold: 340,
        research: ticks(60),
        bonus_bp: bp(250),
    },
];

/// Five advancement thresholds. XP is total earned and is never spent.
pub const AGE_ADVANCES: [AgeAdvanceSpec; 5] = [
    AgeAdvanceSpec {
        to_age: Age::Ancient,
        gold: 250,
        total_xp: 60,
        duration: ticks(100),
    },
    AgeAdvanceSpec {
        to_age: Age::Feudal,
        gold: 400,
        total_xp: 140,
        duration: ticks(100),
    },
    AgeAdvanceSpec {
        to_age: Age::Arcane,
        gold: 600,
        total_xp: 240,
        duration: ticks(100),
    },
    AgeAdvanceSpec {
        to_age: Age::Industrial,
        gold: 850,
        total_xp: 360,
        duration: ticks(100),
    },
    AgeAdvanceSpec {
        to_age: Age::Future,
        gold: 1150,
        total_xp: 500,
        duration: ticks(100),
    },
];
