//! Read-only Rust registry metadata -> lightweight CMP discovery data (I-9; doc 04 §3.3).
//! No game factory, renderer, assets pack, native library or launch authority is generated.

use std::{fmt::Write as _, path::Path};

use tabula_registry::{
    discovery::ErasedDiscoveryGame, platform_messages, Category, Complexity, ContentRating,
    FieldKind, Locale,
};

const OUTPUT: &str = "apps/mobile/shared/src/commonMain/kotlin/com/loveoverflow/tabula/mobile/catalog/RegistryDiscoveryCatalog.kt";

pub fn run() -> Result<(), String> {
    let root = crate::workspace::root().map_err(|error| error.to_string())?;
    let generated = generate()?;
    std::fs::write(root.join(OUTPUT), generated).map_err(|error| error.to_string())?;
    println!("generated {OUTPUT}");
    Ok(())
}

pub fn check_current() -> Result<bool, String> {
    let root = crate::workspace::root().map_err(|error| error.to_string())?;
    check_at(&root)
}

fn check_at(root: &Path) -> Result<bool, String> {
    let generated = generate()?;
    let current = std::fs::read_to_string(root.join(OUTPUT)).map_err(|error| error.to_string())?;
    if current != generated {
        eprintln!("{OUTPUT} is stale; run `cargo xtask gen-mobile-catalog`");
        return Ok(false);
    }
    println!("mobile discovery catalog matches the Rust registry");
    Ok(true)
}

fn generate() -> Result<String, String> {
    let games = tabula_registry::registered_discovery_games();
    let game_ids: Vec<_> = games
        .iter()
        .map(|game| {
            game.metadata()
                .id()
                .as_str()
                .rsplit('.')
                .next()
                .unwrap_or_default()
                .to_owned()
        })
        .collect();
    let mut out = String::from(
        "// @generated by cargo xtask gen-mobile-catalog; do not edit.\n\
         // Registry literals carry a scoped I-9 exemption: facts are copied as data, never game dispatch.\n\
         package com.loveoverflow.tabula.mobile.catalog\n\n\
         /** Public read-only catalog for this build; native play availability remains separate (ADR-0043). */\n\
         object RegistryDiscoveryCatalog {\n",
    );
    out.push_str("    val games: List<DiscoveryGame> = listOf(\n");
    for game in games {
        emit_game(&mut out, game.as_ref())?;
    }
    out.push_str("    )\n}\n");
    // A generated literal is the only exemption. Normal Kotlin consumer files remain scanned.
    Ok(out
        .lines()
        .map(|line| {
            if crate::game_ids_policy::scan_file(OUTPUT, line, &game_ids).is_empty() {
                line.to_owned()
            } else {
                format!("{line} // xtask-allow-game-id: generated registry data, never dispatch.")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n")
}

#[allow(clippy::too_many_lines)]
fn emit_game(out: &mut String, game: &dyn ErasedDiscoveryGame) -> Result<(), String> {
    let metadata = game.metadata();
    let rules_version = i32::try_from(metadata.rules_version().0)
        .map_err(|_| "rules version exceeds the CMP discovery representation".to_owned())?;
    writeln!(out, "        DiscoveryGame(").unwrap();
    writeln!(
        out,
        "            id = {},",
        kotlin_string(metadata.id().as_str())
    )
    .unwrap();
    for (property, key) in [
        ("names", metadata.name_key()),
        ("taglines", metadata.tagline_key()),
        ("descriptions", metadata.description_key()),
    ] {
        writeln!(
            out,
            "            {property} = {},",
            translated(game, Some(key.as_str()))?
        )
        .unwrap();
    }
    let categories: Vec<_> = metadata
        .categories()
        .iter()
        .map(|value| category(*value))
        .collect();
    writeln!(
        out,
        "            categories = {},",
        string_list(categories.iter().map(|(id, _)| *id))
    )
    .unwrap();
    let names = categories
        .iter()
        .map(|(id, key)| {
            Ok(format!(
                "{} to {}",
                kotlin_string(id),
                translated(game, Some(key))?
            ))
        })
        .collect::<Result<Vec<_>, String>>()?;
    writeln!(
        out,
        "            categoryNames = mapOf({}),",
        names.join(", ")
    )
    .unwrap();
    writeln!(
        out,
        "            tags = {},",
        string_list(metadata.tags().iter().map(String::as_str))
    )
    .unwrap();
    let seats =
        (1..=u8::MAX).filter(|count| game.capabilities().seats().allowed().contains(*count));
    writeln!(
        out,
        "            players = listOf({}),",
        seats
            .map(|count| count.to_string())
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    writeln!(
        out,
        "            minMinutes = {},",
        metadata.estimated_minutes().min()
    )
    .unwrap();
    writeln!(
        out,
        "            maxMinutes = {},",
        metadata.estimated_minutes().max()
    )
    .unwrap();
    let (complexity, key) = complexity(metadata.complexity());
    writeln!(
        out,
        "            complexity = {},",
        kotlin_string(complexity)
    )
    .unwrap();
    writeln!(
        out,
        "            complexityNames = {},",
        translated(game, Some(key))?
    )
    .unwrap();
    writeln!(out, "            rulesVersion = {rules_version},").unwrap();
    writeln!(
        out,
        "            version = {},",
        kotlin_string(metadata.version().as_str())
    )
    .unwrap();
    let (rating, rating_key) = content_rating(metadata.content_rating());
    writeln!(
        out,
        "            contentRating = {},",
        kotlin_string(rating)
    )
    .unwrap();
    writeln!(
        out,
        "            contentRatingNames = {},",
        translated(game, Some(rating_key))?
    )
    .unwrap();
    writeln!(
        out,
        "            hiddenInformation = {},",
        game.capabilities().hidden_information()
    )
    .unwrap();
    writeln!(
        out,
        "            rulesUrls = {},",
        translated(
            game,
            metadata
                .rules_url_key()
                .map(tabula_registry::I18nKey::as_str)
        )?
    )
    .unwrap();
    out.push_str("            modes = listOf(\n");
    for support in game.modes() {
        writeln!(out, "                DiscoveryMode(").unwrap();
        writeln!(
            out,
            "                    id = {},",
            kotlin_string(support.mode.as_str())
        )
        .unwrap();
        writeln!(
            out,
            "                    labels = {},",
            translated(game, Some(support.mode.label_key()))?
        )
        .unwrap();
        writeln!(
            out,
            "                    consequences = {},",
            translated(game, Some(support.mode.consequence_key()))?
        )
        .unwrap();
        writeln!(
            out,
            "                    registryAvailable = {},",
            support.is_available()
        )
        .unwrap();
        let reason = support.unavailable_reason();
        writeln!(
            out,
            "                    reasons = {},",
            translated(
                game,
                reason.map(tabula_registry::UnavailableReason::reason_key)
            )?
        )
        .unwrap();
        writeln!(
            out,
            "                    recoveries = {},",
            translated(
                game,
                reason.map(tabula_registry::UnavailableReason::recovery_key)
            )?
        )
        .unwrap();
        out.push_str("                ),\n");
    }
    out.push_str("            ),\n            fields = listOf(\n");
    for field in game.form().fields {
        out.push_str("                DiscoveryField(\n");
        writeln!(
            out,
            "                    key = {},",
            kotlin_string(field.key)
        )
        .unwrap();
        writeln!(
            out,
            "                    labels = {},",
            translated(game, Some(field.label_key))?
        )
        .unwrap();
        writeln!(
            out,
            "                    hints = {},",
            translated(game, field.hint_key)?
        )
        .unwrap();
        match field.kind {
            FieldKind::Choice { options } => {
                out.push_str("                    choices = listOf(\n");
                for choice in options {
                    writeln!(
                        out,
                        "                        DiscoveryChoice({}, {}, {}),",
                        kotlin_string(choice.value),
                        translated(game, Some(choice.label_key))?,
                        string_list(choice.reveals.iter().copied())
                    )
                    .unwrap();
                }
                out.push_str("                    ),\n");
                writeln!(
                    out,
                    "                    default = {},",
                    kotlin_string(options.first().map_or("", |choice| choice.value))
                )
                .unwrap();
            }
            FieldKind::Integer { min, max, default } => {
                writeln!(
                    out,
                    "                    min = {}, max = {}, default = {},",
                    kotlin_string(&min.to_string()),
                    kotlin_string(&max.to_string()),
                    kotlin_string(&default.to_string())
                )
                .unwrap();
            }
        }
        out.push_str("                ),\n");
    }
    out.push_str("            ),\n");
    if let Some(svg) = game.catalog_cover_svg() {
        if svg.len() > 8192
            || !svg.starts_with("<svg ")
            || ["<script", "<image", "<foreignObject", "href=", "<style"]
                .iter()
                .any(|forbidden| svg.contains(forbidden))
        {
            return Err("catalog cover exceeds the inert lightweight source contract".to_owned());
        }
        writeln!(
            out,
            "            cover = DiscoveryCover(svg = {}),",
            kotlin_string(svg)
        )
        .unwrap();
    }
    out.push_str("        ),\n");
    Ok(())
}

fn translated(game: &dyn ErasedDiscoveryGame, key: Option<&str>) -> Result<String, String> {
    let Some(key) = key else {
        return Ok("emptyMap()".to_owned());
    };
    let rows = Locale::ALL
        .into_iter()
        .map(|locale| {
            let table = game.messages(locale);
            let text = table
                .iter()
                .chain(platform_messages(locale))
                .find_map(|(candidate, text)| (*candidate == key).then_some(*text))
                .ok_or_else(|| {
                    format!("missing registry translation for {key} in {}", locale.tag())
                })?;
            Ok(format!(
                "{} to {}",
                kotlin_string(locale.tag()),
                kotlin_string(text)
            ))
        })
        .collect::<Result<Vec<_>, String>>()?;
    Ok(format!("mapOf({})", rows.join(", ")))
}

fn string_list<'a>(values: impl Iterator<Item = &'a str>) -> String {
    format!(
        "listOf({})",
        values.map(kotlin_string).collect::<Vec<_>>().join(", ")
    )
}

fn kotlin_string(value: &str) -> String {
    let mut out = String::from("\"");
    for character in value.chars() {
        match character {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '$' => out.push_str("\\$"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            value if value.is_control() => write!(out, "\\u{:04x}", u32::from(value)).unwrap(),
            value => out.push(value),
        }
    }
    out.push('"');
    out
}

const fn category(value: Category) -> (&'static str, &'static str) {
    match value {
        Category::Abstract => ("abstract", "category.abstract"),
        Category::Cards => ("cards", "category.cards"),
        Category::SocialDeduction => ("social_deduction", "category.social_deduction"),
        Category::TilePlacement => ("tile_placement", "category.tile_placement"),
        Category::Party => ("party", "category.party"),
    }
}

const fn complexity(value: Complexity) -> (&'static str, &'static str) {
    match value {
        Complexity::Light => ("light", "complexity.light"),
        Complexity::Medium => ("medium", "complexity.medium"),
        Complexity::Heavy => ("heavy", "complexity.heavy"),
    }
}

const fn content_rating(value: ContentRating) -> (&'static str, &'static str) {
    match value {
        ContentRating::Everyone => ("everyone", "rating.everyone"),
        ContentRating::Teen => ("teen", "rating.teen"),
        ContentRating::Mature => ("mature", "rating.mature"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_copy_comes_from_every_registered_module_and_is_lightweight() {
        let generated = generate().expect("every declared translation exists");
        let games = tabula_registry::registered_discovery_games();
        assert!(
            !games.is_empty(),
            "catalog test must exercise a linked module"
        );
        assert_eq!(
            generated.matches("        DiscoveryGame(").count(),
            games.len()
        );
        for game in games {
            assert!(generated.contains(&format!(
                "id = {}",
                kotlin_string(game.metadata().id().as_str())
            )));
            for locale in Locale::ALL {
                let name = game
                    .messages(locale)
                    .iter()
                    .find_map(|(key, value)| {
                        (*key == game.metadata().name_key().as_str()).then_some(*value)
                    })
                    .expect("module supplies its name");
                assert!(generated.contains(&kotlin_string(name)));
            }
        }
        assert!(
            generated.len() < 48 * 1024,
            "discovery must remain lightweight"
        );
        assert!(!generated.contains("GameLaunch("));
        assert!(!generated.contains("BundledGame("));
    }

    #[test]
    fn kotlin_strings_escape_interpolation_and_controls() {
        assert_eq!(
            kotlin_string("$amount\n\"\\\u{0000}"),
            "\"\\$amount\\n\\\"\\\\\\u0000\""
        );
    }

    #[test]
    fn stale_generated_catalog_is_rejected() {
        let root = tempfile::tempdir().unwrap();
        let path = root.path().join(OUTPUT);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, generate().unwrap()).unwrap();
        assert!(check_at(root.path()).unwrap());
        std::fs::write(&path, "// stale catalog\n").unwrap();
        assert!(!check_at(root.path()).unwrap());
    }

    #[test]
    fn kotlin_consumers_are_scanned_while_only_generated_literal_lines_are_exempt() {
        let ids = vec!["sample".to_owned()];
        let consumer = "apps/mobile/shared/src/commonMain/kotlin/example/Consumer.kt";
        assert_eq!(
            crate::game_ids_policy::scan_file(
                consumer,
                "if (game.id == \"com.example.sample\") launch()",
                &ids
            )
            .len(),
            1
        );
        let generated = generate().unwrap();
        let registered: Vec<_> = tabula_registry::registered_discovery_games()
            .iter()
            .map(|game| {
                game.metadata()
                    .id()
                    .as_str()
                    .rsplit('.')
                    .next()
                    .unwrap()
                    .to_owned()
            })
            .collect();
        assert!(crate::game_ids_policy::scan_file(OUTPUT, &generated, &registered).is_empty());
        assert!(
            generated
                .lines()
                .filter(|line| line.contains("xtask-allow-game-id:"))
                .count()
                < 12
        );
    }
}
