//! Token generation and freshness checking. (doc 04 §8.1)

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, thiserror::Error)]
pub enum TokenError {
    #[error("workspace root cannot be derived")]
    Root,
    #[error("reading {path}: {source}")]
    Read {
        path: PathBuf,
        source: std::io::Error,
    },
    #[error("writing {path}: {source}")]
    Write {
        path: PathBuf,
        source: std::io::Error,
    },
    #[error("tokens.toml: {0}")]
    Toml(#[from] toml::de::Error),
    #[error("scheme `{scheme}` is missing `{key}`")]
    Missing { scheme: String, key: &'static str },
    #[error("scheme `{scheme}` has invalid hexadecimal colour `{value}`")]
    Color { scheme: String, value: String },
    #[error("rustfmt failed while formatting generated Rust")]
    Rustfmt,
}

const SCHEMES: [(&str, &str, &str); 4] = [
    ("light", "LIGHT", "ThemeKind::Light"),
    ("dark", "DARK", "ThemeKind::Dark"),
    (
        "hc-light",
        "HIGH_CONTRAST_LIGHT",
        "ThemeKind::HighContrastLight",
    ),
    (
        "hc-dark",
        "HIGH_CONTRAST_DARK",
        "ThemeKind::HighContrastDark",
    ),
];
const COLOR_KEYS: [&str; 10] = [
    "surface",
    "container",
    "container-high",
    "on-surface",
    "on-surface-variant",
    "outline",
    "primary",
    "on-primary",
    "danger",
    "on-danger",
];

pub fn run() -> Result<(), TokenError> {
    let root = root()?;
    let rendered = render(&root)?;
    for (relative, content) in rendered {
        write_if_changed(&root.join(relative), &content)?;
    }
    println!("gen-tokens: emitted Rust, CSS, and JSON from tokens.toml");
    Ok(())
}

pub fn check_current() -> Result<bool, TokenError> {
    let root = root()?;
    let mut current = true;
    for (relative, rendered) in render(&root)? {
        let path = root.join(relative);
        let existing = std::fs::read_to_string(&path).map_err(|source| TokenError::Read {
            path: path.clone(),
            source,
        })?;
        if existing != rendered {
            eprintln!(
                "generated token output is stale: {} (run `cargo xtask gen-tokens`)",
                path.display()
            );
            current = false;
        }
    }
    Ok(current)
}

fn root() -> Result<PathBuf, TokenError> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .ok_or(TokenError::Root)
}

fn render(root: &Path) -> Result<Vec<(&'static str, String)>, TokenError> {
    let token_path = root.join("tokens.toml");
    let source = std::fs::read_to_string(&token_path).map_err(|source| TokenError::Read {
        path: token_path.clone(),
        source,
    })?;
    let parsed: toml::Value = toml::from_str(&source)?;
    let schemes = parsed
        .get("schemes")
        .and_then(toml::Value::as_table)
        .ok_or(TokenError::Missing {
            scheme: "root".into(),
            key: "schemes",
        })?;
    let mut resolved = BTreeMap::<String, BTreeMap<String, String>>::new();
    for (name, _, _) in SCHEMES {
        let table =
            schemes
                .get(name)
                .and_then(toml::Value::as_table)
                .ok_or(TokenError::Missing {
                    scheme: name.into(),
                    key: "table",
                })?;
        let mut values = BTreeMap::new();
        for key in COLOR_KEYS {
            let value =
                table
                    .get(key)
                    .and_then(toml::Value::as_str)
                    .ok_or(TokenError::Missing {
                        scheme: name.into(),
                        key,
                    })?;
            parse_hex(name, value)?;
            values.insert(key.to_owned(), value.to_owned());
        }
        resolved.insert(name.to_owned(), values);
    }
    Ok(vec![
        (
            "crates/tabula-design/src/generated.rs",
            format_rust(root, &rust(&resolved))?,
        ),
        ("apps/web/style/tokens.css", css(&resolved)),
        ("docs/ui/tokens.json", json(&resolved)),
    ])
}

fn format_rust(root: &Path, source: &str) -> Result<String, TokenError> {
    let path = root.join("target/token-generation.rs");
    std::fs::write(&path, source).map_err(|source| TokenError::Write {
        path: path.clone(),
        source,
    })?;
    if !Command::new("rustfmt")
        .arg(&path)
        .status()
        .is_ok_and(|status| status.success())
    {
        return Err(TokenError::Rustfmt);
    }
    std::fs::read_to_string(&path).map_err(|source| TokenError::Read { path, source })
}

fn rust(schemes: &BTreeMap<String, BTreeMap<String, String>>) -> String {
    let mut output = String::from("// @generated by `cargo xtask gen-tokens`; do not edit.\nuse crate::{Color, ColorTokens, Density, ElevationTokens, FocusTokens, MotionTokens, ShapeTokens, SpaceTokens, StateLayerTokens, Theme, ThemeKind};\n\nconst TEAM: [Color; 8] = [Color::rgb(0, 95, 115), Color::rgb(202, 103, 2), Color::rgb(109, 89, 122), Color::rgb(18, 125, 102), Color::rgb(182, 70, 100), Color::rgb(56, 95, 145), Color::rgb(121, 82, 30), Color::rgb(94, 88, 126)];\n#[allow(clippy::too_many_arguments)]\nconst fn theme(kind: ThemeKind, surface: Color, container: Color, high: Color, on_surface: Color, on_variant: Color, outline: Color, primary: Color, on_primary: Color, danger: Color, on_danger: Color) -> Theme {\n    Theme { kind, color: ColorTokens { surface, surface_container: container, surface_container_high: high, on_surface, on_surface_variant: on_variant, outline, primary, on_primary, success: Color::rgb(16, 111, 61), on_success: Color::rgb(255, 255, 255), danger, on_danger, turn_active: Color::rgb(0, 99, 65), turn_waiting: Color::rgb(94, 88, 104), legal_target: Color::rgb(0, 112, 68), illegal_target: danger, selected: primary, last_action: Color::rgb(176, 112, 0), threat: danger, hidden: Color::rgb(76, 78, 88), team: TEAM, seat_marker: TEAM }, shape: ShapeTokens { card: 16.0, board: 12.0, button: 14.0, chip: 8.0 }, space: SpaceTokens { xs: 4, sm: 8, md: 16, lg: 24, xl: 32 }, elevation: ElevationTokens { low: 1, medium: 2, high: 3 }, motion: MotionTokens { piece_move_ms: 280, card_deal_ms: 280, invalid_ms: 160, phase_change_ms: 480, win_ms: 800, lose_ms: 800, reduced_duration_scale_percent: 0 }, state: StateLayerTokens { hover: 8, focus: 12, press: 12, drag: 16 }, density: Density { scale: 1.0, min_target: 44.0 }, focus: FocusTokens { ring_width: 3.0, ring_color: primary } }\n}\n");
    for (name, constant, kind) in SCHEMES {
        let values = &schemes[name];
        let arguments = COLOR_KEYS
            .into_iter()
            .map(|key| color_rust(&values[key]))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            output,
            "pub const {constant}: Theme = theme({kind}, {arguments});"
        )
        .expect("writing to a String cannot fail");
    }
    output
}

fn css(schemes: &BTreeMap<String, BTreeMap<String, String>>) -> String {
    let mut output = String::from(
        "/* @generated by `cargo xtask gen-tokens` from tokens.toml; do not edit. */\n",
    );
    for (index, (name, _, _)) in SCHEMES.iter().enumerate() {
        let selector = match *name {
            "light" => ":root",
            "dark" => ":root[data-theme=\"dark\"]",
            "hc-light" => ":root[data-theme=\"hc-light\"]",
            _ => ":root[data-theme=\"hc-dark\"]",
        };
        output.push_str(selector);
        output.push_str(" {\n");
        for key in COLOR_KEYS {
            writeln!(output, "  --sys-color-{key}: {};", schemes[*name][key])
                .expect("writing to a String cannot fail");
        }
        output.push_str("  --sys-shape-button: 14px;\n  --sys-motion-piece-move: 280ms;\n  --sys-state-hover: 0.08;\n}\n");
        if index + 1 != SCHEMES.len() {
            output.push('\n');
        }
    }
    output
}

fn json(schemes: &BTreeMap<String, BTreeMap<String, String>>) -> String {
    format!(
        "{}\n",
        serde_json::to_string_pretty(schemes).expect("BTreeMaps are serializable")
    )
}
fn color_rust(value: &str) -> String {
    let bytes = parse_hex("generated", value).expect("validated during render");
    format!("Color::rgb({}, {}, {})", bytes.0, bytes.1, bytes.2)
}
fn parse_hex(scheme: &str, value: &str) -> Result<(u8, u8, u8), TokenError> {
    let Some(value) = value.strip_prefix('#') else {
        return Err(TokenError::Color {
            scheme: scheme.into(),
            value: value.into(),
        });
    };
    if value.len() != 6 {
        return Err(TokenError::Color {
            scheme: scheme.into(),
            value: format!("#{value}"),
        });
    }
    let parsed = |range| {
        u8::from_str_radix(&value[range], 16).map_err(|_| TokenError::Color {
            scheme: scheme.into(),
            value: format!("#{value}"),
        })
    };
    Ok((parsed(0..2)?, parsed(2..4)?, parsed(4..6)?))
}
fn write_if_changed(path: &Path, content: &str) -> Result<(), TokenError> {
    if std::fs::read_to_string(path).is_ok_and(|existing| existing == content) {
        return Ok(());
    }
    std::fs::write(path, content).map_err(|source| TokenError::Write {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn invalid_hex_is_rejected() {
        assert!(parse_hex("light", "#XYZ123").is_err());
    }
}
