//! Emit the tiny shared setup-brand fragment with the existing asset integrity boundary.
//! Invoked by tools/export-brand.py; runtime pack/game ownership remains with the host.

use std::{env, fmt::Write, fs};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let paths: Vec<_> = env::args_os().skip(1).collect();
    if paths.len() != 2 {
        return Err(
            "usage: brand_manifest <native-mark-mask.png> <native-wordmark-mask.png>".into(),
        );
    }
    let mut fragment = String::from(
        "# Generated by tools/export-brand.py and xtask/examples/brand_manifest.rs.\n",
    );
    for (path, stem) in paths.iter().zip(["mark", "wordmark"]) {
        let bytes = fs::read(path)?;
        let hash = blake3::hash(&bytes).to_hex();
        writeln!(
            fragment,
            "\n[[files]]\nname = \"brand-{stem}-mask.png\"\n\
             path = \"brand/1.0.0/native-{stem}-mask.b3-{hash}.png\"\n\
             hash = \"{hash}\"\nbytes = {}\npriority = \"critical\"",
            bytes.len()
        )?;
    }
    for stem in ["mark", "wordmark"] {
        writeln!(
            fragment,
            "\n[[resources]]\nid = \"brand/{stem}\"\n\n\
             [[resources.variants]]\nfile = \"brand-{stem}-mask.png\""
        )?;
    }
    // Verify the generated fragment with the same validated manifest as the runtime.
    let manifest = tabula_assets::AssetPackManifest::from_toml(&format!(
        "pack = \"brand\"\nversion = \"1.0.0\"\ngame = \"com.tabula.brand\"\n{fragment}"
    ))?;
    for (file, path) in manifest.files().iter().zip(&paths) {
        let bytes = fs::read(path)?;
        file.verify_bytes(&bytes)?;
    }
    print!("{fragment}");
    Ok(())
}
