#!/usr/bin/env python3
"""Export approved T Portal sources into existing Tabula targets (issue #91).

SVGs in assets/brand are canonical. Inkscape 1.4 rasterizes vectors at each target
size; no raster is enlarged and native launcher artwork has no baked OS mask.
Requires Python Pillow and Inkscape 1.4; adds no runtime dependency.
"""
from __future__ import annotations
import argparse
from io import BytesIO
import json
from pathlib import Path
import re
import hashlib
import xml.etree.ElementTree as ET
from PIL import Image
import os
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
BRAND = ROOT / "assets/brand"
NS = {"s": "http://www.w3.org/2000/svg"}
PIN = "ae40d8efda28c141127116b3342d80843aba4185"


def source(name):
    return (BRAND / name).read_text()


def path(name):
    return ET.fromstring(source(name)).find("s:path", NS).attrib["d"]


def lockup():
    # Preserve the handed-over viewBox, geometry and placement. Only presentation
    # attributes change: one accessible name belongs to the surrounding consumer.
    svg = source("tabula-lockup-light.svg")
    svg = re.sub(r' role="img" aria-labelledby="title"', ' class="brand-lockup" aria-hidden="true" focusable="false"', svg)
    svg = re.sub(r'<title[^>]*>.*?</title>', '', svg)
    svg = svg.replace('fill="#7C63ED"', 'fill="var(--sys-color-brand-mark)"', 1)
    return svg.replace('fill="#7C63ED"', 'fill="var(--sys-color-brand-wordmark)"') + "\n"


def outputs(render, write):
    result = {}
    def put(relative, value):
        result[relative] = value.encode() if isinstance(value, str) else value
    palette = json.loads(source("palette.json"))
    colors = palette["brand"]
    put("assets/brand/generated/tabula-lockup.svg", lockup())
    for name in ("index.html", "werewolf.html", "play.html", "werewolf-play.html"):
        relative=f"apps/game-client/web/{name}"
        original=(ROOT/relative).read_text()
        pattern=r"<!-- tabula-brand:start -->.*?<!-- tabula-brand:end -->"
        if len(re.findall(pattern, original, re.S)) != 1:
            raise ValueError(f"expected exactly one canonical brand slot: {relative}")
        updated=re.sub(pattern, "<!-- tabula-brand:start -->"+lockup().strip()+"<!-- tabula-brand:end -->", original, flags=re.S)
        put(relative, updated)
    micro = source("tabula-mark-micro.svg").replace('fill="#7C63ED"', 'fill="currentColor"')
    put("assets/brand/generated/tabula-mark-micro-mono.svg", micro)
    word = ET.fromstring(source("tabula-lockup-light.svg")).find("s:g", NS)
    word_path = word.find("s:path", NS).attrib["d"]
    kt = '''// @generated by python3 tools/export-brand.py; do not edit.
package com.loveoverflow.tabula.mobile.design

/** Canonical T Portal vector geometry, independent of theme and installed fonts. */
internal object TabulaBrandPaths {
    const val MarkViewport = 256f
    const val LockupWidth = 705.276f
    const val LockupHeight = 256f
    const val WordmarkX = 294f
    const val WordmarkY = 77f
    const val Mark = "%s"
    const val MicroMark = "%s"
    const val Wordmark = "%s"
}
''' % (path("tabula-mark-mono.svg"), path("tabula-mark-micro.svg"), word_path)
    put("apps/mobile/shared/src/commonMain/kotlin/com/loveoverflow/tabula/mobile/design/TabulaBrandPaths.kt", kt)
    primary = source("tabula-mark-primary.svg")
    app = source("tabula-app-icon.svg")
    foreground = re.sub(r'<rect[^>]*/>', '', app)
    # Android scales a108dp foreground behind its72dp viewport. Fit the entire
    # essential mark inside the66dp safe circle, not the artwork square.
    foreground = foreground.replace('translate(38.4 38.4) scale(.7)', 'translate(64 64) scale(.5)')
    # Adaptive favicon uses the micro outline because browsers routinely display
    # it at 16/24px. Unlike a launcher, it is transparent and follows contrast.
    favicon = micro.replace(' role="img" aria-labelledby="title"', '').replace('<title id="title">Tabula — optical mark for 16–24 px</title>', '')
    favicon = favicon.replace('<path', '<style>svg{color:%s}@media(prefers-color-scheme:dark){svg{color:%s}}@media(prefers-contrast:more){svg{color:black}}@media(prefers-contrast:more) and (prefers-color-scheme:dark){svg{color:white}}</style><path' % (colors["brandPrimary"], colors["brandLavender"]))
    for web in ("assets/brand/web", "apps/game-client/web/brand"):
        put(f"{web}/favicon.svg", favicon)
        rasters = {}
        for size in (16, 24, 32, 48, 64):
            svg = source("tabula-mark-micro.svg") if size <= 24 else primary
            rasters[size] = render(svg, size)
            put(f"{web}/mark-{size}.png", rasters[size])
        ico = BytesIO()
        Image.open(BytesIO(rasters[48])).save(ico, format="ICO", sizes=[(16,16),(32,32),(48,48)], append_images=[Image.open(BytesIO(rasters[16])),Image.open(BytesIO(rasters[32]))])
        put(f"{web}/favicon.ico", ico.getvalue())
        for size in (180, 192, 512):
            put(f"{web}/app-icon-{size}.png", render(app, size))
        manifest = {"name":"Tabula", "short_name":"Tabula", "start_url":"../", "scope":"../", "display":"standalone", "background_color": colors["brandSurface"], "theme_color":colors["brandInk"], "icons":[{"src":f"app-icon-{size}.png", "sizes":f"{size}x{size}", "type":"image/png", "purpose":"any maskable"} for size in (192,512)]}
        put(f"{web}/manifest.webmanifest", json.dumps(manifest, indent=2) + "\n")
    # Native setup uses white alpha masks tinted by the exact semantic roles,
    # through its existing verified Sprite pipeline rather than a font label.
    native_mark=render(source("tabula-mark-white.svg"),256)
    native_word=render(re.sub(r'fill="[^"]+"', 'fill="white"',source("tabula-wordmark.svg")),1024,262)
    put("assets/brand/generated/native-mark-mask.png",native_mark)
    put("assets/brand/generated/native-wordmark-mask.png",native_word)
    if write:
        # First export bootstraps include_bytes! consumers before compiling the
        # existing xtask example that derives the verified manifest fragment.
        for relative,data in (("assets/brand/generated/native-mark-mask.png",native_mark),("assets/brand/generated/native-wordmark-mask.png",native_word)):
            (ROOT/relative).parent.mkdir(parents=True,exist_ok=True)
            (ROOT/relative).write_bytes(data)
        fragment_path=BRAND/"generated/native-setup.pack.fragment.toml"
        if not fragment_path.exists():fragment_path.write_text("# initial export bootstrap\n")
    with tempfile.TemporaryDirectory(prefix="tabula-brand-manifest-") as temp:
        temp=Path(temp)
        mark=temp/"native-mark-mask.png";word=temp/"native-wordmark-mask.png"
        mark.write_bytes(native_mark);word.write_bytes(native_word)
        fragment=subprocess.check_output(["cargo","run","--offline","--quiet","-p","xtask","--example","brand_manifest","--",str(mark),str(word)],cwd=ROOT)
    put("assets/brand/generated/native-setup.pack.fragment.toml",fragment)
    # Miniquad wants decoded RGBA arrays, not PNG. At 16px use the micro outline.
    for size in (16,32,64):
        svg = app
        if size == 16:
            svg = app.replace(path("tabula-mark-mono.svg"), path("tabula-mark-micro.svg"))
        im = Image.open(BytesIO(render(svg, size))).convert("RGBA")
        put(f"assets/brand/generated/native-icon-{size}.rgba", im.tobytes())
    for density, size in (("mdpi",48),("hdpi",72),("xhdpi",96),("xxhdpi",144),("xxxhdpi",192)):
        put(f"apps/mobile/android/src/main/res/mipmap-{density}/ic_launcher.png", render(app,size))
        adaptive_size = size * 108 // 48
        put(f"apps/mobile/android/src/main/res/mipmap-{density}/ic_launcher_foreground.png", render(foreground, adaptive_size))
    put("apps/mobile/android/src/main/res/values/brand_colors.xml", f'<?xml version="1.0" encoding="utf-8"?>\n<!-- @generated from assets/brand/palette.json; do not edit. -->\n<resources><color name="tabula_brand_ink">{colors["brandInk"]}</color></resources>\n')
    catalog = "apps/mobile/ios/TabulaApp/Assets.xcassets"
    put(f"{catalog}/Contents.json", json.dumps({"info":{"author":"xcode","version":1}}, indent=2)+"\n")
    specifications = [("iphone","20x20",2),("iphone","20x20",3),("iphone","29x29",2),("iphone","29x29",3),("iphone","40x40",2),("iphone","40x40",3),("iphone","60x60",2),("iphone","60x60",3),("ipad","20x20",1),("ipad","20x20",2),("ipad","29x29",1),("ipad","29x29",2),("ipad","40x40",1),("ipad","40x40",2),("ipad","76x76",1),("ipad","76x76",2),("ipad","83.5x83.5",2),("ios-marketing","1024x1024",1)]
    images=[]
    for idiom, pts, scale in specifications:
        size=round(float(pts.split("x")[0])*scale)
        name=f"icon-{size}.png"
        # Apple app icons must be opaque RGB, square and unmasked.
        im=Image.open(BytesIO(render(app,size))).convert("RGB")
        buf=BytesIO(); im.save(buf,format="PNG")
        put(f"{catalog}/AppIcon.appiconset/{name}",buf.getvalue())
        images.append({"idiom":idiom,"size":pts,"scale":f"{scale}x","filename":name})
    put(f"{catalog}/AppIcon.appiconset/Contents.json",json.dumps({"images":images,"info":{"author":"xcode","version":1}},indent=2)+"\n")
    provenance={"source_commit":PIN,"source":"https://github.com/loveoverflowcom/tabula/tree/"+PIN+"/docs/ui/tabula-logo-lavender","canonical_sha256":{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(BRAND.glob('*.svg'))},"palette_sha256":hashlib.sha256((BRAND/'palette.json').read_bytes()).hexdigest(),"outputs":{p:hashlib.sha256(v).hexdigest() for p,v in sorted(result.items())}}
    put("assets/brand/generated/exports.json",json.dumps(provenance,indent=2)+"\n")
    return result


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check",action="store_true",help="rasterize and compare every committed output without writing")
    args=parser.parse_args()
    cache={}
    with tempfile.TemporaryDirectory(prefix="tabula-brand-") as temp:
        temp=Path(temp)
        env={**os.environ,"INKSCAPE_PROFILE_DIR":str(temp/"profile"),"XDG_CACHE_HOME":str(temp/"cache")}
        def render(svg,size,height=None):
            height=size if height is None else height
            key=(svg,size,height)
            if key not in cache:
                input_file=temp/"source.svg"; output_file=temp/"export.png"
                input_file.write_text(svg)
                subprocess.run(["inkscape",str(input_file),"--export-type=png",f"--export-width={size}",f"--export-height={height}",f"--export-filename={output_file}"],env=env,check=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
                # Normalize metadata/encoding so freshness depends only on pixels.
                im=Image.open(output_file).convert("RGBA")
                buf=BytesIO(); im.save(buf,format="PNG",compress_level=9)
                cache[key]=buf.getvalue()
            return cache[key]
        expected=outputs(render, not args.check)
    stale=[]
    for relative,data in expected.items():
        target=ROOT/relative
        if args.check:
            if not target.exists() or target.read_bytes()!=data:stale.append(relative)
        else:
            target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(data)
    if stale:raise SystemExit("stale brand exports:\n"+"\n".join(stale))
    print(f"PASS: {len(expected)} canonical brand exports {'fresh' if args.check else 'written'}; vectors rasterized at native target dimensions")


if __name__=="__main__":main()
