"""Build per-age D05 runtime pack sources from the private delivery archives.

Inputs are owner-private: the delivery index and its archives stay outside Git.
Outputs are staged pack sources (one directory per pack, each with an
`xtask pack-assets --external` source manifest), a private runtime manifest and
a private build/QA report. Nothing here is gameplay: clip markers and sockets
are presentation facts with `authority: false`; canonical combat stays with the
future rules owner (doc 00 I-10).

Memory: one delivered atlas page (plus its mask page) is decoded at a time.
The all-age delivered colour+mask bake is about 2.375 GiB decoded and is never
loaded together.
"""
from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import hashlib
import io
import json
from pathlib import Path
import resource
import shutil
import subprocess
import sys
import time
import zipfile

from PIL import Image
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import packing  # noqa: E402
import verify_inputs  # noqa: E402

AGES = ('Primitive', 'Ancient', 'Feudal', 'Arcane', 'Industrial', 'Future')
GAME_ID = 'com.tabula.agewar'  # GameId grammar has no '-'; provisional, unregistered
BAKE_SCALE = 0.5          # delivered bake canvas 384x320 = authored 768x640 x 0.5
BAKE_HZ = 24
D2_MIN_TEXELS_PER_LU = 1.33  # declare density 2 only where it adds real detail
GROUND_ALPHA = 16
STAGE_LU = (1920, 698)    # D03 stage, logical units at desktop reference scale
CLIPS_FORMAT = 'age-war-d05-clips v1'
LOCOMOTION_CLIPS = ('walk', 'run', 'charge_run')
IMPACT_RECIPE = {'Physical': 'impact_physical', 'Arcane': 'impact_arcane', 'Siege': 'impact_siege'}
VFX_FORMAT = 'age-war-d05-vfx v1'


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def pack_name(age: str | None) -> str:
    return f'age-war-{age.lower()}' if age else 'age-war-common'


def archive(inputs: Path, name: str) -> zipfile.ZipFile:
    return zipfile.ZipFile(inputs / name)


def fmt(value: float) -> str:
    text = f'{value:.3f}'.rstrip('0').rstrip('.')
    return '0' if text in ('-0', '') else text


class Stage:
    """One staged pack source directory with its pack.source.toml declarations."""

    def __init__(self, root: Path, pack: str):
        self.root = root / pack
        if self.root.exists():
            shutil.rmtree(self.root)
        self.root.mkdir(parents=True)
        self.pack = pack
        self.files: list[dict] = []
        self.resources: dict[str, list[dict]] = defaultdict(list)
        self.decoded: Counter = Counter()
        self.groups: dict = defaultdict(Counter)

    def add_file(self, name: str, source: str, data: bytes, priority: str,
                 density: int | None = None, decoded_rgba8: int = 0) -> None:
        path = self.root / source
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        entry = {'name': name, 'source': source, 'priority': priority}
        if density is not None:
            entry['density'] = density
        self.files.append(entry)
        self.decoded[f'density{density}' if density else 'any'] += decoded_rgba8

    def add_variant(self, resource_id: str, file: str, region=None) -> None:
        variant = {'file': file}
        if region is not None:
            variant['region'] = region
        self.resources[resource_id].append(variant)

    def write_manifest(self) -> None:
        lines = ['# Generated by games/age-war/design-tools/runtime/build_runtime_packs.py.',
                 '# Private staged source; seal with cargo xtask pack-assets --external.', '']
        for entry in self.files:
            lines += ['[[files]]', f'name = "{entry["name"]}"', f'source = "{entry["source"]}"',
                      f'priority = "{entry["priority"]}"']
            if 'density' in entry:
                lines.append(f'density = {entry["density"]}')
            lines.append('')
        for resource_id in sorted(self.resources):
            lines += ['[[resources]]', f'id = "{resource_id}"']
            for variant in self.resources[resource_id]:
                lines += ['[[resources.variants]]', f'file = "{variant["file"]}"']
                if 'region' in variant:
                    x, y, w, h = variant['region']
                    lines.append(f'region = {{ x = {x}, y = {y}, width = {w}, height = {h} }}')
            lines.append('')
        (self.root / 'pack.source.toml').write_text('\n'.join(lines))


def reconstruct_clip_index(inputs: Path, rc_names: dict[str, str]) -> tuple[list, str]:
    union = []
    for age in AGES:
        with archive(inputs, rc_names[age]) as rc:
            union += json.loads(rc.read(f'manifest/ages/{age}/runtime-clip-index-reconstructed-v05.json'))
    return union, sha256(json.dumps(union, indent=2).encode())


def check_clip_timing(clip: dict) -> list[str]:
    """The bake is a 24 Hz grid plus exact key times (markers, end pose).

    Every gap is at most one 24 Hz step, every marker has an exact pose, and a
    one-shot clip ends on its final pose at `duration_ms`.
    """
    issues = []
    meta, frames = clip['clip'], clip['frames']
    duration = meta['duration_ms']
    times = [f['time_ms'] for f in frames]
    if not frames or times[0] != 0:
        issues.append('first frame not at 0 ms')
    if any(b <= a for a, b in zip(times, times[1:])):
        issues.append('frame times not strictly increasing')
    if any((b - a) > 1000 / BAKE_HZ + 0.01 for a, b in zip(times, times[1:])):
        issues.append('gap longer than one 24 Hz step')
    if times and times[-1] > duration:
        issues.append('frame beyond clip duration')
    if times and not meta['loop'] and abs(times[-1] - duration) > 0.01:
        issues.append('one-shot clip lacks its final pose at duration')
    for marker in meta.get('markers', []):
        if not 0 <= marker['time_ms'] <= duration or marker.get('authority') is not False:
            issues.append(f'invalid marker {marker}')
        elif not any(abs(t - marker['time_ms']) <= 0.01 for t in times):
            issues.append(f'no exact pose at marker {marker["time_ms"]}')
    if 'windup_ms' in meta and not 0 <= meta['windup_ms'] <= duration:
        issues.append('windup outside clip')
    return issues


def planted_foot_speed(clip: dict) -> tuple[float, float, int]:
    """Ground speed implied by planted feet, and the worst residual slide.

    A foot on the ground line (within 0.5 bake px) in two consecutive frames
    must move backwards exactly as far as the body moves forwards. Returns the
    median implied speed (bake px/s, + = screen right), the largest deviation
    from it over one cycle (bake px per frame step) and the sample count.
    """
    ground = clip['pivot'][1] - 0.5
    samples = []
    frames = clip['frames']
    for before, after in zip(frames, frames[1:]):
        dt = (after['time_ms'] - before['time_ms']) / 1000
        for foot_a, foot_b in zip(before['sockets_original'].get('feet', []),
                                  after['sockets_original'].get('feet', [])):
            if foot_a[1] >= ground and foot_b[1] >= ground and dt > 0:
                samples.append((-(foot_b[0] - foot_a[0]) / dt, foot_b[0] - foot_a[0], dt))
    if not samples:
        return 0.0, 0.0, 0
    speed = float(np.median([v for v, _, _ in samples]))
    residual = max(abs(dx + speed * dt) for _, dx, dt in samples)
    return speed, residual, len(samples)


def unit_scales(rig: dict) -> tuple[float, float]:
    """Logical units per bake pixel (k) and density-1 texture scale (t <= 1)."""
    bake_body = rig['measured_idle_alpha16_body_height_author_px'] * BAKE_SCALE
    k = rig['display_body_height_desktop_px'] / bake_body
    return k, min(1.0, k)


def build_age(age: str, inputs: Path, names: dict, rigs: dict, audio: list, audio_zip: zipfile.ZipFile,
              stage_root: Path, context: dict) -> tuple[Stage, dict, dict]:
    started = time.monotonic()
    stage = Stage(stage_root, pack_name(age))
    report = {'age': age, 'checks': Counter(), 'failures': defaultdict(list), 'ground': {}, 'locomotion': {}}
    rc = archive(inputs, names['rc'][age])
    clips = json.loads(rc.read(f'manifest/ages/{age}/runtime-clip-index-reconstructed-v05.json'))
    atlas = json.loads(rc.read(f'manifest/ages/{age}/atlas-index-reconstructed-v05.json'))

    def check(name: str, ok: bool, detail=None) -> None:
        report['checks'][f'{name}:{"pass" if ok else "fail"}'] += 1
        if not ok and len(report['failures'][name]) < 20:
            report['failures'][name].append(detail)

    # Clip-level structure, timing and facing parity.
    by_unit = defaultdict(lambda: defaultdict(dict))
    for clip in clips:
        by_unit[clip['unit_id']][clip['facing']][clip['clip']['id']] = clip
        issues = check_clip_timing(clip)
        check('clip_timing', not issues, f"{clip['unit_id']}/{clip['facing']}/{clip['clip']['id']}: {issues}")
        check('bake_hz', clip['bake_hz'] == BAKE_HZ, clip['unit_id'])
        check('marker_authority_false', clip['marker_authority'] is False, clip['unit_id'])
        check('canvas_pivot', clip['canvas'] == [384, 320] and clip['pivot'] == [192, 228], clip['unit_id'])
    for unit, facings in by_unit.items():
        check('two_facings', set(facings) == {'right', 'left'}, unit)
        right, left = facings.get('right', {}), facings.get('left', {})
        check('facing_clip_parity', set(right) == set(left), unit)
        for clip_id in set(right) & set(left):
            check('facing_frame_parity', len(right[clip_id]['frames']) == len(left[clip_id]['frames']),
                  f'{unit}/{clip_id}')
        for required in ('idle', 'attack', 'hit', 'death'):
            check('required_clip', required in right and required in left, f'{unit}/{required}')
        check('required_locomotion', bool({'walk', 'run'} & set(right)), unit)

    # Frame records keyed for atlas cross-checking.
    frames_by_page = defaultdict(list)
    for clip in clips:
        for index, frame in enumerate(clip['frames']):
            frames_by_page[frame['atlas_path']].append((clip, index, frame))
            x0, y0, x1, y1 = frame['trim_source_xyxy']
            w, h = frame['rect_xywh'][2:]
            check('trim_matches_rect', (x1 - x0, y1 - y0) == (w, h), frame['atlas_path'])
            check('pivot_trim', frame['pivot_trim'] == [clip['pivot'][0] - x0, clip['pivot'][1] - y0],
                  f"{clip['unit_id']}/{clip['clip']['id']}/{index}")

    d1_color, d2_color, d2_mask, d1_mask, frame_rows = {}, {}, {}, {}, []
    page_bytes_total = 0
    for page_number, page in enumerate(atlas['pages']):
        color_bytes, mask_bytes = rc.read(page['path']), rc.read(page['faction_mask_path'])
        check('page_sha256', sha256(color_bytes) == page['sha256'], page['path'])
        check('mask_page_sha256', sha256(mask_bytes) == page['faction_mask_sha256'], page['faction_mask_path'])
        page_bytes_total += len(color_bytes)
        color = Image.open(io.BytesIO(color_bytes)).convert('RGBA')
        mask = Image.open(io.BytesIO(mask_bytes)).convert('RGBA')
        check('page_size', color.size == mask.size == (page['width'], page['height']), page['path'])
        members = {(m['unit_id'], m['facing'], m['clip_id'], m['time_ms']): m['rect_xywh'] for m in page['members']}
        records = frames_by_page.pop(page['path'], [])
        check('atlas_member_count', len(members) == len(records), page['path'])
        occupied = np.zeros((color.height, color.width), dtype=bool)
        for clip, index, frame in records:
            unit, facing, clip_id = clip['unit_id'], clip['facing'], clip['clip']['id']
            x, y, w, h = frame['rect_xywh']
            key = (unit, facing, clip_id, frame['time_ms'])
            check('atlas_member_rect', members.get(key) == [x, y, w, h], key)
            check('rect_in_page', x >= 2 and y >= 2 and x + w + 2 <= color.width and y + h + 2 <= color.height, key)
            ring = occupied[y - 2:y + h + 2, x - 2:x + w + 2]
            check('no_overlap', not ring.any(), key)
            ring[:] = True
            check('color_extrusion', packing.extrusion_matches(color, x, y, w, h), key)
            check('mask_extrusion', packing.extrusion_matches(mask, x, y, w, h), key)
            color_crop, mask_crop = color.crop((x, y, x + w, y + h)), mask.crop((x, y, x + w, y + h))
            ca, ma = np.asarray(color_crop.getchannel('A')), np.asarray(mask_crop.getchannel('A'))
            check('mask_alpha_subset', int((ma > ca).sum()) == 0, key)
            rows = np.nonzero((ca >= GROUND_ALPHA).any(axis=1))[0]
            bottom = frame['trim_source_xyxy'][1] + int(rows[-1]) + 1 if rows.size else None
            penetration = None if bottom is None else bottom - clip['pivot'][1]
            report['ground'].setdefault(clip_id, []).append(penetration)
            check('ground_penetration_le_1px', penetration is not None and penetration <= 1,
                  (key, penetration))
            k, t = unit_scales(rigs[unit])
            d1 = color_crop if t >= 1 else packing.premultiplied_resize(color_crop, packing.scaled_size(w, h, t))
            d1_color[(unit, facing, clip_id, index)] = d1
            if 1 / k >= D2_MIN_TEXELS_PER_LU:
                d2_color[(unit, facing, clip_id, index)] = color_crop
            shaded = packing.shaded_mask(color_crop, mask_crop)
            bbox = packing.alpha_bbox(shaded)
            mask_lu = None
            if bbox:
                bx0, by0, bx1, by1 = bbox
                d2m = shaded.crop(bbox)
                d2_mask[(unit, facing, clip_id, index)] = d2m
                d1_mask[(unit, facing, clip_id, index)] = d2m if t >= 1 else packing.premultiplied_resize(
                    d2m, packing.scaled_size(bx1 - bx0, by1 - by0, t))
                tx0, ty0 = frame['trim_source_xyxy'][:2]
                mask_lu = [(tx0 + bx0 - clip['pivot'][0]) * k, (ty0 + by0 - clip['pivot'][1]) * k,
                           (bx1 - bx0) * k, (by1 - by0) * k]
            frame_rows.append((clip, index, frame, k, t, (page_number, x, y, w, h), mask_lu))
        del color, mask
    check('all_frames_on_declared_pages', not frames_by_page, list(frames_by_page)[:3])

    # Repack every atlas per (unit, facing): a side only ever shows one facing
    # of a unit, so the loader can fetch exactly the groups on the field.
    def pack_images(images: dict, kind: str, density: int) -> dict:
        regions = {}
        groups = defaultdict(dict)
        for key, image in images.items():
            groups[key[:2]][key] = image
        for (unit, facing), group in sorted(groups.items()):
            placements, pages = packing.shelf_pack([(key, im.width, im.height) for key, im in group.items()])
            canvases = [Image.new('RGBA', size, (0, 0, 0, 0)) for size in pages]
            for place in placements:
                packing.paste_extruded(canvases[place.page], group[place.key], place.x, place.y)
            for place in placements:
                check(f'd{density}_{kind}_extrusion', packing.extrusion_matches(
                    canvases[place.page], place.x, place.y, place.width, place.height), place.key)
                if density == 2 and kind == 'color':
                    exact = np.array_equal(np.asarray(canvases[place.page].crop(
                        (place.x, place.y, place.x + place.width, place.y + place.height))),
                        np.asarray(group[place.key]))
                    check('d2_color_pixel_exact_to_delivery', exact, place.key)
            for number, canvas in enumerate(canvases):
                name = f'd{density}-{kind}-{unit}-{facing}-{number}.png'
                stage.add_file(name, f'd{density}/{kind}/{unit}-{facing}-{number}.png',
                               packing.png_bytes(canvas), 'high', density, canvas.width * canvas.height * 4)
                stage.groups[(unit, facing)][f'd{density}'] += canvas.width * canvas.height * 4
            for place in placements:
                regions[place.key] = (f'd{density}-{kind}-{unit}-{facing}-{place.page}.png',
                                      place.x, place.y, place.width, place.height)
        return regions

    d1_regions = pack_images(d1_color, 'color', 1)
    d1_mask_regions = pack_images(d1_mask, 'mask', 1)
    d2_regions = pack_images(d2_color, 'color', 2)
    d2_mask_regions = pack_images(d2_mask, 'mask', 2)
    del d1_color, d1_mask, d2_color, d2_mask

    # Resources and the integrity-protected clip sidecar.
    lines = [f'# {CLIPS_FORMAT}. Presentation facts only: markers and sockets never decide combat.',
             f'pack\t{stage.pack}\t{age}\t{BAKE_HZ}']
    for unit in sorted(by_unit, key=lambda u: list(rigs).index(u)):
        rig = rigs[unit]
        k, t = unit_scales(rig)
        lines.append('\t'.join(['unit', unit, age, rig['role'], rig['presentation_hint'],
                                str(rig['display_body_height_desktop_px']), fmt(k), fmt(t),
                                rig['weapon_kind'], ','.join(rig['skills']),
                                context['weapons'][unit]['vfx_recipe'],
                                IMPACT_RECIPE[rig['d01_attack']['kind']]]))
    clip_counts = Counter()
    for clip in clips:
        meta = clip['clip']
        lines.append('\t'.join(['clip', clip['unit_id'], clip['facing'], meta['id'], meta.get('skill_id', '-'),
                                fmt(meta['duration_ms']), '1' if meta['loop'] else '0',
                                fmt(meta['windup_ms']) if 'windup_ms' in meta else '-', str(len(clip['frames']))]))
        clip_counts[meta['id']] += 1
        for marker in meta.get('markers', []):
            lines.append('\t'.join(['marker', clip['unit_id'], clip['facing'], meta['id'], fmt(marker['time_ms']),
                                    marker['kind'], marker.get('cue_id', '-')]))
        if meta['id'] in LOCOMOTION_CLIPS:
            k, _ = unit_scales(rigs[clip['unit_id']])
            speed, residual, pairs = planted_foot_speed(clip)
            report['locomotion'][f"{clip['unit_id']}/{clip['facing']}/{meta['id']}"] = {
                'speed_lu_per_s': round(speed * k, 3), 'max_slide_lu': round(residual * k, 3),
                'max_slide_bake_px': round(residual, 3), 'planted_pairs': pairs}
            check('planted_foot_pairs', pairs > 0, f"{clip['unit_id']}/{clip['facing']}/{meta['id']}")
            lines.append('\t'.join(['loco', clip['unit_id'], clip['facing'], meta['id'],
                                    fmt(speed * k), fmt(residual * k)]))
    for clip, index, frame, k, t, (page_number, x, y, w, h), mask_lu in frame_rows:
        unit, facing, clip_id = clip['unit_id'], clip['facing'], clip['clip']['id']
        key = (unit, facing, clip_id, index)
        rid = f'unit/{unit}/{facing}/{clip_id}/{index:03d}'
        file, *region = d1_regions[key]
        stage.add_variant(rid, file, tuple(region))
        if key in d2_regions:
            file, *region = d2_regions[key]
            stage.add_variant(rid, file, tuple(region))
        if mask_lu:
            mid = f'mask/{unit}/{facing}/{clip_id}/{index:03d}'
            file, *region = d1_mask_regions[key]
            stage.add_variant(mid, file, tuple(region))
            if key in d2_regions:
                file, *region = d2_mask_regions[key]
                stage.add_variant(mid, file, tuple(region))
        tx0, ty0 = frame['trim_source_xyxy'][:2]
        px, py = clip['pivot']
        sockets = frame['sockets_original']

        def rel(point):
            return [fmt((point[0] - px) * k), fmt((point[1] - py) * k)] if point else ['-', '-']
        lines.append('\t'.join(
            ['frame', unit, facing, clip_id, str(index), fmt(frame['time_ms']),
             fmt((tx0 - px) * k), fmt((ty0 - py) * k), fmt(w * k), fmt(h * k)]
            + ([fmt(v) for v in mask_lu] if mask_lu else ['-'] * 4)
            + rel(sockets.get('effect')) + rel(sockets.get('muzzle')) + rel(sockets.get('weapon_grip'))))
    clips_tsv = ('\n'.join(lines) + '\n').encode()
    stage.add_file('clips.tsv', 'meta/clips.tsv', clips_tsv, 'critical')
    stage.add_variant('meta/clips', 'clips.tsv')

    # D03 scene derivative used by the D05 previews (flattened, 0.5 texel/lu).
    with archive(inputs, names['preview'][age]) as preview:
        scene = preview.read(f'source/motion-input/scenes/{age}.png')
    scene_size = Image.open(io.BytesIO(scene)).size
    stage.add_file('scene.png', 'scene/backdrop.png', scene, 'critical', None, scene_size[0] * scene_size[1] * 4)
    stage.add_variant('scene/backdrop', 'scene.png')

    # The renderer cache binds one pack at a time, so each age pack carries the
    # baked VFX references its units and spells can cue (a common-pack-only
    # design would need multi-pack residency; recorded as a D06 contract gap).
    recipes = {'impact_physical', 'impact_arcane', 'impact_siege'}
    for unit in by_unit:
        recipes |= {context['weapons'][unit]['vfx_recipe'], *rigs[unit]['skills']}
        if 'summon' in rigs[unit]['skills']:
            recipes |= {'drone_spawn', 'drone_expire'}
    recipes |= {r['id'] for r in context['recipes'] if r['kind'] == 'spell' and r['age'] == age}
    report['vfx_recipes'] = add_vfx_sheets(stage, context['vfx_zip'], context['vfx_index'], recipes)

    # Age-owned audio: commander spells, ambience/motif loops and turret attacks.
    age_audio = [a for a in audio if a['group'] in (f'commander/{age}', f'ambience/{age}', f'auxiliary/{age}')]
    for asset in age_audio:
        data = audio_zip.read(asset['ogg'])
        stage.add_file(f'sfx-{asset["id"]}.ogg', f'sfx/{asset["id"]}.ogg', data,
                       'low' if asset['group'].startswith('ambience') else 'high')
        stage.add_variant(f'sfx/{asset["id"]}', f'sfx-{asset["id"]}.ogg')
    stage.write_manifest()
    rc.close()

    report['checks'] = dict(sorted(report['checks'].items()))
    report['failures'] = dict(report['failures'])
    report['ground'] = {cid: {'max_penetration_px': max(v for v in vals if v is not None),
                              'min_bottom_offset_px': min(v for v in vals if v is not None),
                              'frames': len(vals)} for cid, vals in sorted(report['ground'].items())}
    report.update(clips=len(clips), frames=len(frame_rows), units=len(by_unit), clip_ids=dict(clip_counts),
                  delivered_page_bytes=page_bytes_total, decoded_rgba8=dict(stage.decoded),
                  decoded_rgba8_by_unit_facing={f'{u}/{f}': dict(v) for (u, f), v in sorted(stage.groups.items())},
                  staged_files=len(stage.files), resources=len(stage.resources),
                  seconds=round(time.monotonic() - started, 1))
    return stage, report, {'clips': clips, 'audio': [a['id'] for a in age_audio]}


def add_vfx_sheets(stage: Stage, vfx: zipfile.ZipFile, index: list, ids: set[str] | None) -> list[str]:
    """Copies delivered two-team VFX sheets (hash-checked) plus a frame sidecar."""
    lines = [f'# {VFX_FORMAT}. Baked two-team design references; no hit authority.']
    selected = [sheet for sheet in index if ids is None or sheet['id'] in ids]
    missing = sorted((ids or set()) - {sheet['id'] for sheet in index})
    if missing:
        raise SystemExit(f'VFX sheets not delivered: {missing}')
    for sheet in selected:
        data = vfx.read(sheet['path'])
        if sha256(data) != sheet['sha256']:
            raise SystemExit(f'VFX sheet hash mismatch: {sheet["id"]}')
        name = f'vfx-{sheet["id"]}.png'
        stage.add_file(name, f'vfx/{sheet["id"]}.png', data, 'high', None, sheet['decoded_rgba8_bytes'])
        counters = Counter()
        for frame in sheet['frames']:
            team, phase = frame.get('team', 'any'), frame.get('phase', frame.get('status', 'glyph'))
            ordinal = counters[(team, phase)]
            counters[(team, phase)] += 1
            rid = f'vfx/{sheet["id"]}/{team}/{phase}/{ordinal}'
            stage.add_variant(rid, name, tuple(frame['rect_xywh']))
            pivot = frame.get('pivot', [frame['rect_xywh'][2] // 2, frame['rect_xywh'][3] // 2])
            lines.append('\t'.join(['vfx', sheet['id'], team, phase, str(ordinal), fmt(frame.get('ms', 0)),
                                    str(pivot[0]), str(pivot[1]), str(frame['rect_xywh'][2]),
                                    str(frame['rect_xywh'][3]), frame.get('counts', {}).get('mode', 'full')]))
    data = ('\n'.join(lines) + '\n').encode()
    stage.add_file('vfx.tsv', 'meta/vfx.tsv', data, 'critical')
    stage.add_variant('meta/vfx', 'vfx.tsv')
    return [sheet['id'] for sheet in selected]


def build_common(inputs: Path, names: dict, audio: list, audio_zip: zipfile.ZipFile, stage_root: Path,
                 context: dict) -> tuple[Stage, dict]:
    stage = Stage(stage_root, pack_name(None))
    index = context['vfx_index']
    add_vfx_sheets(stage, context['vfx_zip'], index, None)
    shared = [a for a in audio if a['group'] in ('skills', 'weapons', 'impacts', 'system', 'auxiliary/Shared')]
    sfx_lines = ['# age-war-d05-sfx v1. Mix intent only; playback never changes outcomes.']
    for asset in audio:
        if asset in shared:
            data = audio_zip.read(asset['ogg'])
            stage.add_file(f'sfx-{asset["id"]}.ogg', f'sfx/{asset["id"]}.ogg', data, 'high')
            stage.add_variant(f'sfx/{asset["id"]}', f'sfx-{asset["id"]}.ogg')
        binding = asset.get('canonical_binding') or {}
        sfx_lines.append('\t'.join(['sfx', asset['id'], asset['group'], asset.get('phase') or '-',
                                    binding.get('id', '-') if isinstance(binding, dict) else '-',
                                    fmt(asset['duration_ms']), '1' if asset['loop'] else '0',
                                    str(asset['priority']), fmt(asset['gain_db']), str(asset['cancel_fade_ms']),
                                    pack_name(None) if asset in shared else
                                    pack_name(asset['group'].split('/')[1])]))
    data = ('\n'.join(sfx_lines) + '\n').encode()
    stage.add_file('sfx.tsv', 'meta/sfx.tsv', data, 'critical')
    stage.add_variant('meta/sfx', 'sfx.tsv')
    stage.write_manifest()
    return stage, {'vfx_sheets': len(index), 'shared_audio': len(shared), 'decoded_rgba8': dict(stage.decoded),
                   'staged_files': len(stage.files), 'resources': len(stage.resources)}


def runtime_manifest(ages: list[str], age_data: dict, rigs: dict, common_dir: Path, audio: list,
                     version: str) -> dict:
    """Private unit/skill -> animation/VFX/SFX/socket/marker/timing contract."""
    recipes = {r['id']: r for r in json.loads((common_dir / 'vfx-recipes-v01.json').read_text())}
    weapons = {w['unit_id']: w for w in json.loads((common_dir / 'weapon-bindings-v01.json').read_text())}
    by_binding = defaultdict(lambda: defaultdict(list))
    for asset in audio:
        binding = asset.get('canonical_binding') or {}
        if isinstance(binding, dict) and binding.get('id'):
            by_binding[binding['id']][asset.get('phase') or 'attack'].append(asset['id'])
    units, spells = [], []
    for age in ages:
        clips = age_data[age]['clips']
        for unit_id in [u for u in rigs if rigs[u]['age'] == age]:
            rig = rigs[unit_id]
            k, t = unit_scales(rig)
            unit_clips = [c for c in clips if c['unit_id'] == unit_id]
            facing_rows = defaultdict(list)
            for clip in unit_clips:
                meta = clip['clip']
                facing_rows[clip['facing']].append({
                    'clip_id': meta['id'], 'skill_id': meta.get('skill_id'), 'duration_ms': meta['duration_ms'],
                    'loop': meta['loop'], 'windup_ms': meta.get('windup_ms'), 'frames': len(clip['frames']),
                    'markers': meta.get('markers', []),
                    'resource_prefix': f'unit/{unit_id}/{clip["facing"]}/{meta["id"]}/',
                    'socket_names': sorted({s for f in clip['frames'] for s in f['sockets_original']}),
                })
            skills = []
            for skill in rig['skills']:
                recipe = recipes.get(skill, {})
                skill_clips = sorted({c['clip']['id'] for c in unit_clips if c['clip'].get('skill_id') == skill})
                skills.append({'skill_id': skill, 'd01': rig['d01_skills'].get(skill),
                               'clips': skill_clips or ['attack (passive on-contact reuse)'],
                               'vfx_recipe': recipe.get('id'), 'vfx_timeline': recipe.get('timeline'),
                               'vfx_modes': {'low': recipe.get('low_effects'), 'reduced': recipe.get('reduced_motion')},
                               'sfx': dict(by_binding.get(skill, {})),
                               'cue_keys': {p: f'age_war.{skill}.{p}' for p in ('activate', 'contact', 'expire', 'audio')}})
            weapon = weapons.get(unit_id, {})
            units.append({
                'unit_id': unit_id, 'age': age, 'role': rig['role'], 'presentation_hint': rig['presentation_hint'],
                'pack': f'{pack_name(age)}@{version}', 'display_body_lu': rig['display_body_height_desktop_px'],
                'lu_per_bake_px': round(k, 6), 'density1_texture_scale': round(t, 6),
                'density2_declared': 1 / k >= D2_MIN_TEXELS_PER_LU,
                'pivot': 'frame-local; resources are drawn relative to the ground pivot (feet)',
                'collider': 'unchanged D01 q footprint; sprite size never changes collision',
                'd01_attack': rig['d01_attack'], 'weapon': {'vfx_recipe': weapon.get('vfx_recipe'),
                                                            'sfx': weapon.get('audio_variations')},
                'clips': dict(facing_rows), 'skills': skills,
            })
        for recipe in recipes.values():
            if recipe['kind'] == 'spell' and recipe['age'] == age:
                spells.append({'spell_id': recipe['id'], 'age': age, 'slot': recipe.get('slot'),
                               'vfx_recipe': recipe['id'], 'timeline': recipe.get('timeline'),
                               'sfx': dict(by_binding.get(recipe['id'], {})),
                               'motion': 'COMMANDER_NO_UNIT_CAST'})
    return {'version': f'age-war-d05-runtime-manifest-{version}', 'authority': False,
            'game': GAME_ID, 'units': units, 'spells': spells,
            'auxiliary': 'Turret/drone vector studies stay PARTIAL and are not packed; turret SFX are packed per age.'}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--index', type=Path, required=True, help='private delivery index JSON')
    parser.add_argument('--inputs', type=Path, required=True, help='directory with the verified archives')
    parser.add_argument('--stage', type=Path, required=True, help='private staged pack sources')
    parser.add_argument('--evidence', type=Path, required=True, help='private report/manifest directory')
    parser.add_argument('--ages', default=','.join(AGES))
    parser.add_argument('--version', default='0.5.0')
    parser.add_argument('--seal', type=Path, help='run cargo xtask pack-assets --external into this root')
    args = parser.parse_args()
    ages = [a for a in args.ages.split(',') if a]
    if not ages or any(a not in AGES for a in ages):
        parser.error(f'ages must be drawn from {AGES}')
    started = time.monotonic()
    verification = verify_inputs.verify(args.index, args.inputs)
    files = {e['file_name']: e for e in verification['entries']}

    def require(name: str) -> str:
        entry = files.get(name)
        if not entry or entry['status'] != 'PASS' or entry.get('archive', {}).get('status') == 'FAIL':
            raise SystemExit(f'required verified input missing or failed: {name}')
        return name
    names = {'common': require('AGEWAR_D05_S03_CommonContracts_Source_reconstructed-v05.zip'),
             'audio': require('AGEWAR_D05_S03_OriginalAudio_reconstructed-v05.zip'),
             'vfx': require('AGEWAR_D05_S03_VFX_AuxiliaryReferences_reconstructed-v05.zip'),
             'rc': {a: require(f'AGEWAR_D05_S04_{a}_RuntimeCandidates_reconstructed-v05.zip') for a in AGES},
             'preview': {a: require(f'AGEWAR_D05_S03_{a}_PreviewInputs_reconstructed-v05.zip') for a in ages}}
    index = json.loads(args.index.read_text())
    union, union_hash = reconstruct_clip_index(args.inputs, names['rc'])
    expected = index['coverage_and_qa']['independent_atlas']['runtime_clip_index_sha256']
    args.evidence.mkdir(parents=True, exist_ok=True)
    contracts = args.evidence / 'contracts'
    contracts.mkdir(exist_ok=True)
    with archive(args.inputs, names['common']) as common:
        rigs = {r['unit_id']: r for r in json.loads(common.read('source/rig-index.json'))}
        for member in ('vfx-recipes-v01.json', 'weapon-bindings-v01.json'):
            (contracts / member).write_bytes(common.read(f'manifest/{member}'))
    audio_zip = archive(args.inputs, names['audio'])
    vfx_zip = archive(args.inputs, names['vfx'])
    context = {'weapons': {w['unit_id']: w for w in json.loads((contracts / 'weapon-bindings-v01.json').read_text())},
               'recipes': json.loads((contracts / 'vfx-recipes-v01.json').read_text()),
               'vfx_zip': vfx_zip, 'vfx_index': json.loads(vfx_zip.read('manifest/vfx-sprite-index-v01.json'))}
    audio = json.loads(audio_zip.read('manifest/audio-index-v01.json'))
    report = {'version': args.version, 'inputs': verification['summary'], 'sourceqa': verification['sourceqa'],
              'complete_clip_index': {'clips': len(union), 'frames': sum(len(c['frames']) for c in union),
                                      'sha256': union_hash, 'expected_sha256': expected,
                                      'status': 'PASS' if union_hash == expected else 'FAIL'},
              'ages': {}, 'common': None}
    age_data = {}
    for age in ages:
        stage, age_report, data = build_age(age, args.inputs, {'rc': names['rc'], 'preview': names['preview']},
                                            rigs, audio, audio_zip, args.stage, context)
        report['ages'][age] = age_report
        age_data[age] = data
        print(json.dumps({'age': age, 'frames': age_report['frames'], 'seconds': age_report['seconds'],
                          'fail': {k: v for k, v in age_report['checks'].items() if k.endswith(':fail')},
                          'decoded': age_report['decoded_rgba8']}), flush=True)
    common_stage, report['common'] = build_common(args.inputs, names, audio, audio_zip, args.stage, context)
    manifest = runtime_manifest(ages, age_data, rigs, contracts, audio, args.version)
    (args.evidence / 'runtime-manifest.json').write_text(json.dumps(manifest, indent=1) + '\n')
    if args.seal:
        repo = Path(__file__).resolve().parents[4]
        for pack in [pack_name(a) for a in ages] + [pack_name(None)]:
            result = subprocess.run(['cargo', 'xtask', 'pack-assets', '--external', str(args.stage / pack),
                                     '--game-id', GAME_ID, '--pack', f'{pack}@{args.version}',
                                     '--out', str(args.seal)], cwd=repo, capture_output=True, text=True)
            report.setdefault('sealed', {})[pack] = {'exit': result.returncode,
                                                     'stdout': result.stdout.strip()[-400:],
                                                     'stderr': result.stderr.strip()[-400:]}
            if result.returncode:
                print(result.stderr, file=sys.stderr)
    usage = resource.getrusage(resource.RUSAGE_SELF)
    report['builder'] = {'seconds': round(time.monotonic() - started, 1),
                         'peak_rss_mib': round(usage.ru_maxrss / 1024, 1),
                         'python': sys.version.split()[0], 'pillow': Image.__version__, 'numpy': np.__version__}
    (args.evidence / 'runtime-build-report.json').write_text(json.dumps(report, indent=1, default=str) + '\n')
    failed = [age for age, r in report['ages'].items() if any(k.endswith(':fail') for k in r['checks'])]
    sealed_failed = [p for p, r in report.get('sealed', {}).items() if r['exit']]
    print(json.dumps({'complete_clip_index': report['complete_clip_index']['status'], 'ages_with_failures': failed,
                      'sealed_failures': sealed_failed, 'builder': report['builder']}))
    return 1 if report['complete_clip_index']['status'] != 'PASS' or sealed_failed else 0


if __name__ == '__main__':
    raise SystemExit(main())
