from pathlib import Path
import json,shutil,zipfile,hashlib,xml.etree.ElementTree as ET,re
from build_designs import Scene,P,PACKS,SCREENS
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'dist';AUDIT='44f6b74e07648abc7191363d7582efc1fceab262';REPO='https://github.com/loveoverflowcom/tabula/blob/'+AUDIT+'/'
DETAILS={
 '01-foundation':{'paths':['tokens.toml','crates/tabula-design/src/lib.rs','xtask/src/tokens_cmd.rs','crates/tabula-presentation/src/focus.rs','apps/web/src/main.rs'],'screens':{'13-settings':'Full preference page: four canonical schemes, system preference, HC, reduced motion, sound, density. In-match settings is a small sheet reusing the same preferences. Account/privacy/storage controls are absent until their adapters exist.','22-design-system':'Design showcase and component contract, not a product settings route. States: default/hover/pressed/disabled/focus/busy/error; explicit target/focus metrics.','23-theme-parity':'Four schemes use exact canonical semantic colors. Same content and layout across schemes; focus, disabled, error and turn remain identifiable by text.'},'states':['Preference loading → resolved OS choice → user override → adapter persist; persistence failure keeps active preference and reports retry.','Dialog enter stores invoker; trap/restoration must be verified on platform, Escape policy explicit.','Compact affects margins and grouping, not target/readability. DOM/canvas parity is a future implementation requirement.']},
 '02-discovery':{'paths':['crates/tabula-registry/src/lib.rs','crates/tabula-game-api/src/metadata.rs','crates/tabula-game-api/src/capabilities.rs','apps/web/src/main.rs'],'screens':{'01-library':'Search + capability filters above a compact 3-column catalog, resume card before browse. At390px use one column and short cover/icon treatments. Desktop all5games fit within viewport.','02-game-detail':'Lead with game metadata and available local action. Mode list exposes unavailable reasons. Rules/resources are versioned to module.','03-new-match':'Single form, config validation and summary. Local/AI/online options come from CapabilitySet. Time controls/timer only enabled when actual module exposes them. Mobile summary follows inputs and CTA follows validation.'},'states':['Loading manifest → skeleton; no results → reset filter; module load error → reason + retry.','Unavailable mode disables action with visible reason; never route into a fake online/bot flow.','Setup failure preserves config and allows retry; canonical game state starts only after successful creation.']},
 '03-gameplay':{'paths':['games/chess/src/presentation/mod.rs','games/tiles/src/presentation.rs','crates/tabula-presentation/src/lib.rs','crates/tabula-presentation/src/input.rs','apps/game-client/src/main.rs','apps/game-client/web/index.html'],'screens':{'04-chess':'Board-first560px board, tabular clock, move list and focus/BoardReader area. Position corresponds to6...O-O; f3WhiteKnight selected; legal destinations and last king move agree. Clocks/moves are sample values. Promotion sheet remains separate from canonical state.','06-tiles':'Large pan/zoom map, current tile, player score list, separated rotate/place/cancel controls44dp. Existing34dpHUD target is the explicit correction. Validity markers use shape+text.','05-caro':'Caro adapter screen is a planned rules/presenter reference only. Grid/last move/focus and side panel do not imply a complete playable implementation.','07-werewolf':'Same companion SVG contains an explicit Ma sói panel: own role is privately revealed, public roster/liveness/vote/phase comes from permitted projection. No other-player secret roles. Canonical W2initial state is not a full rules/presenter.'},'states':['Local: selection → validated command → authoritative View → move/event announcement; no optimistic canonical mutation.','Loading: real progress or indeterminate+cancel; error not stderr-only. Reconnect: freeze move input, preserve snapshot, resync before unlock.','Promotion:4legal choices, focus path and cancel policy. Invalid action keeps context and gives reason.','Web zoom200% must remain enabled; BoardReader support is a required adapter feature, not certified in this static deliverable.']},
 '04-replay':{'paths':['apps/game-client/src/replay_capture.rs','crates/tabula-game-api/src/lib.rs','apps/web/src/main.rs'],'screens':{'09-result':'Result summary from game result/event, explicit reason, players and next actions. No invented Elo/accuracy/streak. Storage/export actions gated by adapter.','10-history':'Compact sortable/filterable rows with game/mode/result/ply/date and readable metadata. Empty and incompatible replay states inline.','11-analysis':'Generic replay controller: immutable original, current ply12, explicit branch creation. Keyboard first/prev/next/last and timeline announced. Xiangqi PV/evidence extension lives only in pack05.'},'states':['Import: detect game/version, validate input and checksum before playback; incompatible exposes metadata and fails closed.','Playback: current ply only; seek derives view deterministically; do not mutate original. Branch dirty/save/discard state explicit.','Result save failure retains outcome; export states specify actual format/version and no unsupported replay fidelity claims.']},
 '05-xiangqi':{'paths':['docs/architecture/02-game-module-and-sdk-design.md','docs/architecture/04-frontend-and-design-system.md','docs/architecture/07-phases-and-implementation-roadmap.md'],'screens':{'08-xiangqi':'Board-first Play view with planned module/provider gate. Local only after rules/presenter; bot only after engine probe.','11-xiangqi-analysis':'Xiangqi-specific extension over pack04controller: engine missing state, evidence/PV, budget and cancellation. Evaluation data must includeprovider/version, depth, nodes, elapsed and position identity.','12-learn':'Tutor conversation grounded in position and engine evidence. No LLM in this mock; no assertions of best move when evidence missing. Explicit evidence links to board/ply/branch.','14-resources':'Install lifecycle and metadata reference: official provider/source,license,size,checksum,compatibility; resource state cannot sayready until verify+probe.'},'states':['Missing engine / no LLM → visible explanation; analysis controls gated; learning facts only from valid resources.','Position/branch changes → stale evidence badge; cancel obsolete work; never paint prior evaluation as current.','Worker progress has cancellable budget CPU/thread/time; error/retry idempotent; no duplicate provider jobs.','Engine/model download is not performed here; platform compatibility must be proven before UI offers installation.']},
 '06-accounts':{'paths':['apps/web/src/main.rs','services/tabula-server/src/main.rs','docs/architecture/07-phases-and-implementation-roadmap.md'],'screens':{'15-login':'Compact auth panel with local escape route, email/password visibility,remember choice and generic errors. Prototype neither captures credentials nor creates a session.','16-register':'Display name/email/password and actual linked legal terms only when real auth exists. No fake signup/auto-session after mock submit.','20-profile':'Editable display metadata, visibility and server-backed statistics only when adapters exist; placeholders have reasons. Default identity is genericBạn.','21-friends':'Stable accountIDsearch, request state, private/block behavior and age/staleness of presence. Invitation actions are adapter-gated.'},'states':['Signed out / loading / signed in / expired / offline states distinct; local games remain reachable.','Auth error message does not reveal account existence; field errors remain associated with labels.','Profile save pending/error keeps dirty form. Friend pending/accepted/rejected/blocked states derive from service, not UI-only toggles.']},
 '07-lobby':{'paths':['crates/tabula-lobby/src/lib.rs','crates/tabula-net-client/src/lib.rs','services/tabula-server/src/main.rs','apps/web/src/main.rs'],'screens':{'17-rooms':'Compact room rows + search/mode filters + join code/create entry. Capacity andpresence are server-authoritative; stale/offline listing marked.','18-room':'Player slots/host/config/ready/chat withrevision awareness. Config change invalidatesready; start waits for authorization and serverack/session.','19-queue':'Ticket-backed elapsed waiting, no fake ETA/rating/opponents; matchfound/cancel/timeout/reconnect race states explicit. QueueSVG is editable even though mobilevariant is selected for compact PNG set.'},'states':['Create/join: validate code,auth,capacity,compatibility; full/expired/permission errors preserve navigation context.','Ready is acked state. Start only with valid players and shared configrevision; duplicate start prevented.','Queue: request→ticket→waiting→matched or cancelled/expired; cancellation race reconciles server result; retry does not make duplicate tickets.','Reconnect identifies session/ticket before retry. Online cannot silently turn into local. Chat only afterauth+permission+room session.']}}
COMMON='''## How to use this small pack

Open index.html in a browser to select each editable SVG screen; the viewer is a static design navigator, not a runnable game. No network calls, auth, rules, payments, installs, engine or AI execute. Open individual screens/*.svg for direct editing. Run node render.mjs with Sharp installed from the official npm registry to regenerate the3preview PNGs; no screenshot/browser capture is claimed.

## Shared layout / component contract

- Desktop1440×1000: rail176px, topbar64px, task title26px, body14/16px, compact metadata12px. Sans hierarchy replaces the original44px serif/306px hero. Board view gets the first large region; ancillary content follows.
- Mobile390px: one-column task-first view, topbar58px, navigation56px, canvas before detail sheet. Never scale down actions below44logicaldp. 200%browser zoom must remain enabled in implementation.
- Existing tokens.toml is the single source. Use generated Rust/CSS/JSON. Exact four schemes are light,dark,hc-light,hc-dark; focus3dp primary; min target44dp; card16dp,board12dp,button14dp,chip8dp. Board art colors inherited from the original prototype are design/art extensions, not new product semantic tokens.
- Foundation owner: buttons/icon-buttons, tabs, fields, compact rows/cards, capabilities/badges, alerts/progress/error/empty, dialogs/sheets/toasts. Reference pack01instead of copying theme logic. Showcase22andsettings13are distinct surfaces.
- Focus/order/AT/live announcement,hover/pressed and actual keyboard actions require implementation/platform QA. Static rendered SVG is not accessibility proof. Visual circles/toggles/checkbox glyphs specify44dp wrapper hit targets, not their small drawn marks.
- Label unavailable features visibly withreason. Labels CURRENTdescribe audited module availability, not a working portal route. Auth/lobby/replaystorage/settingsshell arephase-gated.
- All names,clocks,moves,counters,roomcodes,presence andscores are sampledata. Design instructions never provide engine/network authority. i18n plan: stable en/vi message keys, no string concatenation forplural/status, locale-awaretime/date andnotation fromgame adapter.

## State matrix required by implementation

Default / hover / pressed / disabled-with-reason / keyboardfocus / loading / busy / empty / validationerror / serviceerror / stale / offline. Primaryactions cannot imply successful work before authority/adaptersacknowledge. Modal focus returns toinvoker; error announcer and boardreader follow platform contracts. Reduced-motionuses canonicalmotion preference and OSsetting; no decorative spinner dependency.

## Verification boundary

This deliverable has SVG/XML parse checks,source-syntax checks,image dimensions/sizechecks and visualinspection. No Rust build/runtime/screenshots,real engine/AI/network,screenreader audit,all-browser layout orphaseexit certification performed. PRs must pin current HEAD,read AGENTS.md andarchitecture00/04/07/09,follow repo verification skills,invariant→oracle→evidence,targeted tests then justcheck,explicitly reportwhat wasnotrun. Do not auto-regenerate goldens.
'''
for p,d in DETAILS.items():
 folder=OUT/p
 body='# Tabula Design02 / '+PACKS[p][0]+'\n\nScope: design only. Audited develop @ '+AUDIT+'. Future implementation must re-pin HEAD and phase gates.\n\n'+COMMON+'\n## Per-screen ownership and details\n\n'
 for k,v in d['screens'].items():body+='### '+k+'\n\n'+v+'\n\n'
 body+='## Specific flows / failure states\n\n'+''.join('- '+v+'\n' for v in d['states'])+'\n## Existing code to compare\n\n'+''.join('- ['+x+']('+REPO+x+')\n' for x in d['paths'])
 body+='\n## Small sequential PR prompts\n\nSee implementation-prompts.md for the reviewed source-grounded issue plan. Each prompt is a separate PR; this design branch itself changes no production code.\n'
 (folder/'implementation-notes.md').write_text(body)
 draft=ROOT.parent/'tabula-issue-drafts'/(p+'.md')
 if draft.exists():
  text=draft.read_text();a=text.find('## Prompt PR');b=text.find('## Nghiệm thu',a);(folder/'implementation-prompts.md').write_text(text[a:b] if a>=0 else text)
 (folder/'README.md').write_text('# '+PACKS[p][0]+'\n\nTabula Design02; static reference and sampledata.\n\n- index.html + prototype.css + viewer.mjs:static screen navigator\n- screens/*.svg:scoped,editable desktop/mobile sources\n- previews/*.png:two desktopboards+one purpose-built mobile/stateboard\n- implementation-notes.md:screen/state/adapter/a11y contract\n- implementation-prompts.md:small sequentialPRprompts\n- render.mjs:reproducible SVG→PNG renderer (Sharp)\n\nShared canonical snapshots andcomponent contract are included only in01-foundation. Otherpacks reference that foundation. Do not copy mockSVGliterals into productiontheme or port the board intoDOM.\n')
 # Drop stale PNGs; only renderer manifest is deliverable.
 keep=set(PACKS[p][1][:2]+['mobile-states'])
 for f in (folder/'previews').glob('*.png'):
  if f.stem not in keep:f.unlink()
# Shared reference snapshots exactly once, no extra SSOT.
shared=OUT/'01-foundation'/'shared';shared.mkdir(exist_ok=True)
for ext in ['toml','json','css']:shutil.copy(ROOT/'source'/('canonical-tokens.'+ext),shared/('canonical-tokens.'+ext))
(shared/'README.md').write_text('Read-only snapshots of audited tokens.toml/generated CSS/JSON@'+AUDIT+'. Product SSOT remains repository-root tokens.toml. Boardart/compactlayout are reference extensions, not generatedtokens. Focus3dp/minTarget44dp; any componenttokenproposal needs an actualconsumer and writtenreason.\n')
component={'source_commit':AUDIT,'min_target_dp':44,'focus_ring_dp':3,'focus_color':'primary','components':{'ActionButton':['default','hover','pressed','disabled','focused','busy'],'CapabilityBadge':['current','planned','unavailable','stale'],'Field':['default','focus','validating','invalid','disabled'],'CompactRow':['default','selected','focus'],'DialogSheet':['open','busy','error','focus_restore'],'BoardStatus':['turn_active','turn_waiting','selected','legal_target','last_action','offline']},'owners':{'theme':'tokens.toml + xtask','web_shell':'Leptos after Phase5 gate','gameplay':'Macroquad + RenderList','game_state':'GameRules authority, never local mockcontroller'}}
(shared/'component-contract.json').write_text(json.dumps(component,ensure_ascii=False,indent=2))
# Actual exact four-theme same-content board, editable foundation source.
tokens=json.loads((shared/'canonical-tokens.json').read_text());s=Scene();s.rect(0,0,1440,1000,P['bg'],r=0);s.text(56,53,'Theme parity · canonical four schemes',28,weight=700);s.text(56,87,'Exact snapshots from tokens.toml; same content/layout in every scheme · 44dp target · 3dp focus',14,P['muted'])
for i,key in enumerate(['light','dark','hc-light','hc-dark']):
 c=tokens['schemes'][key];x=56+(i%2)*684;y=132+(i//2)*402;s.rect(x,y,660,378,c['surface'],c['outline'],r=16);s.text(x+24,y+42,key,23,c['on-surface'],700);s.rect(x+24,y+66,612,76,c['container'],r=12);s.text(x+44,y+98,'Đến lượt bạn / White to move',17,c['turn-active'],600);s.text(x+44,y+125,'Status uses text + marker, never color alone',13,c['on-surface-variant']);s.rect(x+24,y+168,286,44,c['primary'],r=14);s.text(x+167,y+197,'Primary · 44dp',15,c['on-primary'],600,'middle');s.rect(x+20,y+164,294,52,'none',c['primary'],r=18,sw=3);s.rect(x+330,y+168,306,44,c['container'],c['outline'],r=14);s.text(x+483,y+197,'Disabled · reason visible',14,c['on-surface-variant'],600,'middle');s.rect(x+24,y+238,612,90,c['container-high'],r=12);s.text(x+44,y+269,'Không nạp được module / Load failed',16,c['danger'],600);s.text(x+44,y+301,'Keep input + clear retry action; no stderr-only failure',13,c['on-surface-variant']);s.text(x+24,y+356,'surface / container / primary / on-primary / outline / danger',11,c['on-surface-variant'])
f=OUT/'01-foundation/screens/23-theme-parity.svg';f.write_text(s.svg('Canonicaltheme parity'));folder=OUT/'01-foundation';idx=json.loads((folder/'screen-index.json').read_text());idx.append({'id':'23-theme-parity','title':'Four canonical schemes','file':'screens/23-theme-parity.svg'});(folder/'screen-index.json').write_text(json.dumps(idx,ensure_ascii=False,indent=2));ht=(folder/'index.html').read_text();a=ht.index('<script id="screen-data"');b=ht.index('</script>',a);old=ht[a:b];t=old.index('>')+1;(folder/'index.html').write_text(ht[:a]+old[:t]+json.dumps(idx,ensure_ascii=False)+ht[b:])
# Mainhuman-readable index andcoverage
trace=json.loads((OUT/'traceability.json').read_text());lines=['# Tabula Design02 · scoped screen packs','','Designonly. StaticSVG+PNG references,sampledata. Auditeddevelop44f6b74; notruntime screenshots.','','## Seven small implementationboundaries','']
for pack,(title,prev) in PACKS.items():lines.append('- ['+pack+' · '+title+']('+pack+'/README.md): [downloadZIP](packages/'+pack+'.zip) · [screensource]('+pack+'/index.html) · [mobilepreview]('+pack+'/previews/mobile-states.png)')
lines+=['','##22screencoverage','']
for r in trace:lines.append('- '+r['input_screen']+' → '+r['pack']+' / '+r['title'])
lines+=['','Screen11genericreplay belongs04. Xiangqispecificevidence/PV extension belongs05. Screen05and07share anexplicit adapter/recovery board withseparate Caro/Masói panels. Sourcefor all22screens plusXiàngqi-specificanalysis,7actual mobileboards andfour-theme parity included.','','## Foundation reuse','','01owns exact read-onlycanonicaltokens snapshots andsmall component/statecontract. No newproductthemeSSOT. Otherpacks include onlytheir scoped sources; no original10.82MBZIP,externalimages,binaries,fontfiles,node_modulesorappbundle.','','## Comparison / validation','','Original ZIP visual language:purple/light-dark semantic scheme,sageChess/Tiles,warm Xiangqiboard. Improvedchrome andtask hierarchy:176pxrail/64pxtopbar,compact sans titles,boardfirst,clear sample/gatedstates. Validation isstaticvisual/source QAonly; runtime/a11y/engine/networkbehavior mustbeproven during futurePRs.']
# Legible normalwordspacing: retain intentional identifiers only.
(OUT/'README.md').write_text('\n'.join(lines)+'\n')
# copied generator for reproducible all-screen editing, once atmasterlevel
source=OUT/'source';source.mkdir(exist_ok=True)
for name in ['build_designs.py','mobile_boards.py','package_designs.py']:shutil.copy(ROOT/'source'/name,source/name)
print('Pack notes, canonical foundation andmasterindex written')
